### PR TITLE
Melodic devel

### PR DESCRIPTION
**Pull request by edetleon**
Hello,

I use ROS melodic with Ubuntu 18.04.
I had an issue with the IKFast (wich uses openrave 0.9.0) while generating the IK solver type TranslationXY2D for a robot arm that I created myself.* 
The generation had some errors, but I could generate the package and compile my workspace anyway. When I opened it in Rviz (with the command _roslaunch pkg_name demo.launch_) and tried to move it, I couldn't move the robot and had the following error : 

**[ERROR] [1583159947.486174117]: IK for this IkParameterizationType not implemented yet.**

This is exactly the same problem reported in the 2 links below for the IK solver type "Translation3D" and "TranslationYaxis4D", except that these posts concern older versions : 

https://answers.ros.org/question/191884/ik-for-this-ikparameterizationtype-not-implemented-yet/
https://github.com/ros-planning/moveit/issues/548

I followed the developers advices and I added 2 lines of code in the source file "pkg_name_ikfast_moveit_plugin.cpp" generated by the solver. Now it works and I can move the arm with Rviz, using the interractive marker. This is the lines that I added after "case IKP_TranslationXY2D" (**line 592, you will fid the code below) : 

trans[2] = 0;

      ComputeIk(trans, direction.data, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

It would be good to implement the TranslationXY2D type of IK solver, as well as the Translation2DOrientation1D type, because as far as I know, there is no existing IK solver for robots with low DOF.

If someone could read this, and take the time to do the implementation, thank you very much !

Best regards,

Edith

*To install and generate the IK Solver, I followed the tutorial linked below, and I used the following command line to generate the solver : 
rosrun moveit_kinematics auto_create_ikfast_moveit_plugin.sh --iktype TranslationXY2D $MYROBOT_NAME.urdf <planning_group_name> <base_link> <eef_link>

http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast/ikfast_tutorial.html

****Here is the code concerned :** 

solutions.Clear();

  double trans[3];
  trans[0] = pose_frame.p[0];
  trans[1] = pose_frame.p[1];
  trans[2] = pose_frame.p[2];

  KDL::Rotation mult;
  KDL::Vector direction;

  switch (GetIkType())
  {
    case IKP_Transform6D:
    case IKP_Translation3D:

      mult = pose_frame.M;

      double vals[9];
      vals[0] = mult(0, 0);
      vals[1] = mult(0, 1);
      vals[2] = mult(0, 2);
      vals[3] = mult(1, 0);
      vals[4] = mult(1, 1);
      vals[5] = mult(1, 2);
      vals[6] = mult(2, 0);
      vals[7] = mult(2, 1);
      vals[8] = mult(2, 2);

      // IKFast56/61
      ComputeIk(trans, vals, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    case IKP_Direction3D:
    case IKP_Ray4D:
    case IKP_TranslationDirection5D:
      // For **Direction3D**, **Ray4D**, and **TranslationDirection5D**, the first 3 values represent the target
      // direction.

      direction = pose_frame.M * KDL::Vector(0, 0, 1);
      ComputeIk(trans, direction.data, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    case IKP_TranslationXAxisAngle4D:
    case IKP_TranslationYAxisAngle4D:
    case IKP_TranslationZAxisAngle4D:
      // For *TranslationXAxisAngle4D*, *TranslationYAxisAngle4D*, *TranslationZAxisAngle4D* - end effector origin
      // reaches desired 3D translation, manipulator direction makes a specific angle with x/y/z-axis (defined in the
      // manipulator base link’s coordinate system)
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;

    case IKP_TranslationLocalGlobal6D:
      // For **TranslationLocalGlobal6D**, the diagonal elements ([0],[4],[8]) are the local translation inside the end
      // effector coordinate system.
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;

    case IKP_Rotation3D:
    case IKP_Lookat3D:
    case IKP_TranslationXY2D:

      trans[2] = 0;

      ComputeIk(trans, direction.data, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    case IKP_TranslationXYOrientation3D:
      ROS_ERROR_NAMED(name_, "IK for this IkParameterizationType not implemented yet.");
      return 0;

    case IKP_TranslationXAxisAngleZNorm4D:
      double roll, pitch, yaw;
      // For **TranslationXAxisAngleZNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to z axis and be rotated at a certain angle starting from the x axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &yaw, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    case IKP_TranslationYAxisAngleXNorm4D:
      // For **TranslationYAxisAngleXNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to x axis and be rotated at a certain angle starting from the y axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &roll, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    case IKP_TranslationZAxisAngleYNorm4D:
      // For **TranslationZAxisAngleYNorm4D** - end effector origin reaches desired 3D translation, manipulator
      // direction needs to be orthogonal to y axis and be rotated at a certain angle starting from the z axis (defined
      // in the manipulator base link’s coordinate system)
      pose_frame.M.GetRPY(roll, pitch, yaw);
      ComputeIk(trans, &pitch, vfree.size() > 0 ? &vfree[0] : nullptr, solutions);
      return solutions.GetNumSolutions();

    default:
      ROS_ERROR_NAMED(name_, "Unknown IkParameterizationType! "
                             "Was the solver generated with an incompatible version of Openrave?");
      return 0;
  }
}

void IKFastKinematicsPlugin::getSolution(const IkSolutionList<IkReal>& solutions, int i,
                                         std::vector<double>& solution) const
{
  solution.clear();
  solution.resize(num_joints_);

  // IKFast56/61
  const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
  std::vector<IkReal> vsolfree(sol.GetFree().size());
  sol.GetSolution(&solution[0], vsolfree.size() > 0 ? &vsolfree[0] : nullptr);

  for (std::size_t joint_id = 0; joint_id < num_joints_; ++joint_id)
  {
    if (joint_has_limits_vector_[joint_id])
    {
      solution[joint_id] = enforceLimits(solution[joint_id], joint_min_vector_[joint_id], joint_max_vector_[joint_id]);
    }
  }
}

### CODE REVIEW

**Comment by felixvd** [comment]
I think you selected the wrong branches when you submitted the pull request. If I understand correctly, you have made code changes that you would like to merge. Please [follow these instructions to file a pull request properly](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). In short, you should first push your code to a fork on Github then submit the PR using a branch in your fork..

Also, please read the [contributing guidelines](https://moveit.ros.org/documentation/contributing/code/).

**Comment by edetleon** [comment]
> This looks like it should be an issue not a PR



> I think you selected the wrong branches when you submitted the pull request. If I understand correctly, you have made code changes that you would like to merge. Please [follow these instructions to file a pull request properly](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). In short, you should first push your code to a fork on Github then submit the PR using a branch in your fork.
> 
> Also, please read the [contributing guidelines](https://moveit.ros.org/documentation/contributing/code/) and fix the formatting of the original post. It is hard to read.

**Comment by edetleon** [comment]
Thank you for your answers !

**These are not code changes**. I had to change the code that was _generated_ by IKFast, the moveit plugin. This is more an issue to me, but I found a similar issue there, and the answers suggest to make a pull request : https://github.com/ros-planning/moveit/issues/548

**Comment by felixvd** [comment]
I think you may want to read [this](https://opensource.stackexchange.com/questions/352/what-exactly-is-a-pull-request). If there is no code you need to submit, the discussion should be done in an issue.

**Comment by edetleon** [comment]
> I think you may want to read [this](https://opensource.stackexchange.com/questions/352/what-exactly-is-a-pull-request). If there is no code you need to submit, the discussion should be done in an issue.

Thank you, I will do that

**Pull request closed without merging**
