### PR TITLE
Pass robot_description parameter in RobotCommander.get_group

### PR DESCRIPTION
**Pull request by rkeatin3**
### Description

When using a parameter other than "/robot_description", `RobotCommander.get_group()` will fail in creating a `MoveGroupCommander`. The name of the parameter needs to be passed.

### Checklist
- [ ] **Required**: ~~Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)~~ 
Not applicable. My changes are PEP-8 compliant, though. 

I realize that it would have been cleaner to reset my indigo-devel to origin/indigo-devel rather than merge. I can redo this PR if that's at all problematic.

### CODE REVIEW

**Comment by rkeatin3** [comment]
Agreed. Resetting my branch to origin/indigo-devel from my previous PR would have avoided part of that headache, yeah? 

Any other feedback appreciated, as I'm fairly new to git and very new to open-source software development.

**Comment by bmagyar** [comment]
No worries about that, this is great. 

I do have to add a new note though...It is preferred to submit PR-s against `kinetic-devel` (where the same issue persists) as that is our current main branch. In the submission of the PR you can then recommend the PR to be cherry-picked back to Indigo too. Please submit a new PR against `kinetic-devel`. It will be the same changes, it's also a good opportunity to clean up the commit log :) Once submtited the new one, you can close this PR.

**Comment by rkeatin3** [comment]
Sure thing, will do.

It's easy to verify `kinetic-devel` has the same issue in this case. In the case that it isn't or that I have to touch the C++, are there any ways for me to help you maintainers given that I don't have a machine with 16.04/Kinetic?

Thanks for the input!

**Comment by rkeatin3** [comment]
See new PR for `kinetic-devel`: [https://github.com/ros-planning/moveit/pull/782](https://github.com/ros-planning/moveit/pull/782).

**Pull request closed without merging**
