### PR TITLE
code  clean up of moveit_core

### PR DESCRIPTION
**Pull request by bailaC**
### Description

The repetitive namespace declaration has been removed from all the spaces.

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by davetcoleman** [comment]
I do not want to merge this until https://github.com/ros-planning/moveit/pull/662 because it has some really valuable collision checking improvements that will conflict i think.

**Comment by davetcoleman** [comment]
@bailaC could you rebase with the recent changes? then we can quickly merge this before more merge conflicts happen

**Comment by rhaschke** [comment]
> @bailaC could you rebase with the recent changes? then we can quickly merge this before more merge conflicts happen

Probably it's easier (and safer) to redo those automatic changes...

**Comment by bailaC** [comment]
Sure @davetcoleman , @rhaschke ...I will do the rebase and commit asap.

**Comment by bailaC** [comment]
I am getting too much conflicts for my forked repo. Give me some time to figure out things.

**Comment by bailaC** [comment]
I think i made too much mistakes while rebasing my repo. I want to close this PR as I am not able to fix all these. I am very sorry for messing all these thing.

**Comment by rhaschke** [comment]
@bailaC As stated above, I would have been easier to redo those changes. I guess you used some query-replace function on the whole repository anyway, didn't you?

**Comment by bailaC** [comment]
Yes @rhaschke. I am on my way to redo those changes. Can i use this same PR for my changes again?

**Comment by rhaschke** [comment]
@bailaC No, you need to create a new PR. I'm closing this one now.

**Pull request closed without merging**
