### PR TITLE
Noetic changelogs and version bump (1.1.2)

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Changelogs and version bump for Noetic release 1.1.2

### CODE REVIEW

**Review by henningkayser — APPROVED** [review]

**Review by felixvd — APPROVED** [review]
LGTM, but why does Travis fail on clang?

**Comment by rhaschke** [comment]
We didn't had a single successful master branch build on Travis [since 18 days](https://travis-ci.com/github/ros-planning/moveit/builds), namely since the Pilz planner (#1893) was merged!
The core reason is that we are running out of build time - exactly what I predicted before!
Even worse, Travis has changed it's pricing model: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing.
Currently, all CI jobs are disabled, because we already consumed all our free credits. @davetcoleman we need to discuss urgently, how to mitigate this issue.

Additionally, there is a flaky unit test:
```
build/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rosunit-move_group_pick_place_test.xml: 2 tests, 0 errors, 2 failures, 0 skipped
Summary: 1618 tests, 0 errors, 2 failures, 2 skipped
```

**Comment by tylerjw** [comment]
I started debugging the test that is flaky yesterday but don't have a fix for it.  Some testing yesterday showed that that notice on Travis is not telling the truth and it is running ci (for now atleast).  I have started working on circleci and am using GitHub actions on one customer project.  I have yet to get better performance out of circleci and wouldn't recommend it yet.  GitHub actions seems to be faster than Travis (Microsoft might be throwing money at more powerful machines to try to get people to switch).  To use GitHub actions the easiest way will be to use industrial_ci.  There are a handful of things we have in moveit_ci that we would lose until we get those things upstreamed.  One of them is code coverage which is almost in industrial_ci.

Another decision we should consider is (grasp) breaking up the repo.  One sort of obvious thing we could factor out is anything that depends on qt.  That would make for faster builds and have the advantage that people who depend on moveit but don't want the qt stuff but don't have them on their target can stop having to deal with our qt dependency.

On top of all this the noetic fcl thing isn't building and causing problems for the official buildfarm.

**Comment by rhaschke** [comment]
> I started debugging the test that is flaky yesterday but don't have a fix for it.

What's the culprit?

> On top of all this the noetic fcl thing isn't building and causing problems for the official buildfarm.

Can you provide any evidence, e.g. a link to a buildfarm build?

**Comment by tylerjw** [comment]
https://github.com/ros/rosdistro/issues/27401

**Comment by tylerjw** [comment]
> > I started debugging the test that is flaky yesterday but don't have a fix for it.
> 
> What's the culprit?
> 
I don't know yet.

**Comment by jschleicher** [comment]
> We didn't had a single successful master branch build on Travis [since 18 days](https://travis-ci.com/github/ros-planning/moveit/builds), namely since the Pilz planner (#1893) was merged!

The [PR builds](https://github.com/ros-planning/moveit/runs/1344474201) before the merge did succeed. But it takes veeryy long:
grafik

Is ros-planning/moveit_ci#73 still active? It seems like clang-tidy runs on all files (again) - while no files changed in the current PR?

**Comment by tylerjw** [comment]
Picknik now paying for the 1 runner plan on Travis to have a temporary solution to the timeouts.  This will probably make CI take longer but not timeout.  In the long-ish term I will be investigating the other providers and doing work to support them to try to find a better solution than Travis.

**Comment by rhaschke** [comment]
@tylerjw: The ROS build farm is complaining about missing pilz packages, e.g.: moveit_resources_prbt_moveit_config
http://build.ros.org/job/Ndev__moveit__ubuntu_focal_amd64/20/display/redirect

Didn't you already release those?

**Comment by jschleicher** [comment]
@tylerjw It seems, there hasn't been a release of [ros-planning/moveit_resources](https://github.com/ros-planning/moveit_resources/) since october?!

**Comment by tylerjw** [comment]
I remember releasing moveit_resources when I did the last noetic release.  It appears I didn't though.  We should release it so the build farm is happy.

**Comment by jschleicher** [comment]
@tylerjw actually this PR (#2423) ist still open, so neiter the november moveit release nor the release of moveit_resources got bloomed? When do you plan to do the release?

**Comment by tylerjw** [comment]
@jschleicher I am planning on doing a release once some of the tests become more robust.  With the current state of our runners on travis the move_group interface test and subframes test has become flaky.  I'm working with @bostoncleek to get that resolved so it stops blocking the OMPL constrained space PR and many others.  I'm hoping that we'll have a solution for that within the next couple weeks.

**Comment by jschleicher** [comment]
@tylerjw  We're still waiting for a binary release including the pilz_industrial_motion_planner. Is there any news on your side?
>within the next couple weeks.

**Comment by tylerjw** [comment]
closing this as 1.1.2 just went out

**Pull request closed without merging**
