### PR TITLE
[backport] Make GILReleaser exception-safe and Improved Unit Test for ByteString

### PR DESCRIPTION
**Pull request by gleichdick**
### Description

Backport #2362 and #2363 to melodic-devel

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by rhaschke** [comment]
First let's get the original PRs merged :wink: I will back-port them to melodic subsequently.

**Comment by rhaschke** [comment]
Ok. Just noticed that you already resolved some conflicts...

**Comment by gleichdick** [comment]
Only the GILReleaser patch was conflicting. But now there is a unused variable?
```diff
--- a/moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
+++ b/moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp
@@ -467,10 +467,9 @@ public:
   py_bindings_tools::ByteString getPlanPython()
   {
     MoveGroupInterface::Plan plan;
-    moveit_msgs::MoveItErrorCodes res;
     {
       GILReleaser gr;
-      res = MoveGroupInterface::plan(plan);
+      MoveGroupInterface::plan(plan);
     }
     return py_bindings_tools::serializeMsg(plan.trajectory_);
   }
```

**Comment by rhaschke** [comment]
Superseeded by #2368

**Pull request closed without merging**
