### PR TITLE
[Fix] missed naming problems

### PR DESCRIPTION
**Pull request by jeasinema**

### CODE REVIEW

**Comment by v4hn** [comment]
Thanks for bringing this to my attention @jeasinema .

@davetcoleman @rhaschke @bmagyar @IanTheEngineer I know we just accepted this API change as-is in srdfdom and geometric_shapes, but do we really want that all across MoveIt?
I propose to add a new compatibility header instead similar to https://github.com/ros-planning/geometric_shapes/pull/85 instead, but the other way around.

I would just alias `log*` as `CONSOLE_BRIDGE_log*` in newer versions to avoid all these changes and more importantly not clutter the code even more.

Opinions?

**Comment by rhaschke** [comment]
No objections to switch back to `log*` using an appropriate header `include/moveit/macros/logging.h`.

**Comment by davetcoleman** [comment]
While this temporary fix seems fine, my bigger picture objections are outlined here: https://github.com/ros-planning/moveit/issues/860

**Comment by v4hn** [comment]
Closed in favor of #874

**Pull request closed without merging**
