### PR TITLE
cleanup urdfdom compatibility

### PR DESCRIPTION
**Pull request by rhaschke**
This PR cleans up #317, relying on a compatibility layer in the upstream package `urdf` instead.

Attention: This relies on https://github.com/ros/robot_model/pull/160 and thus should only be merged when this upstream is released.

### CODE REVIEW

**Comment by rhaschke** [comment]
ros/robot_model#160 was released: https://github.com/ros/rosdistro/pull/13092

**Comment by 130s** [comment]
Seems mergeable to me but I'll wait for confirmation from others.

**Comment by davetcoleman** [comment]
I think this PR is low priority and should not be merged until the next buildfarm sync, so that our Travis tests don't fail for non-shadow-fixed, as @v4hn suggested.

**Comment by davetcoleman** [comment]
Merging because the compatibility layer is causing [issues](https://github.com/ros-planning/moveit/issues/357#issuecomment-260611506) with the ROS buildfarm.

This will unfortunately break our source build until the next release unless you are on shadow-fixed - I'll disable the Travis test for now

**Pull request merged**
