### PR TITLE
fixed numpy.ndarray indices bug (from #86)

### PR DESCRIPTION
**Pull request by Kukanani**
### Description

A fix for the numpy.ndarray indices bug, the second bug described in #86.

This fix was proposed by @lifangda01 in the same issue.

I was unsure what to do about clang-format, since it seems that it's for C++ only.

### Checklist
- [ ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

Thank you!

### CODE REVIEW

**Comment by v4hn** [comment]
Nice! Thanks for the pull-request. You're right, strict formatting is only required for C++ (for now...).

I just verified, pyassimp moved from an internal datatype to numpy.ndarray for these fields.

Until now the code is compatible with the pyassimp versions of ROS indigo and kinetic.
This patch breaks compatibility with the old version.

Would you mind to change it into something along the lines of
```
if hasattr(face, '__len__') and len(face) == 3:
    ....
elif hasattr(face, 'indices') and len(face.indices) == 3:
    ....
```
to allow the script to run with the old version too?

**Comment by Kukanani** [comment]
Full disclosure: if accepted, this would be my first successful pull request.

I added an error that is thrown if both approaches fail. Let me know if that's being "too safe." Also, these checks are being run for every face in the mesh, which is extremely slow. I think the better design would be to check only the first face to determine the pyassimp version, then run one of two operations based on the check.

**Comment by v4hn** [comment]
Hm, apparently GitHub decided to drop the mail response I sent yesterday evening. Sorry for that.
Here it is again:

~~~

Hehe, welcome to the happy folks who file pull-requests :)

You're right, it's not very efficient to check this for every face.
Sure, you can also move the conditional outside the loop and run different
loops if you prefer that.

Sadly, the library itself does not seem to export its own version, but in this
case, it might be better to set a global indicator `PYASSIMP_VERSION`(?) at the
very beginning of the file and use that for the check.
There's a conditional there already because pyassimp > 3.0 is included via
`import pyassimp` and not via `from pyassimp import pyassimp` anymore.

I don't think the additional exception is a good idea though.
The old code just ran on when it encountered an invalid face and added an empty
`MeshTriangle`.
Now, we can definitely skip adding the empty entry, but the rest of the mesh
should still be parsed.
There's all kinds of weird mesh files out there, so we should probably extract
whatever we can. :)

**Comment by Kukanani** [comment]
I agree that if we are looping over every face, then it does not make sense to raise exceptions. 

However, in the code I wrote above, the exception at the end is catching the case where the first face specifically is not loadable via either method. It assumes that all the faces in the mesh have the same Python structure. If that's not the case, then I would propose keeping the loop  structure as it currently is, where `hasttr()` is evaluated for every face, and then remove the exception.

So I would say that the two best options are 1. Use the code above, checking only the first face's structure, with the exception, or 2. Check every face for pyassimp structure, throwing no exceptions.

**Comment by v4hn** [comment]
> I agree that if we are looping over every face, then it does not make sense to raise exceptions.

Sorry, that is the current state of the pull-request though. I commented on that...

> 1. Use the code above, checking only the first face's structure, with the exception
> 2. Check every face for pyassimp structure, throwing no exceptions.

Both ways are fine by me. Just choose one and implement it in the request. :)

With (1.), you might want to check for `len(scene.meshes) > 0 and len(scene.meshes[0].faces) > 0` before for completeness sake.

**Comment by Kukanani** [comment]
Alright, I think it should be ready to go.

**Comment by cschindlbeck** [comment]
I encountered this bug in the indigo branch as well, the same changes seem to fix that for me, pull request?

**Comment by v4hn** [comment]
@cschindlbeck I still suspect you broke your local setup somehow, but I don't see any harm in having this
in `indigo-devel` too.

Feel free to file a pull-request for this.

**Pull request merged**
