### PR TITLE
Codecov

### PR DESCRIPTION
**Pull request by rhaschke**
Reopening #1765. This is an alternative to #1719, not requiring to touch cmake files.

### CODE REVIEW

**Comment by tylerjw** [comment]
This produced a different but not yet working report: https://codecov.io/gh/ros-planning/moveit/tree/d993faaccd979e3aa33799637d0a8ecf067cfe17

**Comment by tylerjw** [comment]
Also, ccache performance on this was bad (note that the cache size is 500mb), this may have something to do with travis not having a cache to provide for this build as it wasn't able to retrieve the one produced from the previous PR you submitted:
```
cache directory                     /root/.ccache
primary config                      /root/.ccache/ccache.conf
secondary config      (readonly)    /etc/ccache.conf
stats zero time                     Mon Nov 25 14:38:25 2019
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                           790
cache hit rate                      0.00 %
called for link                      662
called for preprocessing              14
no input file                         52
cleanups performed                     2
files in cache                      2273
cache size                         352.1 MB
max cache size                     500.0 MB
```

**Comment by rhaschke** [comment]
It's annoying that the recommended way to upload coverage reports doesn't work [as expected](https://github.com/codecov/example-cpp11-cmake#travis-setup-using-lcov).
Running [genhtml](http://ltp.sourceforge.net/coverage/lcov/genhtml.1.php) locally, generates a correct report from the coverage trace created by my approach.
I will file a bug report to codecov.io.

**Comment by tylerjw** [comment]
I tested this locally and confirmed this is some issue with codecov.io as you reported in the other pr. Hopefully they can fix that soon. I also tested ccache and I can't reproduce the low cache hits locally :/ I think it has something to do with travis and I don't know yet how to debug that.

**Comment by rhaschke** [comment]
I filed an issue with codecov.io: https://github.com/codecov/codecov-bash/issues/232

**Comment by rhaschke** [comment]
Hi @tylerjw,
I just merged this, but the [coverage report](https://codecov.io/github/ros-planning/moveit/commit/d48d57f856b33433c18754497712be8d185a371f) is not accessible on codecov.io. Do we need further settings here or at codecov.io to enable this?

image

**Comment by tylerjw** [comment]
@rhaschke When you go to the overview page it shows that `kinetic-devel` is the main branch and there isn't a coverage report for that.  I believe that is the issue and you should be able to configure it to look at the master branch in the settings page.  I'm not a maintainer so I can't see that page (I get a 404 forbidden if I try to go there).  The other thing you'll find there is the markdown code to add the badge to the readme.

**Pull request merged**
