### PR TITLE
Add more console output colors

### PR DESCRIPTION
**Pull request by davetcoleman**
Adds yellow and purple

### CODE REVIEW

**Comment by v4hn** [comment]
I tend to dislike this kind of color management altogether..
In my opinion, if we want color output we should use proper terminal control, but then I don't think rosconsole supports that at the moment...

Anyway, if you like to have them here, we can of course add them...

Merging / pick to indigo

**Comment by v4hn** [comment]
Sorry, I just reverted and didn't cherry-pick to indigo yet.

Could you please sort the colors by indices (the part after `[`). You will find that your new "yellow" was previously known as "brown".
Please fix this if possible.

**Comment by bmagyar** [comment]
I agree that ROS prints need to have a better way to address colours...

I know it's bad but I tend to carry around this file with me to save time writing the same boilerplate printing code all the time:
https://gist.github.com/bmagyar/5b35cc21428dcdb99b43382969586e79

**Comment by davetcoleman** [comment]
Indeed good catch @v4hn. The color [is misnamed](http://misc.flogisoft.com/bash/tip_colors_and_formatting) in moveit and should be yellow, so I've left both so that its more clear to others who might want to use that macro and yellow. I also added a comment to show they are the same value, and ordered the colors per @v4hn

**Pull request merged**
