### PR TITLE
MoveGroupCommander: Improve exception messages

### PR DESCRIPTION
**Pull request by v4hn**
Slightly improve the exception messages I ran into today.

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
new wording seems to make sense

**Review by felixvd — APPROVED** [review]

**Review by rhaschke — APPROVED** [review]

**Comment by rhaschke** [comment]
This PR triggered two Travis jobs, one of the passed, the other got stalled. What happened here? Other PRs trigger Travis only once.

**Comment by v4hn** [comment]
> This PR triggered two Travis jobs, one of the passed, the other got stalled.
> What happened here? Other PRs trigger Travis only once.

I swear I did not do anything unusual here... Hopefully only some Travis hiccup?

**Comment by gavanderhoorn** [comment]
This is a glitch in the Travis<->GH integration.

**Comment by rhaschke** [comment]
> I swear I did not do anything unusual here...

I wasn't assuming anything in that direction :wink:

**Pull request merged**
