### PR TITLE
add full VERSIONs / SONAMEs to all libraries

### PR DESCRIPTION
**Pull request by v4hn**
See https://github.com/ros-planning/moveit/issues/100#issuecomment-266461246 .

This is similar to #273 / 0a7a895bb2ae9e171efa101f354826366fa5eaff,
but hard-codes the version for each library instead of using the project's version.
Thus, we have to bump the version of a library *manually* if we break ABI in a release.

=== Below is the original commit message of the patch targeting the kinetic branch.

* add full VERSIONs / SONAMEs to all core libraries

As a result the libraries do not install as `libmoveit_xyz.so` anymore,
but as `libmoveit_xyz.so.${MOVEIT_VERSION}` and only provide `libmoveit_xyz.so`
as a symlink pointing to the versioned file.

Because this sets each library's SONAME to the *full version*, this enforces
that *every* binary links with the versioned library file from now on and
has to be relinked with *each* new release of MoveIt!.

The alternative would be to set the SONAME to `$MAJOR.$MINOR` and ignore the patch version,
but because we currently stay with one `$MAJOR.$MINOR` number within each ROS distribution,
we had (and likely will have) ABI changes in the `$PATCH` version releases too.

The reason for this commit is that it is practically impossible to maintain full ABI compatibility
within each ROS distribution and still add the the features/patches the community asks for.
This has resulted in more than one ABI-incompatible MoveIt! release in the recent past
within a ROS distribution. Because the libraries have not been versioned up to now,
there was no way to indicate the incompatible changes and users who did not rebuild
their whole workspace with the new release encountered weird and hard-to-track segfaults
or broken behavior.

* add SONAMES to all non-core libraries too

### CODE REVIEW

**Comment by davetcoleman** [comment]
Would it be cleaner to define the version number once, say [here](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_core/version/) and have all the CMake files pull the variable from there?

**Comment by v4hn** [comment]
No. The whole idea of this approach is to define the version *per library*.
Thus, we can update the version of *exactly* and *only* those libraries that change in ABI in another indigo-release.
In theory, we don't want this to happen, but if we still want to do this in practice, at least we can handle it.

@jspricke: could you please have a look at this request?

**Comment by 130s** [comment]
> @jspricke: could you please have a look at this request?

Friendly ping :)

**Comment by jspricke** [comment]
I've added a +1 already at the top ;)

**Comment by 130s** [comment]
Thanks! Merging.

----

Just trying to understand the maintenance workflow.
So for every single future release, we'll somehow update all these values for 67+ files. Is that correct? Sounds like a lot of effort (don't get me wrong I'm not arguing here) so we better to have a automatic way to do this.

**Comment by jspricke** [comment]
No, that would brake all of the installations for all users every time you make a release.

ABI versions have nothing to do with package release versions. Whenever you change the ABI of some shared object, you increase the ABI version of that particular lib. So the only overhead is to check new releases for breaking changes, what you should do anyhow.

**Comment by v4hn** [comment]
On Tue, Dec 20, 2016 at 10:00:22PM -0800, Jochen Sprickerhof wrote:
> Whenever you change the ABI of some shared object, you increase the ABI version of that particular lib.

Exactly. So we will keep the hardcoded sonames of the individual libraries in future releases *unless*
we made an ABI-incompatible change in one of them. In that case we change the soname of *this one library*
to the next release version.

> So the only overhead is to check new releases for breaking changes

I promised to do that for future indigo releases.

**Comment by davetcoleman** [comment]
@v4hn think we can automate your ABI tests to be a Travis test that is "allowed_failure"?

**Comment by v4hn** [comment]
On Wed, Dec 21, 2016 at 10:21:43PM -0800, Dave Coleman wrote:
> @v4hn think we can automate your ABI tests to be a Travis test that is "allowed_failure"?

Hm, I did not consider "allowed_failure" before.
But even then we would need to build the whole moveit repo twice (with and without the new commits)
with full debugging symbols (-g -Og). But I suppose we would also want to build in release mode
once. Extraction of ABI dumps also takes quite a bit of time. So this would more-than-triple
the build time in Travis. Also, the checker has lots of false-positives (e.g. our recent changes
to move from `boost::shared_ptr<...>` to `...Ptr` produced an issue for each occurance...)

Overall, I would say this is too costly and annoying to integrate it in Travis. What do you say?
I'll prepare a script for this though, once I get around to do this (next year?).

**Comment by davetcoleman** [comment]
Yes, I didn't realize how costly it could be. If we had our own servers no problem, but Travis is quite limiting in that regard.

> But even then we would need to build the whole moveit repo twice (with and without the new commits)

Why not just compare to the currently released binaries for ABI breakage? I realize it would be slightly less useful because of recent commits could have triggered the ABI breakage, but once its broken, it doesn't really matter anyway

**Comment by v4hn** [comment]
So we might do that in some future with MoveIt-only CI servers, but not for now.

> Why not just compare to the currently released binaries for ABI breakage? I realize it would be slightly less useful because of recent commits could have triggered the ABI breakage, but once its broken, it doesn't really matter anyway

The "currently released binaries" do not work, because they were not compiled with full debugging symbols `gcc -g -Og`.
We could, indeed, cache the built binaries for the current head, but that wouldn't save a lot I believe.
If we would add that check in CI against the *latest released* version,
this would produce way too many false positives and would be more confusing than helpful in my opinion.

**Pull request merged**
