### PR TITLE
Auto format codebase using clang-format

### PR DESCRIPTION
**Pull request by davetcoleman**
This PR is to finalize discussion on the proposed auto-formatting of the code base discussed https://github.com/ros-planning/moveit/issues/242

After this is merged, Travis will then warn us when new code is added that violates the style guidelines: https://github.com/ros-planning/moveit_ci/pull/19

The changes in this PR are all achieved by the single command in the root of this repo:

```
find . -name '*.h' -or -name '*.hpp' -or -name '*.cpp' | xargs clang-format-3.6 -i -style=file
```

Using the formatting file defined in https://github.com/ros-planning/moveit/blob/kinetic-devel/.clang-format

### CODE REVIEW

**Comment by davetcoleman** [comment]
This PR is ready to merge now that kinetic has been released!

**Comment by v4hn** [comment]
Welcome to the new age of auto-formatted code :)

Shouldn't we apply similar changes to the other two branches to ease further cherry-picking?

**Comment by davetcoleman** [comment]
Yes, I will do that soon

**Comment by jonbinney** [comment]
So beautiful!!!

**Comment by davetcoleman** [comment]
I've applied the formatting to indigo/jade, see above

**Comment by davetcoleman** [comment]
...one step closer to robots programming robots.

**Pull request merged**
