### PR TITLE
Ensure consistency when overriding collision geometry with visual

### LINKED ISSUE #1907: rviz collision is inaccurate when robot visual is used to override collision
**Is your feature request related to a problem? Please describe.**
When there is no collision specified for a link, but there is a visual specified, the visual geometry is taken as the collision geometry (See for example #130).  However, in rviz, the collision for the link is not shown as there is no collision geometry for the object.  This can lead to hard to debug problems as collisions may not appear to be collisions in rviz.

**Describe the solution you'd like**
The RobotStateVisualization for rviz should also use the visual geometry as collision geometry when a link is empty.  I also think a warning should be issued when moveit overrides the collision geometry.

### PR DESCRIPTION
**Pull request by Dale-Koenig**
### Description

One approach to fix  #1907 
When visual geometry is specified for a link but not collision geometry, RobotModel overrides the collision geometry using the visual geometry when creating shapes.  This PR changes RobotModel to instead take ownership of it's own copy of the `urdf::ModelInterface`, and to modify it before generating the model.  This ensures that anything that touches the RobotModel in the future, such as the rviz display functionality, uses the same collision geometry.

I'm a bit hesitant to change the constructor for an important class like this so I'm open to other approaches.

Also, would this need special handling for when the visual array is empty?  I tested with a link that had a single visual element and it still had a non-empty Visual array, but it seems like the previous code had special handling for the case where the visual array is empty.

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by rhaschke** [comment]
This PR solves the issue only for MoveIt-related rviz plugins. The rviz-builtin RobotModel will not react to those changes. As explained in https://github.com/ros-planning/moveit/issues/130#issuecomment-589544315, I prefer a clear-cut solution, returning to the standard ROS behavior within a deprecation phase.

**Comment by Dale-Koenig** [comment]
> This PR solves the issue only for MoveIt-related rviz plugins. The rviz-builtin RobotModel will not react to those changes. As explained in [#130 (comment)](https://github.com/ros-planning/moveit/issues/130#issuecomment-589544315), I prefer a clear-cut solution, returning to the standard ROS behavior within a deprecation phase.

Fair enough.  I think it would still be best to have rviz as accurate as possible over the current situation, but as long as there is a scary enough error message it's probably not worth putting in partial measures.

**Comment by rhaschke** [comment]
Could you provide a corresponding PR to implement the suggested behavior in `RobotModel::constructLinkModel`?

**Comment by Dale-Koenig** [comment]
@shaschke It's not completely clear to me that there was a conclusion made in terms of how to handle this, or what that conclusion is.  By a parameter to disable the collision overriding, do you just mean an extra argument to the `RobotModel` constructor?

**Comment by rhaschke** [comment]
In #130, we didn't yet came up with a final conclusion. My suggestion was to use a new ROS parameter `moveit_populate_empty_collision_geometry`, that should be evaluated within `RobotModel`.

**Comment by Dale-Koenig** [comment]
@rhaschke I posted my opinion in the issue thread.  I'm happy to make a PR, but I think I will wait until a conclusion is made (or until it seems this has been forgotten about)

**Pull request closed without merging**
