### PR TITLE
remove meta-package moveit_full_pr2

### PR DESCRIPTION
**Pull request by rhaschke**
As explained in https://github.com/ros-planning/moveit/issues/1106#issuecomment-431831861, this meta-package induces a circular package dependency, which makes the Indigo pre-release test fail.

### CODE REVIEW

**Comment by 130s** [comment]
Thanks for taking a deep look @rhaschke 

I'm not sure if this change should be merged in by itself; the package was moved from somewhere in https://github.com/ros-planning/moveit/pull/422. I'm afraid removing this package from this repo would remove it in ROS distro land.

That's my quick thoughts. More thoughts needed though.

**Comment by rhaschke** [comment]
I agree, @130s. I think we should move this meta-package to the moveit_pr2 repo, where it belongs IMHO.
I prepared a corresponding PR: https://github.com/ros-planning/moveit_pr2/pull/98

**Comment by 130s** [comment]
https://github.com/ros-planning/moveit_pr2/pull/98 is merged so this PR should be almost ready except failing CIs. I restarted them.

https://travis-ci.org/ros-planning/moveit/jobs/444869605#L1685
```
:
cat build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="24" failures="24" disabled="0" errors="0" time="7.728" name="AllTests">
  <testsuite name="float_test/MeshFilterTestFloat" tests="12" failures="12" disabled="0" errors="0" time="3.896">
    <testcase name="float/0" value_param="0" status="run" time="0.35" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/1" value_param="0.5" status="run" time="0.323" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/2" value_param="1" status="run" time="0.337" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/3" value_param="1.5" status="run" time="0.321" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/4" value_param="2" status="run" time="0.322" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/5" value_param="2.5" status="run" time="0.312" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/6" value_param="3" status="run" time="0.331" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/7" value_param="3.5" status="run" time="0.314" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/8" value_param="4" status="run" time="0.326" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/9" value_param="4.5" status="run" time="0.318" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/10" value_param="5" status="run" time="0.313" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
    <testcase name="float/11" value_param="5.5" status="run" time="0.327" classname="float_test/MeshFilterTestFloat">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 0&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 1" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 0
Expected: filtered_depth[idx]
Which is: 1]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="ushort_test/MeshFilterTestUnsignedShort" tests="12" failures="12" disabled="0" errors="0" time="3.832">
    <testcase name="unsigned_short/0" value_param="0" status="run" time="0.33" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/1" value_param="0.5" status="run" time="0.31" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/2" value_param="1" status="run" time="0.323" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/3" value_param="1.5" status="run" time="0.313" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/4" value_param="2" status="run" time="0.341" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/5" value_param="2.5" status="run" time="0.316" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/6" value_param="3" status="run" time="0.317" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/7" value_param="3.5" status="run" time="0.312" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/8" value_param="4" status="run" time="0.337" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/9" value_param="4.5" status="run" time="0.314" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/10" value_param="5" status="run" time="0.314" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
    <testcase name="unsigned_short/11" value_param="5.5" status="run" time="0.305" classname="ushort_test/MeshFilterTestUnsignedShort">
      <failure message="Value of: gt_depth[idx]&#x0A;  Actual: 3.9430001&#x0A;Expected: filtered_depth[idx]&#x0A;Which is: 0" type=""><![CDATA[/root/ws_moveit/src/moveit/moveit_ros/perception/mesh_filter/test/mesh_filter_test.cpp:234
Value of: gt_depth[idx]
  Actual: 3.9430001
Expected: filtered_depth[idx]
Which is: 0]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

https://travis-ci.org/ros-planning/moveit/jobs/444869606#L1861
```
:
catkin_test_results
build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 24 tests, 0 errors, 24 failures, 0 skipped
Summary: 117 tests, 0 errors, 24 failures, 0 skipped
```

**Comment by 130s** [comment]
CI failed again. I do see pr2 stuff is missing, but I can't tell at a glance that this is due to PR2 change. Would be great if anyone else can chime in.

https://travis-ci.org/ros-planning/moveit/jobs/444869605#L1416
```
:
catkin build --catkin-make-args run_tests -- --no-status --summarize --no-deps moveit moveit_commander moveit_core moveit_controller_manager_example moveit_experimental chomp_motion_planner moveit_full moveit_planners moveit_planners_chomp moveit_plugins moveit_ros moveit_ros_perception moveit_ros_planning moveit_fake_controller_manager moveit_kinematics moveit_planners_ompl moveit_ros_move_group moveit_ros_manipulation moveit_ros_robot_interaction moveit_ros_warehouse moveit_ros_benchmarks moveit_ros_planning_interface moveit_ros_visualization moveit_ros_benchmarks_gui moveit_runtime moveit_setup_assistant moveit_simple_controller_manager moveit_ros_control_interface
:
Warning: Failed to add group 'left_arm_joints'
         at line 509 in /root/ws_moveit/src/moveit/moveit_core/robot_model/src/robot_model.cpp
Error:   Group 'left_arm_base_tip' not found in model 'pr2'
         at line 474 in /root/ws_moveit/src/moveit/moveit_core/robot_model/src/robot_model.cpp
Error:   Group 'left_arm_joints' not found in model 'pr2'
:
Error:   Joint '' not found in model 'pr2'
:
Error:   Link '' not found in model 'pr2'
         at line 1115 in /root/ws_moveit/src/moveit/moveit_core/robot_model/src/robot_model.cpp
:
Error:   Link '' not found in model 'pr2'
:
Error:   Joint 'no_joint' not found in model 'pr2'
         at line 1086 in /root/ws_moveit/src/moveit/moveit_core/robot_model/src/robot_model.cpp
[ERROR] [1540315572.504094355]: IK solver computes joint values for joint 'l_shoulder_pan_joint' but group 'base' does not contain such a joint.
[ERROR] [1540315572.660640576]: Joint '' not found in model 'pr2'
[ERROR] [1540315572.660964618]: The constraints for joint 'r_shoulder_pan_joint' are such that there are no possible values for the joint: min_bound: 0.53, max_bound: 0.43. Failing.
[ERROR] [1540315572.661107778]: The constraints for joint 'r_shoulder_pan_joint' are such that there are no possible values for the joint: min_bound: 0.53, max_bound: 0.43. Failing.
[ERROR] [1540315572.714683532]: IK solver computes joint values for joint 'l_shoulder_pan_joint' but group 'base' does not contain such a joint.
[ERROR] [1540315572.869077742]: Group 'l_arm' not found in model 'pr2'
:
build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 24 tests, 0 errors, 24 failures, 0 skipped
Summary: 117 tests, 0 errors, 24 failures, 0 skipped
moveit/moveit:indigo-ci container finished with errors
```

**Comment by rhaschke** [comment]
@130s As already mentioned in https://github.com/ros-planning/moveit/issues/1106#issuecomment-431702426, the failing Travis builds are related to the `mest_filter_test` in `moveit_ros_perception`. In Kinetic / Melodic we disabled this test, because its related to an upstream issue in OpenGL (see #1109).
```
catkin_test_results
build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 24 tests, 0 errors, 24 failures, 0 skipped
Summary: 117 tests, 0 errors, 24 failures, 0 skipped
```
On the build farm the test will be ignored anyway, because the test requires an X11 display.

The errors you have listed are simply outputs from the unittests, which are OK.

**Pull request merged**
