### PR TITLE
Travis: add clang build

### PR DESCRIPTION
**Pull request by rhaschke**
In addition to #1233, also make Travis to build once with clang.

### CODE REVIEW

**Comment by v4hn** [comment]
> fatal: Remote branch clang-build not found in upstream origin

what?

**Comment by rhaschke** [comment]
> fatal: Remote branch clang-build not found in upstream origin

I accidentally push my branch to ros-planning, which triggered a Travis build. Then I removed the branch again before Travis actually started to build and this results in the mentioned error. Not a big issue ;-)

**Comment by v4hn** [comment]
>  Could not find compiler set in environment variable CC:
>  clang.

I guess it should have succeeded with your second patch, but this seems to be the output of CI for this commit.

**Comment by rhaschke** [comment]
It can only succeed if the 2nd commit has been merged and dockerhub has rebuild the corresponding docker image (including clang). So, either we reverse the commit order and wait for these steps to be completed or we just trust, that it will work out as in melodic - and fix any issues later if not.

**Comment by v4hn** [comment]
I will leave this choice to @davetcoleman , as I am currently still not familiar enough with our CI system.

**Comment by v4hn** [comment]
@rhaschke reverted this again right after merge in https://github.com/ros-planning/moveit/commit/12129304860190302aea9bfd68b4d0f864e496b7 because of ABI problems with boost, see
https://travis-ci.org/ros-planning/moveit/jobs/464316478#L3205 .

**Pull request merged**
