### PR TITLE
[readme] Add geometric_shapes, random_numbers, srdfdom labels.

### PR DESCRIPTION
**Pull request by 130s**
All repositories/packages in `ros-planning` github org that are depended on by any package in the main `moveit` repo deserve to be listed IMO.

### CODE REVIEW

**Comment by mikeferguson** [comment]
I haven't reviewed the formatting, but +1 to the idea

**Comment by v4hn** [comment]
picked to i/j.

Good idea @130s

**Comment by davetcoleman** [comment]
why did you put geometric_shapes at the top but the other two repos at the bottom? i would have preferred all at the bottom since they aren't main moveit repos but "helpers"

**Comment by v4hn** [comment]
On Fri, Aug 26, 2016 at 10:46:13AM -0700, Dave Coleman wrote:
> why did you put geometric_shapes at the top but the other two repos at the bottom? i would have preferred all at the bottom since they aren't main moveit repos but "helpers"

Alphabetical order. I thought it's fine.
If you would prefer all three of them below, just file another request.
I'm fine with it either way...

**Comment by 130s** [comment]
Yeah, alphabetical. But I noticed later that I forgot to sort `moveit*` packages. Either way is fine for me too but I know think separation of `moveit` repo and others might be clearer.

**Comment by davetcoleman** [comment]
I'm particular about my pretty table ;-)

**Pull request merged**
