### PR TITLE
[maint] clang-format-10

### PR DESCRIPTION
**Pull request by tylerjw**
This is a rebase of #2177 which itself was based on #2169 

clang-format-10 is available via apt on ubuntu 18.04 and 20.04.  it is also possible to install on 16.04 using the instructions from the clang project itself.  This is blocking work on moveit2.  Please consider this quickly so we can get it done before it needs another rebase.

Co-authored-by: Robert Haschke <rhaschke@techfak.uni-bielefeld.de>
Co-authored-by: Henning Kayser <henningkayser@picknik.ai>

### CODE REVIEW

**Comment by tylerjw** [comment]
This is failing CI because moveit_ci doesn't use clang-format-10.  I'll make a PR to fix that.

**Comment by henningkayser** [comment]
> This is failing CI because moveit_ci doesn't use clang-format-10. I'll make a PR to fix that.

Just wanted to mention that. I think we should also keep legacy support for clang-format-3.9 to not break too many setups at once.

**Comment by rhaschke** [comment]
I don't like that you squashed the 4 commits of #2177 / #2169 into a single commit. I think, adapting and applying the config should be two separate commits.

**Comment by rhaschke** [comment]
Continuing with #2177.

**Pull request closed without merging**
