### PR TITLE
[indigo-devel] Modify ikfast_template for getPositionIK single solution results (#537) from kinetic-devel

### PR DESCRIPTION
**Pull request by 130s**
#537

### CODE REVIEW

**Comment by v4hn** [comment]
Due to #586 the template is broken in indigo at the moment.
Until this is fixed I would like to refrain from further patches.

**Comment by v4hn** [comment]
This needs to be tested now that ikfast generation works on indigo again.
Adding WMD label.

**Comment by henningkayser** [comment]
@130s, @v4hn can we close this PR?

**Comment by davetcoleman** [comment]
This is just a cherry-pick of a kinetic fix into indigo. I don't think we should be changing indigo behavior at this point, and this PR is clearly stale. Closing.

**Pull request closed without merging**
