### PR TITLE
Use MOVEIT_CLASS_FORWARD for moveit classes in moveit_ros.

### PR DESCRIPTION
**Pull request by de-vri-es**
More `MOVEIT_CLASS_FORWARD`, this time for `moveit_ros/*`.

### CODE REVIEW

**Comment by davetcoleman** [comment]
LGTM, but needs to be rebased

**Comment by de-vri-es** [comment]
Oops, forgot to update =]

**Comment by davetcoleman** [comment]
+1, I don't see any potential ABI breakages

**Comment by davetcoleman** [comment]
cherry-picked to Jade, Indigo had a conflict in move_group.h so i fixed and created a PR

https://github.com/ros-planning/moveit/pull/183

**Pull request merged**
