### PR TITLE
protect RobotState in RobotStateDisplay with mutex

### PR DESCRIPTION
**Pull request by simonschmeisser**
### Description

Currently the `RobotStateDisplay` is not thread-safe and a new incoming message updating the `robot_state_` while it's updated for rendering can cause a crash

### CODE REVIEW

**Review by JafarAbdi — COMMENTED** [review]
What do you think about using [LockedRobotState](https://github.com/ros-planning/moveit/blob/master/moveit_ros/robot_interaction/include/moveit/robot_interaction/locked_robot_state.h) from robot interaction? looks like it's suited for this use case

**Comment by simonschmeisser** [comment]
Actually got it to work but I'm not quite convinced this is nicer than the plain old mutex ... if it shall be this variant, please squash on merge

**Comment by simonschmeisser** [comment]
friendly ping @JafarAbdi

**Comment by rhaschke** [comment]
> Currently the `RobotStateDisplay` is not thread-safe and a new incoming message updating the `robot_state_` while it's updated for rendering can cause a crash

Actually, I cannot confirm this statement. RobotStateDisplay is served by the default, global message queue, which in turn is processed synchronously within rviz' main update loop. Thus, it's not possible that messages are incoming while they are processed.
I guess your are not using standard rviz, but your own version, serving the global message queue from several threads/spinners? I remember that we discussed this issue over in rviz a while ago...

**Comment by simonschmeisser** [comment]
That's right, I use rviz as a library with AsyncSpinner (as does `rqt_rviz` afaik) in my application.

**Comment by rhaschke** [comment]
Closing as too specific for your use case.

**Pull request closed without merging**
