### PR TITLE
Enable higher number of self-collision checking samples

### PR DESCRIPTION
**Pull request by salihmarangoz**
### Description

This PR solves #3526

- Replaced QLabel showing the number of samples with QSpinbox. Sampling spinbox and slider are connected to each other. Slider works in range (1.000-100.000), Spinbox works in range (1.000-100.000.000). Values are always rounded in 1000s. User can set high number of samples using Spinbox which may also increase the waiting time.
- Refactored the code to use the number of samples instead of density in the range 0-100.
- Added an interrupt button if the collision generation takes a long time for the user.
- Increased the progress bar update period from 5% to 1% but that caused Floating Point Exception somewhere in the code, so reverted the changes.

Default:
default

Number of samples set to maximum using the spinbox and generating:
computing

Clicked on the interrupt button:
interrupt

Experimented on [a two-arm robot configuration](https://github.com/RePAIRProject/repair_ros_robot) with different number of samples. I think setting the upper limit to 100.000.000 makes sense because setting to 10.000.000 doesn't create the same solution every time.

```
100.000:
[ INFO] [1699975705.184316444]:     33 : Total Links
[ INFO] [1699975705.184333485]:    528 : Total possible collisions
[ INFO] [1699975705.184345498]:      0 : Always in collision
[ INFO] [1699975705.184357999]:    317 : Never in collision
[ INFO] [1699975705.184368336]:     19 : Default in collision
[ INFO] [1699975705.184379440]:     28 : Adjacent links disabled
[ INFO] [1699975705.184390406]:    164 : Sometimes in collision
[ INFO] [1699975705.184399764]:    364 : TOTAL DISABLED

500.000:
[ INFO] [1699975740.059887924]:     33 : Total Links
[ INFO] [1699975740.059903708]:    528 : Total possible collisions
[ INFO] [1699975740.059915581]:      0 : Always in collision
[ INFO] [1699975740.059926686]:    316 : Never in collision
[ INFO] [1699975740.059938000]:     19 : Default in collision
[ INFO] [1699975740.059947987]:     28 : Adjacent links disabled
[ INFO] [1699975740.059958603]:    165 : Sometimes in collision
[ INFO] [1699975740.059968939]:    363 : TOTAL DISABLED

1.000.000:
[ INFO] [1699975767.495380743]:     33 : Total Links
[ INFO] [1699975767.495407213]:    528 : Total possible collisions
[ INFO] [1699975767.495424534]:      0 : Always in collision
[ INFO] [1699975767.495441994]:    313 : Never in collision
[ INFO] [1699975767.495458826]:     19 : Default in collision
[ INFO] [1699975767.495473981]:     28 : Adjacent links disabled
[ INFO] [1699975767.495490254]:    168 : Sometimes in collision
[ INFO] [1699975767.495505480]:    360 : TOTAL DISABLED

5.000.000:
[ INFO] [1699975834.433148867]:     33 : Total Links
[ INFO] [1699975834.433171705]:    528 : Total possible collisions
[ INFO] [1699975834.433191470]:      0 : Always in collision
[ INFO] [1699975834.433208023]:    306 : Never in collision
[ INFO] [1699975834.433223877]:     19 : Default in collision
[ INFO] [1699975834.433239381]:     28 : Adjacent links disabled
[ INFO] [1699975834.433256073]:    175 : Sometimes in collision
[ INFO] [1699975834.433269902]:    353 : TOTAL DISABLED

10.000.000:
[ INFO] [1699976001.606243521]:     33 : Total Links
[ INFO] [1699976001.606260982]:    528 : Total possible collisions
[ INFO] [1699976001.606272086]:      0 : Always in collision
[ INFO] [1699976001.606282074]:    304 : Never in collision
[ INFO] [1699976001.606292061]:     19 : Default in collision
[ INFO] [1699976001.606302118]:     28 : Adjacent links disabled
[ INFO] [1699976001.606311686]:    177 : Sometimes in collision
[ INFO] [1699976001.606322023]:    351 : TOTAL DISABLED

50.000.000:
[ INFO] [1699976373.608263528]:     33 : Total Links
[ INFO] [1699976373.608278754]:    528 : Total possible collisions
[ INFO] [1699976373.608292582]:      0 : Always in collision
[ INFO] [1699976373.608314512]:    304 : Never in collision
[ INFO] [1699976373.608330436]:     19 : Default in collision
[ INFO] [1699976373.608346918]:     28 : Adjacent links disabled
[ INFO] [1699976373.608363541]:    177 : Sometimes in collision
[ INFO] [1699976373.608380023]:    351 : TOTAL DISABLED

100.000.000:
[ INFO] [1699977117.672622957]:     33 : Total Links
[ INFO] [1699977117.672644818]:    528 : Total possible collisions
[ INFO] [1699977117.672664443]:      0 : Always in collision
[ INFO] [1699977117.672683579]:    304 : Never in collision
[ INFO] [1699977117.672695452]:     19 : Default in collision
[ INFO] [1699977117.672706347]:     28 : Adjacent links disabled
[ INFO] [1699977117.672715986]:    177 : Sometimes in collision
[ INFO] [1699977117.672724925]:    351 : TOTAL DISABLED
```

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
When the slider and spinbox widgets don't express a density anymore, but the number of samples, I suggest renaming the widget variables correspondingly - for consistency.
I also committed several minor fixes.

**Comment by salihmarangoz** [comment]
I have updated the variable names and comments for consistency. I also noticed that progress bar does not disappear after finishing/interrupting the process. Is this another feature? :)

**Comment by rhaschke** [comment]
> I also noticed that progress bar does not disappear after finishing/interrupting the process. Is this a feature?

Yes, I think the user might be interested where the process stopped.

**Review by rhaschke — APPROVED** [review]
Looks good to me now.

**Comment by salihmarangoz** [comment]
Looks good to me too. Can you merge this PR?

**Comment by rhaschke** [comment]
We have a policy that two maintainers need to review a PR. Give them at least the chance to do so.

**Comment by salihmarangoz** [comment]
> We have a policy that two maintainers need to review a PR. Give them at least the chance to do so.

Sorry, I just saw the new "awaits 2nd review" tag and deleted my comment.

**Review by v4hn — APPROVED** [review]
I was a bit surprised to see that interrupting the computation will not yield "partial" results in the matrix, but I think this is good enough as is.

@salihmarangoz thanks for the patch. If you feel like implementing the optimization to find potential collisions in narrow joint ranges, please go ahead. I agree that it would be feasible and nice to have! It's just that random sampling mostly gets the job done and a human should look through the entries anyway...

**Pull request merged**
