### PR TITLE
Add support for the Arctic gamepad

### PR DESCRIPTION
**Pull request by galou**
### Description

Add support for the arctic gamepad in `moveitjoy_module.py`, and, indirectly in `moveit_ros_visualization::moveit_joy.py`.

Arctic gamepad: https://www.arctic.ac/eu_en/usb-wireless-gamepad.html.

I'm ready to add the support for this gamepad somewhere if someone can point me where.

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code), **didn't touch much**
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Include a screenshot if changing a GUI, **no change in any GUI**
- [x] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html), **not necessary**
- [x] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic), **can be cherry picked, very local changes**

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by v4hn** [comment]
Thank you for the contribution @galou 👍

**Comment by davetcoleman** [comment]
Sweet!

**Comment by davetcoleman** [comment]
Can you update http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ros_visualization/joystick.html also please?

**Comment by galou** [comment]
Updated the documentation at https://github.com/ros-planning/moveit_tutorials/pull/143.

**Pull request merged**
