### PR TITLE
Fix #2811

### LINKED ISSUE #2811: ompl_interface::ConstrainedGoalSampler::sampleUsingConstraintSampler doesn't appear to sample?
Hello,

I was working on trying to implement a custom `constraint_samplers::ConstraintSampler`, but I noticed that only the `project` method gets called, never the `sample` method.

The state I get as input always appears to be the same (I think it's the same as the starting state?) when I print it out.

When reading through https://github.com/ros-planning/moveit/blob/master/moveit_planners/ompl/ompl_interface/src/detail/constrained_goal_sampler.cpp#L90, I also don't really see any source of randomness in there... it appears to just be projecting the same state over and over.

Is this the intended behavior?

### PR DESCRIPTION
**Pull request by werner291**
This is a PR for #2811

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by felixvd — APPROVED** [review]
This looks a lot clearer to me, and `project` should really not do the same thing as `sample`, but I never touch this code so I am just adding this as a vote of support.

**Comment by v4hn** [comment]
Our tests like it and this fixes quite a crucial aspect of method semantics. I'll just take your approval as a +1 @felixvd and merge. :cat2: 

Thanks for the effort @werner291 !

**Comment by rhaschke** [comment]
Please use more informative PR descriptions, e.g. here: `ConstrainedGoalSampler: actually sample()`
The description usually becomes the final commit message.

**Comment by v4hn** [comment]
My bad, I should have adjusted the commit message of course.

**Pull request merged**
