### PR TITLE
clang-format cleanup with version 3.9

### PR DESCRIPTION
**Pull request by v4hn**
This found a number of formatting issues that where not detected by clang-format 3.6.

Let's see whether they are compatible with our 3.6 test.

### CODE REVIEW

**Comment by rbbg** [comment]
Not working huh? This is the reason #338 failed as well :)

**Comment by v4hn** [comment]
Yeah, let's see. Dave imposed clang-format 3.6, but not many linux distributions provide outdated versions of the tool.

**Comment by v4hn** [comment]
ok, I yield. 3.6 wants to undo most of the changes in this commit. closing.

**Comment by davetcoleman** [comment]
I'd be fine switching to whatever clang-format 3.8 does - it is the [default in Ubuntu 16.04](https://launchpad.net/ubuntu/xenial/+package/clang-format-3.8). We need to change the Travis test to either install [3.8 from a PPA](http://askubuntu.com/questions/735201/installing-clang-3-8-on-ubuntu-14-04-3) or use a 16.04 Docker image. The PPA would probably be easiest.

We'd also have to ask our 14.04 users to either 1) manually fix their formatting errors 2) use the PPA or 3) install from source clang-format. I'm okay with that since everyone should be migrating to 16.04 LTS

**Comment by v4hn** [comment]
As pointed out 3.8 is outdated already, and I don't see any indication that the llvm folks want to guarantee compatibility. This is a race against a stable-release-incompatible software-release system at their end in my opinion.

> install from source clang-format

This involves building entire llvm as I wrote [here](https://github.com/ros-planning/moveit/pull/332#issuecomment-259978143).

I vote for staying with 3.6 until indigo eol.

**Comment by rbbg** [comment]
Although I agree that it's probably best to keep using clang-format-3.6 for 14.04/Indigo, I would like to point out that clang-format-3.8 is the latest version available in the `trusty-updates` repository. I didn't read the documentation so when installing clang-format I mistakenly installed the latest version causing my PR to fail.

**Comment by davetcoleman** [comment]
@rbbg huh, I hadn't seen that 3.8 is available in trusty (14.04). I don't think there is a "default" though

**Comment by davetcoleman** [comment]
New fix for this issue: https://github.com/ros-planning/moveit/pull/367

**Pull request closed without merging**
