### PR TITLE
fix exported plugin xml for collision_distance_field

### PR DESCRIPTION
**Pull request by v4hn**
Otherwise the xml can not be found on an installed workspace

### CODE REVIEW

**Comment by v4hn** [comment]
should be picked to j/k

**Comment by davetcoleman** [comment]
I don't understand why having the ``install`` command in a subdirectory causes a problem. Don't the CMakeLists behave the same when you use `` add_subdirectory(collision_distance_field)`` ?

**Comment by v4hn** [comment]
The problem is not the install rule in the subfolder, but the install location of the xml file.

It should have the same relative path in the source folder of the package and in the installed share-folder, because only one relative path can be specified in the `package.xml` and the file has to be available in devel and install workspaces.
I didn't want to create `<install-ws>/share/moveit_experimental/collision_distance_field`, so instead I moved the file one level higher in the packages source folder.

**Comment by davetcoleman** [comment]
picked to j/k

**Pull request merged**
