### PR TITLE
Check errors when loading scene geometry from files

### PR DESCRIPTION
**Pull request by jonbinney**
### Description

Before this PR, there was no error checking when loading planning scene geometry from a text file. This meant the caller couldn't tell whether the planning scene had been successfully loaded.

Not sure if this should be cherry-picked. It changes the return type of two PlanningScene member functions, so I think it would require people to re-compile their code.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [x] Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Decide if this should be cherry-picked to other current ROS branches
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by felixvd** [comment]
I like helpful error messages, so I like this. Is there anything to update in the visualization tab?

**Comment by jonbinney** [comment]
@felixvd do you mean for the rviz plugin? I hadn't looked at that - I was actually using this function directly from a non-gui program.

**Comment by jonbinney** [comment]
@bmagyar good point - I'll add a couple unit tests..

**Comment by jonbinney** [comment]
@bmagyar I've added a couple tests. Not exhaustive by any means, but should do a decent job of sanity checking the code.

**Comment by rhaschke** [comment]
I changed usages of the method in existing MoveIt! code to consider the return value.

**Comment by jonbinney** [comment]
@rhaschke thanks for updating the rviz plugin to use this! Switching to exceptions seems like a bigger change - other functions in `PlanningScene` like `processAttachedCollisionObjectMsg` use a return value (bool) to indicate success/failure and I figured it would be best to keep things similar.

**Comment by jonbinney** [comment]
(if you do want exceptions here though, let me know and I'm happy to update the PR)

**Pull request merged**
