### PR TITLE
Add tf dependency to package.xml

### PR DESCRIPTION
**Pull request by clalancette**
### Description

[chomp_optimizer_adapter.cpp](https://github.com/ros-planning/moveit/blob/melodic-devel/moveit_ros/planning/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp#L51) still requires tf, and will not compile on the build farm without it.

Here's a link to a failing binary build: http://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__moveit_ros_planning__ubuntu_bionic_amd64__binary/20/consoleFull

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Document API changes relevant to the user in the moveit/MIGRATION.md notes
- [ ] Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Decide if this should be cherry-picked to other current ROS branches
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by 130s** [comment]
Thanks for the patch. I do see [the error on the buildfarm](http://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__moveit_ros_planning__ubuntu_bionic_amd64__binary/20/consoleFull).
```
06:43:59 /tmp/binarydeb/ros-melodic-moveit-ros-planning-0.10.3/planning_request_adapter_plugins/src/chomp_optimizer_adapter.cpp:51:10: fatal error: tf/transform_listener.h: No such file or directory
06:43:59  #include <tf/transform_listener.h>
06:43:59           ^~~~~~~~~~~~~~~~~~~~~~~~~
06:43:59 compilation terminated.
```

(To me the question is the PRtest didn't capture this sort of issues..
@rhaschke was able to have pre-release test pass https://github.com/ros-planning/moveit/issues/1083#issuecomment-433647868 so did I.)

**Comment by rhaschke** [comment]
Also the dev-builds on the build farm succeed. The reason for the failure is, that the deb builds are building one package after the other. Hence one package cannot profit from another one pulling in dependencies..

@clalancette While this is an acceptable hotfix, I would prefer to finalize the transition to tf2. I will have a short look...

**Comment by IanTheEngineer** [comment]
I agree that this is a fine hotfix, but we should be independent of `tf1` at this point in the `melodic-devel` branch. That in of itself is a bug.

**Comment by rhaschke** [comment]
That was easy: #1170. Hope, Travis and build-farm don't complain anymore ;-)

**Comment by rhaschke** [comment]
Closing in favour of #1170.

**Pull request closed without merging**
