### PR TITLE
Add and remove packages based on changes in moveit

### PR DESCRIPTION
**Pull request by davetcoleman**
Change Kinetic status

### CODE REVIEW

**Comment by rhaschke** [comment]
Why do you want to remove the entry for `benchmarks_gui` for < Kinetic?

**Comment by davetcoleman** [comment]
1) I was being lazy and just removed the whole line
2) the package barely worked and was not really advertised, as per this message @isucan and I added many years ago: https://github.com/ros-planning/moveit/blob/jade-devel/moveit_ros/benchmarks_gui/src/main_window.cpp#L62
3) I'm only editing the README of the kinetic-devel branch, and it doesn't exist there.

**Comment by davetcoleman** [comment]
fyi we're still getting this flaky test:

```
Warnings << moveit_ros_planning_interface:make /root/ws_moveit/logs/moveit_ros_planning_interface/build.make.002.log
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/__init__.py", line 274, in rostestmain
    _main()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain
    results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file
    raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))
IOError: cannot create test results directory [/root/ws_moveit/build/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface]. Please check permissions.
```

I've just retriggered the build

**Comment by davetcoleman** [comment]
ping

**Pull request merged**
