### PR TITLE
Replace panda_moveit_config with moveit_resources

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

@v4hn @rhaschke Here is a simple change to change to use moveit_resources for now until we have a fancier solution.

### CODE REVIEW

**Comment by v4hn** [comment]
I guess he is talking about https://github.com/ros-planning/moveit/pull/2019 :+1:
@tylerjw CI did not report back, but [failed in the subframe test](https://travis-ci.org/github/ros-planning/moveit/jobs/673056290). Could you have a look please?

**Comment by tylerjw** [comment]
panda_collision

This is the problem.  The panda model in the moveit_resources has the gripper closed and that is in collision with the cylinder.

**Comment by tylerjw** [comment]
It is more complicated that what I posted above because where it fails is not about a collision, it has to do with something going wrong between adding the collision object in the planning scene interface and then asking to plan from a subframe of that object.  There is something different about the launchfiles between the other repo panda_moveit_config and the moveit_resources one.

**Comment by tylerjw** [comment]
I can't find it documented anywhere but what is the plan for keeping the different copies of panda_moveit_config in sync?  Should I make a PR to copy the latest changes to the other repo into the moveit_resources version of it?

@v4hn @rhaschke

**Comment by tylerjw** [comment]
Sorry, didn't mean to close this.

**Comment by rhaschke** [comment]
Yes, we need to manually sync required changes from panda_moveit_config.
Last time I did this was mid February (https://github.com/ros-planning/moveit_resources/commit/ad32e7ebcd7895f029bd6d6d9b75f082954fd1b5).
Probably, you are missing the `ResolveSubFrames` capability?

**Comment by v4hn** [comment]
> Probably, you are missing the `ResolveSubFrames` capability?

What would that be?

**Comment by rhaschke** [comment]
> > Probably, you are missing the `ResolveSubFrames` capability?
> 
> What would that be?

Sorry, the name is `ResolveConstraintFrames`.

**Comment by tylerjw** [comment]
Here is a new PR to do that again: https://github.com/ros-planning/moveit_resources/pull/29

**Comment by v4hn** [comment]
@tylerjw can you rebase this and trigger CI again?
Our tests should all depend on moveit_resources anyway, so this makes sense to merge.

**Comment by tylerjw** [comment]
@v4hn the subframes test still doesn't work with moveit_resources and I can't figure out why.  I created a new PR with just the other change (so it'll be easy to backport too).

**Comment by v4hn** [comment]
Closing. This is deprecated and touched again by #2199 .

**Pull request closed without merging**
