### PR TITLE
WIP: Add colours to trajectory_visualisation display

### PR DESCRIPTION
**Pull request by bmagyar**
### Description

I needed a way to overlay trajectory displays in an easy to distinguish way so I've added colouring to the trajectory_visualisation display. 

A video can be found here: 
https://www.youtube.com/watch?v=Vj0KNAOtFrw

screenshot_2016-11-15_16-21-48

**Please note that this is a PR to discover interest for this feature.**
Code is probably very dirty and doesn't meet any of the merging requirements, I haven't even rebased it on the current codebase yet, it's a few weeks old. **If I get a few thumbs up, I'd gladly tidy things up to be merged!**

PS: I love this checklist :+1: 

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1 to proceeding - I've run into this limitation before and the only current way to differentiate a trajectory is by the transparency level

can you share a screenshot of the updated display properties also?

**Comment by bmagyar** [comment]
screenshot_2016-11-15_16-27-49

I've added a boolean property to disable this functionality, this could be off by default.

**Comment by bmagyar** [comment]
Also I'd only colour the actual moving parts of the robot, I can add that too.

**Comment by davetcoleman** [comment]
I'd suggest the wording "Color Enabled" to match how the RobotState display words "Visual Enabled" and "Collision Enabled"

**Comment by v4hn** [comment]
I like the idea, please proceed!
This is nice to have :-)

**Comment by bmagyar** [comment]
I ran clang-format, but discovered some inconsistencies around pointers and references.

I'd personally prefer the .h version everywhere.

Change it did in .h:
void setRobotColor(rviz::Robot* robot, const QColor& color);

Change it did in .cpp:
void TrajectoryVisualization::setRobotColor(rviz::Robot *robot, const QColor &color)

**Comment by davetcoleman** [comment]
clang-format: I hadn't realized that discrepancy. Feel free to investigate and propose a fix to https://github.com/ros-planning/moveit/blob/kinetic-devel/.clang-format

**Comment by bmagyar** [comment]
Thanks!

I'll change that clang format back by hand first, then investigate.

I'd also like to tweak the behaviour a bit first, now when the .rviz config
is saved with colours on they don't active when loaded. I need to fiddle a
bit there. I'll attempt getting it all done on Friday.

**Comment by bmagyar** [comment]
My last commit fixed the issue with saved rviz configuration of the tickbox & moved those &-s and *-s where they should be.

All green from me :+1:

**Comment by davetcoleman** [comment]
We should not try to override the clang-format default, otherwise all Travis tests will fail in the future. Rather, I have investigated your observation about clang-format and made a upstream fix here: https://github.com/ros-planning/moveit/pull/367

Until then you should do what clang-format suggests so we can merge this

**Comment by bmagyar** [comment]
Right! Actually my hand-fixed stuff is not failing but some of the new
piece of code I touched while adding the final bits. Pushed update.

**Comment by davetcoleman** [comment]
I've confirmed this PR works in my system - having the colored trajectory is great thanks!

**Comment by davetcoleman** [comment]
Please open PRs for Jade and Indigo if you'd like this backported

**Comment by bmagyar** [comment]
Directly to the branches of this repo, right?

**Comment by davetcoleman** [comment]
Yes - create a branch in your fork for i.e. jade and open a pull request to jade-devel in this repo

**Pull request merged**
