### PR TITLE
Removed the unnecessary null pointer checks. Solved issue # 1389

### PR DESCRIPTION
**Pull request by Mahmoud-Selim**
Removed the unnecessary null pointer checks. Addresses issue #1389.

### CODE REVIEW

**Comment by Mahmoud-Selim** [comment]
@rhaschke it says to use "find . -name '*.h' -or -name '*.hpp' -or -name '*.cpp' | xargs clang-format-3.9 -i -style=file" as the "TEST="clang-format catkin_lint" build failed. is there is something that i should do ?
Thanks,

**Comment by rhaschke** [comment]
Yes, please run the suggested clang-format command on the source tree.

**Comment by rhaschke** [comment]
Looks like you used the wrong clang-format version. We required clang-format-3.9.
Also, please don't use merge commits to sync your PR with master. Instead, you should always rebase onto master (if necessary at all).

**Comment by Mahmoud-Selim** [comment]
@rhaschke so should i file another PR for this ? thanks for you patience.

**Comment by rhaschke** [comment]
@Mahmoud-Selim, yes, please 
- cherry-pick your original commit 2bfa721ecc15a05fb115e531750202d2012a8369 onto master
- apply the correct clang-format and amend-commit the change
- (force) push the new branch HEAD to this PR (or open a new one instead)

**Comment by rhaschke** [comment]
Superseeded by #1410

**Pull request closed without merging**
