### PR TITLE
Melodic backports

### PR DESCRIPTION
**Pull request by rhaschke**
Current melodic-devel is [broken on Travis](https://travis-ci.com/github/ros-planning/moveit/builds/174775901), because of the missing cherry-pick e894d3892ba220746c3f4dca183ff655ba9e3d32.
Thus, I decided to cherry-pick all recent changes on master (up to 88712bb7f5ab2c4153440c5c55f915798ca83dd3). Here is the full list of PRs that I considered (critical ones are bold-face):

- #2193: Fix segfault in PSM::clearOctomap()
- #2194: use moveit_resources for testing
- #2207: Remove urdf package as build_depend from package.xml
- #2180: Various fixes for upcoming Noetic release (only parts, ignored commits are crossed out):
  - a617923cb7adc499aa7c2863ac0ddf597c431f9a Prefer vendor-specific OpenGL library
  - e894d3892ba220746c3f4dca183ff655ba9e3d32 **Further increase acceptance threshold for mesh-filter test**
  - ~~93cdeabf2c774d1a8066a3736e47ebdc68ec11c7 use SYSTEM includes to suppress external warnings~~
  - ~~a8ee3cb11433716baaf9bc23d8aa2a64d799d5c0 Fix warnings~~
  - ~~7c0d067fef49498812947df5e2308691fc05dfb4 Travis: Enable Noetic build~~
  - ~~9dd66f905c93b8c5ca86d6d4df531bfb66495973 Remove moveit_noetic.rosinstall~~
- #2198: Allow adding planning scene shapes from rviz panel
- #2215: Fix docstrings in robot_state.h
- #2221: Travis: Update dist to Bionic
- #2201: Exposed missing parameters from the MoveGroup Python interface
- #2229: Optimize includes
- #2232: Remove unused yaml param
- #2204: Check collisions during joint motions, too
- #2239: Fix memcpy bug in copyJointToOMPLState in ompl interface
- #2242: Add planning_adapters for chomp in setup assistant
- #2177: **Migration to clang-format-10**
- #2246: A ROS service to reset the Servo status
- #2199: **Adapt repository for splitted moveit_resources layout**

This is the list of ignored PRs (because they didn't apply easily)
- #2211: Add named logging with LOGNAME to OMPL interface
- #2214: Remove dead code from ompl interface (related to subspaces)
- #2226: Add documentation to ompl interface
- #2227: OMPL interface: fix / ignore clang-tidy warnings

@JeroenDM, all these are recent commits from you. Please decide whether these should be pack-ported as well and file a separate PR in case.

The only other critical PR (during cherry-picking) was #2198, which I thoroughly tested after resolving its conflicts.
As this PR comprises the clang-format-10 change, I suggest to review _individual_ commits.
**This PR is best "merged" from the cmdline via fast-forwarding.**

### CODE REVIEW

**Comment by v4hn** [comment]
:smile: I was about to send you a mail about this branch I just saw.

> a617923 Prefer vendor-specific OpenGL library

Is not actually valid in melodic (the cmake version in bionic is too old), but guarded, so it's ok to merge it nonetheless.

> ~a8ee3cb Fix warnings~

Why not include this, it's simple enough to adapt and improves general issues. Or does the [boost constant](https://github.com/ros-planning/moveit/commit/a8ee3cb11433716baaf9bc23d8aa2a64d799d5c0#diff-198c44e593303bbb85838e64ceb7e8efR44) introduce issues?

**Comment by JeroenDM** [comment]
> @JeroenDM, all these are recent commits from you. Please decide whether these should be pack-ported as well and file a separate PR in case.

I'd be happy to create a PR, if these cleanup commits are considered valuable for the melodic-branch. Personally, I don't need these commits backported until my constrained planning additions are successful enough to be backported. (If ever)

@rhaschke  I hope I did not cause too much of a headache with these commits. If so, I'm sorry.

**Comment by rhaschke** [comment]
> > ~[a8ee3cb](https://github.com/ros-planning/moveit/commit/a8ee3cb11433716baaf9bc23d8aa2a64d799d5c0) Fix warnings~
> 
> Why not include this, it's simple enough to adapt and improves general issues.

I thought this would be specific to Noetic. But, yes, we can apply it too.

> I hope I did not cause too much of a headache with these commits. If so, I'm sorry.

No, not at all. I just didn't dive into the details of these commits and thus I'm asking you to decide yourself, whether or not to backport.

**Comment by v4hn** [comment]
> I'd be happy to create a PR, if these cleanup commits are considered valuable for the melodic-branch. Personally, I don't need these commits backported until my constrained planning additions are successful enough to be backported. (If ever)

Please do so once this request is merged. I believe there is nothing in your requests that would justify keeping it out of melodic and it means more people get to enjoy your improvements. :wink:

**Comment by rhaschke** [comment]
If Travis succeeds on this, I will merge and would like to prepare a new Melodic release. However, it would be great to merge the backport #2245 as well. Can I get an approval for #2245 as well?

**Comment by rhaschke** [comment]
I prepared a new Melodic release (https://github.com/ros/rosdistro/pull/26241) to [unblock the ROS build farm](https://github.com/ros/rosdistro/pull/26237).

**Pull request merged**
