### PR TITLE
add backward compatibility patch for indigo

### PR DESCRIPTION
**Pull request by v4hn**
At [the last developer meeting](https://discourse.ros.org/t/maintainer-meeting-recap-march-7th/1442) we agreed to allow patches that support to compile the `kinetic-devel` branch on ROS indigo.

I worked on that on the side and actually it's quite possible by now if you know what you're doing.
The only problems that are left are the API change in `ros_control` and https://github.com/ros/robot_model/pull/210 .

This patch adds preprocessor magic to support the old `ros_control` API.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Cool

**Comment by hartmanndennis** [comment]
What dependencies have to be changed for this to work? I tried building it with ROS indigo and needed to change geometric_shapes to kinetic-devel version. It seems that I also need a new fcl version and maybe octomap. Are there any other dependencies that need to be updated?

**Comment by v4hn** [comment]
First of all, nobody said it would be simple to cross-compile, right. :)
You're on the right track.

I have the setup working on our PR2, basically you need ompl, fcl and octomap within the same workspace. Due to [a problem with OMPL](https://github.com/ros-planning/moveit/issues/169), you have to remove the system installation of the package (or try to use [a trick](https://github.com/ros-planning/moveit/issues/554#issuecomment-317115618))
Additionally you need the kinetic versions of `geometric_shapes` and `srdfdom`. I'm not sure if anything else was needed right now.

I'll put it on my todo list to describe the setup properly, but I'm overly busy for the next two months - If you manage to get it working, we would very much welcome your contribution!

**Comment by hartmanndennis** [comment]
I got it to build and run the tests successfully by doing the following steps:

- get the docker image moveit/moveit:indigo-source
- checkout kinetic-devel in src/moveit
- checkout kinetic-devel in src/moveit_msgs
- apt-get remove ros-indigo-fcl
- apt-get remove ros-indigo-ompl
- clone geometric_shapes:kinetic-devel
- clone warehouse_ros:jade-devel
- clone robot_model:indigo-devel
- build and install fcl 0.5
- build and install ompl 1.3.1

The default srdfdom in the docker workspace with branch indigo-devel works fine.
robot_model is fixed in indigo-devel, so you shouldn't need it in your workspace anymore after the next indigo release.
octomap indigo-release is fine.

**Comment by v4hn** [comment]
Thanks for the concise summary @hartmanndennis and congratulations on getting it to work! :)

Let's wait with more official documentation until my `robot_model` patch has been released&synced on indigo.

> octomap indigo-release is fine.

I don't remember the details at the moment, but I could have sworn there where some `shared_ptr` related issues when I last tried it...

**Comment by davetcoleman** [comment]
@hartmanndennis could you make a subpage similar to [this one](http://moveit.ros.org/install/source/dependencies/) that is linked from the source install page that advertises this "advanced" usage? Could be useful for others as well as you in the future if you ever have to do it all again.

**Pull request merged**
