### PR TITLE
add FollowJointTrajectoryGoal to moveit_fake_controller_manager

### PR DESCRIPTION
**Pull request by k-okada**
This will take JTA for each limbs

```
/fake_head_controller/cancel
/fake_head_controller/feedback
/fake_head_controller/goal
/fake_head_controller/result
/fake_head_controller/status
/fake_larm_controller/cancel
/fake_larm_controller/feedback
/fake_larm_controller/goal
/fake_larm_controller/result
/fake_larm_controller/status
/fake_rarm_controller/cancel
/fake_rarm_controller/feedback
/fake_rarm_controller/goal
/fake_rarm_controller/result
/fake_rarm_controller/status
/fake_torso_controller/cancel
/fake_torso_controller/feedback
/fake_torso_controller/goal
/fake_torso_controller/result
/fake_torso_controller/status

```

Cc: @7675t

### CODE REVIEW

**Comment by davetcoleman** [comment]
I too am confused by this PR

**Comment by v4hn** [comment]
@k-okada Please have a look at https://github.com/PickNikRobotics/moveit_sim_controller .
I did not try it yet, but @davetcoleman's approach looks somewhat better to me.

**Comment by davetcoleman** [comment]
My moveit_sim_controller approach is very experimental and meant only as loose notes on how to do this properly

**Comment by v4hn** [comment]
Yes, that's why I was talking about "approach", not about code. :)

I very much like the idea to stub the fake execution properly
in an external node. It feels awful that our fake execution mode
does not use the same ROS interfaces as the actual setups.

**Comment by davetcoleman** [comment]
I actually take it back, I think my approach is pretty decent. I think when I wrote my last comment I was confused with another package.

**Comment by 7675t** [comment]
FYI, I'm also developing `fake_joint_controller` in here, it is a "loop-back" controller using ros_control framework.

https://github.com/tork-a/fake_joint
http://wiki.ros.org/fake_joint

**Comment by v4hn** [comment]
As I stated before, I would like to have an external demo mode based on ros_control.
After deprecation of the old mode, it could even replace the current demo mode entirely.

@7675t Could your code directly parse the controller specifications the user defined in `moveit_config/config/controllers.yaml`?

In that case we could add a different demo mode/parameter to the setup assistant that uses your package.

I'm interested in @davetcoleman's opinion on the idea.

**Comment by 7675t** [comment]
> @7675t Could your code directly parse the controller specifications the user defined in `moveit_config/config/controllers.yaml`? In that case we could add a different demo mode/parameter to the setup assistant that uses your package.

I believe it is possible. `fake_joint_driver` package just provides a loop-backed JointPositionController node for all joints in the robot_description(URDF). The controller setting is done by controller_manager same as usual ros_control based system. Please take a look at sample files in [`fake_joint_launch`](https://github.com/tork-a/fake_joint/tree/master/fake_joint_launch), say ur3.launch and config/ur_controllers.yaml. 

It is wonderful if integrated as an option in the setup_assistant. I'm very happy to help to adapt the package if you need. Please tell me what I can do for it.

I personally need this `fake_joint` package to create [jog_control](https://github.com/tork-a/jog_control) package, which expect the trajectory controller accepts continuous trajectories. I believe the fake controller of MoveIt!  does not accept them, and strict on the angle errors in the initial state.

**Comment by henningkayser** [comment]
@7675t @k-okada what's the state of this PR? To me it seems like the implementation is not complete.

The `fake_joint_controller` sounds quite useful but I don't understand why this needs FollowJointTrajectory actions either.
@v4hn do you think this functionality should be added to the fake controller manager?

**Comment by 7675t** [comment]
I have no idea on this PR itself, so please, @k-okada .

Something on `fake_joint` package,  please let me know on the repo(https://github.com/tork-a/fake_joint).

**Comment by v4hn** [comment]
> The `fake_joint_controller` sounds quite useful but I don't understand why this needs FollowJointTrajectory actions either.
> @v4hn do you think this functionality should be added to the fake controller manager?

The current fake controller manager does not expose the standard FollowJointTrajectory actions and the trajectory simulation takes place inside MoveIt only.
This makes it more difficult to introspect time parameterization and debug MoveIt<->controller interplay.
Given the quintic ros_control trajectory controller, I would prefer to leave the world simulation to an external ros_control based controller and get rid of the current fake controller logic altogether.

**Comment by v4hn** [comment]
Closing this as no-merge.

The functionality to enable `FollowJointTrajectory` servers should be provided by external nodes, such as `moveit_sim_controller` or `fake_joint`.

**Pull request closed without merging**
