### PR TITLE
depth_image_octomap_updater: (cherry-pick #1661)

### PR DESCRIPTION
**Pull request by v4hn**

### CODE REVIEW

**Comment by v4hn** [comment]
I am not allowed to merge this (we need to talk about permissions).

Please someone do so.

**Comment by jonbinney** [comment]
@v4hn i think some of the perception stuff in particular doesn't have enough reviewers since i haven't had time to contribute for a while. I'd support dropping me as a maintainer and adding someone with enough time to do reviews regularly.

**Comment by v4hn** [comment]
Thanks for merging.

> i think some of the perception stuff in particular doesn't have enough reviewers [...]

That's true for all of MoveIt.

> adding someone with enough time to do reviews regularly.

You're free to propose candidates (who contributed before according to [our policy](https://moveit.ros.org/about/maintainer_policy/)).

**Comment by jonbinney** [comment]
Unfortunately i don't have any candidates - just wanted to be up-front that i've got limited time these days.

**Pull request merged**
