### PR TITLE
Exposed planners from latest ompl release.

### PR DESCRIPTION
**Pull request by rbbg**
### Description

This PR exposes the following OMPL planners:

geometric::FMT
geometric::BFMT
geometric::PDST
geometric::STRIDE
geometric::BiTRRT
geometric::LBTRRT
geometric::BiEST
geometric::ProjEST
geometric::LazyPRM
geometric::LazyPRMstar
geometric::SPARS
geometric::SPARStwo

Several other planners are available in OMPL, but from I found those to not work out of the box so some work would be required in integrating those.

To test: I have a forked moveit_resources (over [here](https://github.com/rbbg/moveit_resources/tree/kinetic-ompl-planners)) that has a ompl_planning.yaml with (parameter-less) configurations for these planners.

Due to the difference in OMPL version between kinetic and jade/indigo, this should not be cherry picked (I think).

### CODE REVIEW

**Comment by davetcoleman** [comment]
Awesome, thank you!

Can you also add [default parameter values](https://github.com/ros-planning/moveit/blob/3c760fe2d1319dffb410e71729c5c548c9c4c842/moveit_setup_assistant/src/tools/moveit_config_data.cpp) for these planners in the Setup Assistant in this PR so that its easier for new users to configure these planners?

**Comment by rbbg** [comment]
I would like to, but I honestly have no clue what would be logical settings for most of these parameters, so I don't really know how to go about it. I figured it was perhaps best let to OMPL to select the defaults. Thoughts on how to go about this?

**Comment by davetcoleman** [comment]
In the Setup Assistant defaults, just copy the default already provided in each planner's config. e.g. for FMT you can see its defaults in the [constructor](http://ompl.kavrakilab.org/FMT_8cpp_source.html)

This allows users to easily tweak the settings in the future, and keeps the planner setup consistent in MoveIt!

**Comment by rbbg** [comment]
I'm working on this but am running into a couple of problems so it might be a couple of days.

**Comment by rbbg** [comment]
For some reason FMT and BFMT are not finding any solutions at the moment, so I need to see where that is coming from, I pretty sure they were working before so not sure what that is about. Also, my clang-format plugin seems to have some problems :(

**Comment by davetcoleman** [comment]
> For some reason FMT and BFMT are not finding any solutions at the moment, so I need to see where that is coming from

Is a parameter set incorrectly in theses defaults? I'm ok merging these new features now and worrying about tweaking individual parameters later.

> Also, my clang-format plugin seems to have some problems :(

I'm curious - did you have to manually fix the formatting then? What version are you using?

**Comment by rbbg** [comment]
> Is a parameter set incorrectly in theses defaults? I'm ok merging these new features now and worrying about tweaking individual parameters later.

I don't think it's a parameter. I tried with an empty configuration but that didn't work either.

> I'm curious - did you have to manually fix the formatting then? What version are you using?

I was using clang-format-3.8 but that isn't compatible as demonstrated by #344. As a matter of fact, the formatting changes I saw in the diff of that PR were identical to the ones I was having in my `moveit_config_data.cpp` file. Switching to clang-format-3.6 fixed it.

**Comment by davetcoleman** [comment]
Thanks so much! Please open another PR when you get a chance to look at FMT / BFMT

**Comment by gavanderhoorn** [comment]
@rbbg: is the 'regular' binary distributed OMPL release (on Kinetic) enough for this, or do we need a source install?

**Comment by davetcoleman** [comment]
@gavanderhoorn the binary should work because Travis passed that uses OMPL from binary

**Comment by gavanderhoorn** [comment]
Right. Missed that. Thanks.

**Pull request merged**
