### PR TITLE
backport #247 to indigo

### PR DESCRIPTION
**Pull request by v4hn**

### CODE REVIEW

**Comment by davetcoleman** [comment]
trivial feedback, but would prefer a href link to the original PR in the description, e.g.: https://github.com/ros-planning/moveit/pull/247

**Comment by davetcoleman** [comment]
looks like during the cherry-pick, the original moveit_ikfast folder was not completely deleted:
https://github.com/v4hn/moveit/tree/fe950a1841c87ddcf281a22c704ab8927faa4d7e/moveit_ikfast

**Comment by v4hn** [comment]
Thanks, git pointed this out to me during cherry-picking already, so I should have noticed...
I removed the folder completely now.

**Comment by davetcoleman** [comment]
thanks for fixing @v4hn

**Pull request merged**
