### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mcevoyandy**
why doesn't MoveIt! have a code of conduct? I think it's essential to promote an all-inclusive and welcoming atmosphere.

### Description

added code of conduct from [Contributor Covenant](https://www.contributor-covenant.org/)

### Checklist
- [ ] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I think this is an ok idea. I wouldn't call it *essential* though.

**Comment by bmagyar** [comment]
It's not bad although Linus Torvalds would fail on many of these points.

IMHO a project is there primarily to be useful for the community, not to be
welcoming.

On Oct 17, 2017 19:00, "G.A. vd. Hoorn" <notifications@github.com> wrote:

I think this is an ok idea. I wouldn't call it *essential* though.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-planning/moveit/pull/647#issuecomment-337311844>,
or mute the thread

**Comment by v4hn** [comment]
*sigh*

To be honest I simply don't care about an explicit COC.
I don't oppose, but I don't particularly approve either.

For a long time the general maxim "be excellent to each other" was good enough for FOSS projects.
In my opinion it still is.

That being said, if we want to merge this file, we will have to talk about it at a maintainer meeting before, because this makes us as maintainers to blame if something goes wrong somewhere.

It would be nice if you could attend the next video meeting @mcevoyandy .

**Comment by davetcoleman** [comment]
Good point, lets discuss at a maintainer meeting! I think overall its a good discussion to have and can possibly improve MoveIt!'s legitimacy for securing grant money to fund open source projects

**Pull request closed without merging**
