### PR TITLE
Fix set start state to current

### PR DESCRIPTION
**Pull request by jrgnicho**
### Description
Actually sets the start state to the current state.  Previously it would only reset the pointer.

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!

### CODE REVIEW

**Comment by v4hn** [comment]
> Actually sets the start state to the current state.  Previously it would only reset the pointer.

I didn't look at your patch, but a null_ptr/an empty state is the *current state of the move_group upon receiving the request*.
This is actually more current and should be preferred for planning requests from external sources from my point of view..

**Comment by jrgnicho** [comment]
@v4hn the name of the method suggest to me that it'll fetch the current robot state and apply it to the start state.

**Comment by bmagyar** [comment]
> *current state of the move_group upon receiving the request*.
I had the same problem in #675 , couldn't figure out how and where this should be handled, actually added the same steps manually to my tests in #626 .

Should the planner plugin be fetching the last state with a null start_state? (In case of a yes I will add this to CHOMP)

**Comment by jrgnicho** [comment]
@bmagyar OMPL fills an empty start state with the current one but STOMP just errors out and prints a message.  I don't feel very strongly about this but personally I think that whoever is sending the motion plan request sure ensure that it is properly created.

**Comment by bmagyar** [comment]
I see the logic behind both approaches however requiring the planners to fetch the current state is a bit awkward. 

I think either move_group should have support for this either by default built-in or via a request adapter by default. The emphasis here is on _by default_. 

At the same time, the API in question is indeed misleading and the PR is correct. Maybe it's worth adding another function (with some explanation) that'd achieve "current state given XY" by sending the empty start_state. 

Now I may be going off-track but we could even introduce a new `autofill_current` flag to the RobotState message.

**Comment by v4hn** [comment]
> At the same time, the API in question is indeed misleading and the PR is correct

I disagree. The `MoveGroupInterface` is a "handy wrapper to access move_group's functionality".
The correct thing to do in the wrapper is to clear the start state and leave it to the `move_group` to know the correct values. Even so, I agree that we should add a comment that explains why an empty start state represents the current state here.

> > OMPL fills an empty start state with the current one
> 
> I think either move_group should have support for this either by default built-in [...]

I **strongly** agree that the `move_group` should fill in the start state and not the planner.
I didn't know that was not case!
At first glance this could go right [here](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/move_group/src/default_capabilities/move_action_capability.cpp#L150) - At least this is where I expected it.

**Comment by jrgnicho** [comment]
@v4hn  documenting what move_group does with a null start state would be helpful indeed, however it seems that the [intent ](http://docs.ros.org/kinetic/api/moveit_ros_planning_interface/html/classmoveit_1_1planning__interface_1_1MoveGroupInterface.html#a34e857711a8dca3e98635f4925abaf46) of the ```setStartStateToCurrentState``` method is to grab the current robot state and populate the start state instead of setting it to null.
It would make more sense to name the method ```clearStartState()``` and describe how move group assumes that the current robot state is the start when its given a null pointer.  However I rather stay away from renaming methods.

**Comment by v4hn** [comment]
> it seems that the intent of the setStartStateToCurrentState method is to grab the current robot state and populate the start state instead of setting it to null.

That depends on how you interpret the description you cite, which indeed is ambiguous:

> Set the starting state for planning to be that reported by the robot's joint state publication

imho implies that *planning* (i.e. `move_group`) uses the published state as start state, not the planning interface :-)
Personally I believe this is more in line with the description for `setStartState` above the one you cite:

> If a different start state should be considered instead of the current state of the robot, this function sets that state. 

But either way, I believe we both explained our points of view well enough.

I would very much prefer not to change semantics here (and break with previous behavior)
if there is a feasible interpretation that explains the current behavior.
If we would accept this pull-request, some nodes would that didn't need it before will connect to the `joint_states` topic for basically no reason at all.

Instead we need proper documentation that explains the current behavior.

**Comment by davetcoleman** [comment]
I agree with @v4hn about preferring not to change semantics here but that documentation is key (in the moveit_msg source and in this move_group_interface).

Another reason why I like the current nullptr start state is that it would likely reduce state latency by filling in the current state closer to the planner, rather than before a ROS message hop.

**Comment by jrgnicho** [comment]
I'm on board with better documentation but I do think that at some level the current robot's joint state needs to be captured and used to fill the start state. Preferably this would be done after the ROS service call but it just seems easier to do in the move_group_interface and I'm not sure that the latency penalty is too significant.

**Comment by znbrito** [comment]
@jrgnicho why does the current version of the whole package (last commit yesterday on the kinetic devel, which is the one I have installed) doesn't have this changes applied in the code? Was this commit accepted? Cause I cannot refresh my robot position after I execute a plan and I tried to alter the code from my program according to the changes you made but I just can't seem to find a solution. I can't alter the code from the move_group_interface.hpp (and *.cpp), so what do you think I should do? Thanks in advance.

**Comment by v4hn** [comment]
> Was this commit accepted?

No.

> Cause I cannot refresh my robot position after I execute a plan [...]

This sounds like your move_group does not connect to the correct joint_states topic.
Either way, please file a new issue for this and provide more details, at least a minimal code example.

**Comment by znbrito** [comment]
@v4hn I created a new issue on https://github.com/znbrito/Brito-thesis-Robotis-Manipulator-H-path-planning/issues/1 , hope you can help me! And thanks for your tip, that solved my first error, but now I have another one.

**Comment by davetcoleman** [comment]
@jrgnicho should this PR be closed? I believe one outcome of this issue you brought up was to improve the documentation around this weird behavior, can you do that?

**Pull request closed without merging**
