### PR TITLE
TrajectoryDisplay: hide links in trail

### PR DESCRIPTION
**Pull request by simonschmeisser**
### Description

This allows to hide some parts of the robot in the trail mode by applying the general link visibility to the trail as well.

It is currently only applied on new incoming trajectories but adding some signal-slots for live update would be possible as well of course

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by v4hn** [comment]
I love the idea!

> It is currently only applied on new incoming trajectories but adding some signal-slots for live update would be possible as well of course

Does that mean you will do it as part of this PR?

**Comment by rhaschke** [comment]
Great contribution. I was missing this exact feature this week as well...
Please add slot methods to react to changes of the corresponding toggles live as well.

**Comment by simonschmeisser** [comment]
Just wanted to clean up my workspace and gather interest. I'll try to add the signal slots as well

**Review by rhaschke — APPROVED** [review]
Thanks for further improving this. Looks good and works as expected.
I only have a small nitpick.

**Pull request merged**
