### PR TITLE
Melodic backports

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Here are the backports from https://github.com/ros-planning/moveit/issues/2387 that I found to be straightforward to apply.  If anyone has a workspace that is currently using the debian installed Melodic release it would be helpful if you could test your application with this branch of moveit.

### CODE REVIEW

**Review by AndyZe — APPROVED** [review]
I checked this out and tested it on a rather large demo we have (2 different types of robot arms). No issues.

I guess that's about all you can do for reviewing such a large PR

**Comment by tylerjw** [comment]
Thank you, these are all changes that were merged into master.  Most of what reviewing this is verifying they don't break setups that work currently with the melodic-devel branch.

**Comment by tylerjw** [comment]
I'd like to get a second review before I merge this mostly because I don't know what is in all these changes and am unsure how to test this well.

**Comment by tylerjw** [comment]
I tested this using a customer's project that is using moveit via the debians in melodic.  This did not cause any issues for that project.  If there are no objections to this before Friday I plan on merging this Friday and making a melodic release based on this.  

If anyone else has a project that runs on the moveit melodic debians it would be helpful if you could test this.

If anyone who had anything to do with the list of backported RPs could read through them and let me know if any of them shouldn't be in melodic that would be important too.

**Comment by felixvd** [comment]
I don't see any commits I remember that would cause an issue. 

Another thing: I see #2320, but what about #2310 ? That would be great to have in Melodic. I think the only Noetic-only thing about are the two words "and subframes". Apart from that it should work.

**Comment by felixvd** [comment]
I took the liberty of adding it with the small change I mentioned above.

**Review by felixvd — APPROVED** [review]
Not that I can really look at the details, but from what I can see it is fine.

**Comment by rhaschke** [comment]
@tylerjw, thanks for handling the backport. Looks like you forgot to update the branch `reviewed-for-backport`.
As far as I can see, I should be moved forward to e337c0808be9b561d62f5c41c267643f5b46eb00. Can you confirm?

**Comment by tylerjw** [comment]
I haven't advanced it yet.  I couldn't get the pre-release tests to pass locally.  This pr may have been merged prematurely.  I want to make sure pre-release tests pass before moving forward with the melodic release.

**Comment by rhaschke** [comment]
Can you report the error you obtaining from prerelease tests? Maybe I can help.

**Comment by tylerjw** [comment]
I started a level 1 test on my laptop that is slow (and didn't finish until sometime yesterday).  It looked like it mostly worked.  On my desktop which is much faster I tried running it inside a lxc container and kept having trouble on friday.  I just looked at the output of the level 1 dependency run on my laptop and these are the failures.  Do we care about these / are they a problem or should I move ahead with the melodic release?

```
jsk_pcl_ros/rosunit-test_add_color_from_image.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_add_color_from_image_to_organized.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_attention_clipper.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_bilateral_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_border_estimator.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_capture_stereo_synchronizer.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_cluster_point_indices_decomposer.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_cluster_point_indices_decomposer_sort_by.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_collision_detector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_color_based_region_growing_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_color_histogram.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_colorize_map_random_forest.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_colorize_random_forest.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_convex_connected_voxels.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_depth_calibration.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_depth_image_creator.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_edge_depth_refinement.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_edgebased_cube_finder.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_environment_plane_modeling.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_euclidean_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_extract_top_polygon_likelihood.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_feature_registration.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_find_object_on_plane.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_fuse_depth_images.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_fuse_rgb_images.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_grid_sampler.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_handle_estimator.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_heightmap_converter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_heightmap_morphlogical_filtering.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_heightmap_time_accumulation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_heightmap_to_pointcloud.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_hinted_handle_estimator.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_hinted_plane_detector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_hinted_stick_finder.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_hsi_color_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_icp_registration.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_in_hand_recognition_manager.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_incremental_model_registration.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_intermittent_image_annotator.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_joint_state_static_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_keypoints_publisher.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_line_segment_collector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_line_segment_detector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_linemod_detector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_marker_appender.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_mask_image_cluster_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_mask_image_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_moving_least_square_smoothing.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_multi_euclidean_clustering.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_multi_plane_extraction.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_multi_plane_sac_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_normal_direction_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_normal_estimation_integral_image.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_normal_estimation_omp.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_octomap_contact.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_octree_change_publisher.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_octree_voxel_grid.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_organized_edge_detector.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_organized_multi_plane_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_organized_pointcloud_to_point_indices.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_organzed_pass_through.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_parallel_edge_finder.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_particle_filter_tracking.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_particle_filter_tracking_service_renew.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_plane_supported_cuboid_estimator.xml: 1 tests
jsk_pcl_ros/rosunit-test_plane_time_ensync_for_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_pointcloud_database_server.xml: 1 tests
jsk_pcl_ros/rosunit-test_pointcloud_localization.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_pointcloud_screenpoint_published.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_region_growing_multiple_plane_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_region_growing_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_resize_points_publisher.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_rgb_color_filter.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_roi_clipper.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_selected_cluster_publisher.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_snapit.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_supervoxel_segmentation.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_target_adaptive_tracking.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_tilt_laser_listener.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_torus_finder.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_voxel_grid_downsample.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros/rosunit-test_voxel_grid_large_scale.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/roslaunch-check_test_add_point_indices.test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/roslaunch-check_test_subtract_point_indices.test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_add_point_indices.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_centroid_publisher.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_cloud_on_plane.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_cloud_on_plane_info.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_colorize_height_2d_mapping.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_delay_pointcloud.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_evaluate_voxel_segmentation_by_gt_box.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_marker_array_voxel_to_pointcloud.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_mask_image_to_depth_considered_mask_image.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_normal_concatenater.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_normal_flip_to_frame.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_plane_reasoner.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_relative_from_pose_stamped.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_to_cluster_point_indices.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_to_mask_image.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_to_point_indices.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_xyz_to_xyzrgb.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_pointcloud_xyzrgb_to_xyz.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_polygon_appender.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_subtract_point_indices.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_pcl_ros_utils/rosunit-test_tf_transform_cloud.xml: 1 tests, 0 errors, 1 failures, 0 skipped
moveit_opw_kinematics_plugin/MISSING-rostest-test_test_fanuc.xml: 1 tests, 0 errors, 1 failures, 0 skipped
moveit_opw_kinematics_plugin/MISSING-rostest-test_test_fanuc_faulty_params.xml: 1 tests, 0 errors, 1 failures, 0 skipped
moveit_opw_kinematics_plugin/MISSING-rostest-test_test_kuka.xml: 1 tests, 0 errors, 1 failures, 0 skipped
moveit_opw_kinematics_plugin/MISSING-rostest-test_test_kuka_faulty_params.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```

**Comment by rhaschke** [comment]
`jsk_pcl_ros` don't even run their tests on Travis: https://travis-ci.org/github/jsk-ros-pkg/jsk_recognition/builds/744574056
`moveit_opw_kinematics_plugin` succeeds: https://travis-ci.org/github/JeroenDM/moveit_opw_kinematics_plugin/branches
So, here it would be interesting to understand why the tests don't run.

**Comment by tylerjw** [comment]
I searched back through the logfile from running the pre-release tests and I can't find the output of starting those tests (where it would say it exited with some return code).

**Comment by knorth55** [comment]
>jsk_pcl_ros don't even run their tests on Travis: travis-ci.org/github/jsk-ros-pkg/jsk_recognition/builds/744574056

What do you mean?
we are running test on our jenkins server, which is triggered from travis-ci.
does `jsk_pcl_ros` matter pre-release test of moveit?

**Pull request merged**
