### PR TITLE
[master] Update version info to 1.0.1

### PR DESCRIPTION
**Pull request by 130s**
### Description

- Update all version info as 1.0.1.
  - This is similar to https://github.com/ros-planning/moveit/pull/1363 and https://github.com/ros-planning/moveit/pull/1362 for 1.0.0, but with a single PR. `bloom`-ready once merged.

### Checklist
- [x]  I don't request review, same reason as https://github.com/ros-planning/moveit/pull/1362#issuecomment-466835576. This can be merged once all check items are checked.
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/) --> No need.
- [x] Include a screenshot if changing a GUI --> No need.
- [x] Document API changes relevant to the user in the moveit/MIGRATION.md notes --> No need.
- [x] Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html) --> No need.
- [ ] Decide if this should be cherry-picked to other current ROS branches

### Post-merge actions
- [ ] Push `tag 1.0.1`.
- [ ] Go back to the action item list https://github.com/ros-planning/moveit/issues/1326

### CODE REVIEW

**Comment by rhaschke** [comment]
Please hold on. I'm currently fixing a whole bunch of compiler warnings in the MoveIt codebase.
I think if we go for a 1.x release, this should be incorporated.

**Comment by 130s** [comment]
As discussed around https://github.com/ros-planning/moveit/issues/1326#issuecomment-469902318, the whole point of 1.0.1 **patch release** is to verify if #1371 is fixed or not, which is only possible on ROS buildfarm as we agreed https://github.com/ros-planning/moveit/issues/1326#issuecomment-469406447. 

I do not mind making another patch release soon after 1.0.1 to include more bugfixes or any patches. I think that's what @davetcoleman suggests at https://github.com/ros-planning/moveit/issues/1326#issuecomment-469902318 and I agree with that.

**Comment by rhaschke** [comment]
I don't see the point in doing a "test" release, just to verify #1371. I'm really confident that it is fixed. However, I agreed that the final proof will be given by a release only.
But, as you know, I don't like cluttering the release history with lots of fake releases...

**Comment by 130s** [comment]
1.0.1 won't be a "test" release. It'll be a "real" bugfix release, as 1.0.0 had a critical build issue as you pointed out https://github.com/ros-planning/moveit/issues/1326#issuecomment-467351712.

> I don't like cluttering the release history with lots of fake releases...

Again it's not a fake release. But what do you specifically mean by "release history"? 

If it's changelog, I agree that smaller sets of changelog might obfuscate the significance of a major change like MoveIt! 1.0 release. I can consolidate the changelogs of 1.0.0 and 1.0.1 (that shouldn't be an issue IMO, as 1.0.0 didn't make it to rosdistro).

**Comment by rhaschke** [comment]
> But what do you specifically mean by "release history"?

I'm talking about our history of release tags. In the recent past, we had several broken releases, which didn't actually made it to rosdistro, but still are listed in the list of release tags. Doing a release, which is immediately superseded by another one, doesn't make sense to me very much.

**Comment by rhaschke** [comment]
> I can consolidate the changelogs of 1.0.0 and 1.0.1.

I remember that this causes issues with `catkin_prepare_release` later on.

**Comment by 130s** [comment]
> history of release tags.

I see. I'd say it's not ideal but ok. As long as the latest release is usable.

>>    I can consolidate the changelogs of 1.0.0 and 1.0.1.
>
> I remember that this causes issues with catkin_prepare_release later on.

Hmm, ok. IMO the most important changelog will be the one included in the release announcement, which we can and should manually edit to make it meaningful to the general public audience (for the changelogs committed to git, like the ones in this PR, I try to make them look meaningful but they can still contain trivial changes).

**Comment by rhaschke** [comment]
> I remember that this causes issues with catkin_prepare_release later on.

As far as I remember, catkin_prepare_release gets confused if there are changelog sections missing for existing release tags.

I filed two new, simple PRs which I would like to have included in the 1.0 release.
* [ ] #1380: fix more warnings
* [ ] #1381: fix flaky unit tests

@130s, feel free to review and merge them. Subsequently I'm happy to proceed with the release process as well.

**Comment by davetcoleman** [comment]
> I see. I'd say it's not ideal but ok. As long as the latest release is usable.

+1 to @130s thoughts

**Pull request merged**
