### PR TITLE
Clang tidy core

### PR DESCRIPTION
**Pull request by BryceStevenWilley**
### Description

Extended clang-tidy from collision_detection (#693) to the rest of moveit_core. Each commit is a specific [clang-tidy check](http://releases.llvm.org/3.8.0/tools/clang/tools/extra/docs/clang-tidy/checks/list.html), it's probably easier to browse through each commit individually.

To keep this commit manageable, I only did clang-tidy checks that included automatic/simple fixes. In the future, we should look into enabling and fixing checks like cppcoreguidelines-* (http://releases.llvm.org/3.8.0/tools/clang/tools/extra/docs/clang-tidy/checks/list.html), as those are the most likely to result in fewer segfaults and silent bugs.

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Include a screenshot if changing a GUI
- [x] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [x] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by v4hn** [comment]
Hey there,

most changes look alright.

On dca3919bf8fbf81a92f772c2db8bfb8c0f21e2f1 and 4a082b3f6a9622de2da1dc93cae5897dac48c51e :
I'm not a fan of `auto` at all. It's fine for prototyping, but it makes big code bases like MoveIt harder to understand.
@davetcoleman @bmagyar @rhaschke I believe we should discuss this in the next meeting.

What is 050f998f5009aa19c83dfdc7b75a05da287f5b09 about? Most of the changes there are uncalled for or make no sense semantically.

**Comment by BryceStevenWilley** [comment]
Understandable, `auto` does obscure a bit. However, clang-tidy [only replaces](http://releases.llvm.org/3.8.0/tools/clang/tools/extra/docs/clang-tidy/checks/modernize-use-auto.html) explicit types with `auto` for iterators and for `new` statements, where the type is explicitly written out twice. That seemed like a reasonable compromise IMO. 

 050f998 was checking to see if the parameter names in the function declaration matched the same name in the function definition, and it copied the name over from the definition if they didn't match. Looking at the specific changes though, I agree that the new names aren't as good. I'll take a look at this soon and try to choose the better of the two names.

**Comment by rhaschke** [comment]
I agree with @BryceStevenWilley regarding use of `auto` in `for` loops and the like. Usually it increases readability if code becomes less cluttered. However, as soon as IDEs can't resolve the type anymore, `auto` turns into a hurdle.

**Comment by davetcoleman** [comment]
I'm a fan of this, including ``auto`` changes described here. Sorry we have been slow in merging this, as there are now a lot of merge conflicts. I think the biggest conflict is going to be https://github.com/ros-planning/moveit/pull/662

**Comment by BryceStevenWilley** [comment]
Possible merge ping.  Merge conflicts gather up pretty quickly.

**Comment by rhaschke** [comment]
@BryceStevenWilley I'm sorry that we were so slow on merging this. However, I think instead of merging your branch into the current HEAD you should have rebased onto the current HEAD. Now the commit history as well as githhub's diff are messed up. Please can you fix this by rebasing your PR branch onto HEAD?

@v4hn @davetcoleman Did we agree on the set of tidy changes to apply? Should we discuss that on the next maintainer meeting and then tackle this PR from scratch?

**Comment by davetcoleman** [comment]
I feel ok with the sparing use of ``auto`` in this PR, but since it is a bit controversial I think the best approach would be to remove that commit (https://github.com/ros-planning/moveit/commit/4a082b3f6a9622de2da1dc93cae5897dac48c51e) and the corresponding rule in the .clang-tidy file then quickly merge this.

The other two commits that @v4hn brought up seem fine to me after @BryceStevenWilley's explanation

We can discuss auto further at the next meeting

**Comment by BryceStevenWilley** [comment]
@rhaschke I couldn't clean the commit history on this particular branch, but I've made a duplicate PR (#880) to address the history issue. This isn't the first time you've pointed out my messy merge history, I'll try to rebase more in the future. :sweat_smile:.  

@davetcoleman The auto changes have been removed in #880, I'll close this PR. Sorry for the noise.

**Pull request closed without merging**
