### PR TITLE
unlock planning scene before next service call

### PR DESCRIPTION
**Pull request by Jntzko**
We want to use get_planning_scene service in our grasp planning service, this will lock the planning scene.
The problem is that the planning scene is already locked in the fillGrasps method.
So the planning scene should be unlocked before we call the grasp planner.

### CODE REVIEW

**Comment by v4hn** [comment]
I authored this patch together with @Jntzko and we tested it locally.
It simply does not feel right to lock the scene during the service call and it actually breaks if the external module wants to communicate back to the scene.
We discovered the fault and tested this patch in our local setup and it works.

+1

**Comment by rhaschke** [comment]
Unlocking the scene might result in a different scene state used for grasp planning. I think, the scene shouldn't be updated during the planning process. Here, this might affect the pose (and even existence) of the to-be-grasped object.
As get_planning_scene_service locks the scene read-only too, there shouldn't be a locking issue, because read-only locks are shared locks, i.e. there can be multiple locks in different threads in parallel.
-1

**Comment by v4hn** [comment]
On Thu, Aug 18, 2016 at 07:14:35AM -0700, Robert Haschke wrote:
> Unlocking the scene might result in a different scene state used for grasp planning.
> I think, the scene shouldn't be updated during the planning process.
> Here, this might affect the pose (and even existence) of the to-be-grasped object.

This is the very first thing that happens when the `PickAction` is executed, if there are no grasps supplied.
Only *much later* in `plan_execution::PlanExecution::planAndExecute` the planning scene is fetched,
and in between the lock is dropped anyway because the scene is only locked in `fillGrasps`.
So I don't think this is a valid argument at all. If it is, the `pick_place` modules should be drastically refactored.
(Something like that is on my long-term-agenda anyway).

> As get_planning_scene_service locks the scene read-only too, there shouldn't be a locking issue,
> because read-only locks are shared locks, i.e. there can be multiple locks in different threads in parallel.

That was my thought too, but this patch fixed the issue, so there is some catch I didn't find yet.
I'll have another look into this once I have the time..

Nevertheless, I still consider this patch perfectly valid.

**Comment by rhaschke** [comment]
I can agree to your argumentation. 
> That was my thought too, but this patch fixed the issue, so there is some catch I didn't find yet.

However, not understanding why releasing the shared lock in between is necessary, is not so satisfactory.

**Comment by v4hn** [comment]
On Fri, Aug 19, 2016 at 10:56:22AM -0700, Robert Haschke wrote:
> However, not understanding why releasing the shared lock in between is necessary, is not so satisfactory.

Yes. I'd say the -1 still stands until I analyzed this further.

**Comment by v4hn** [comment]
Ok, I just spend hours digging through the locking of the scene when once quick thought should have been enough...
Here's the problem:

1. fillGrasps read-locks the scene
- fillGrasps calls the external grasp service
- the external service calls `get_planning_scene`
- `scenePublishingThread` is scheduled with a write-lock (yes, this write-locks -.-) to the scene
- `get_planning_scene` is processed and is scheduled *after* `scenePublishingThread`.
  This is because there is a writer in the scheduling queue and thus the new thread can't just share the lock with `fillGrasps`...

That's basically what I meant with:
> It simply does not feel right to lock the scene during the service call

:)

@rhaschke please review again.

**Comment by rhaschke** [comment]
Cherry-picked to J/K.

**Pull request merged**
