### PR TITLE
Travis: re-enable ros-shadow-fixed

### PR DESCRIPTION
**Pull request by rhaschke**
A new eigenpy version is released to ros-shadow-fixed...

### CODE REVIEW

**Comment by rhaschke** [comment]
eigenpy is still failing

**Comment by v4hn** [comment]
Even once the eigenpy issue is resolved, I oppose this as a required check for CI.

Having this job for pull-requests can and does break our whole merge process which can only be overridden by github administrators.

Two alternatives I see:
- allow the job to fail - in theory it should still send mails on failure?
- add the job only for the main branches. This way we would see issues in shadow-fixed but they would not block CI.

**Comment by gavanderhoorn** [comment]
Third option: enable "cron builds". Those would run independently of CI, and could be used to periodically check whether any upstream changes in MoveIt's dependencies have introduced any breaking changes.

**Comment by rhaschke** [comment]
> Having this job for pull-requests can and does break our whole merge process

And we want it to break early and noticable, so that we can take counter measures...

> ... which can only be overridden by github administrators.

Not really true. Every maintainer can (temporarily) disable the ros-testing by editing `.travis.yml`.

> Third option: enable "cron builds".

Interesting idea. Checking the environment variable [`$TRAVIS_EVENT_TYPE == "cron"`](https://docs.travis-ci.com/user/cron-jobs/) we can limit the corresponding job to cron builds.
A remaining question is how to (email) notify the maintainers in case of a failure of this particular job.

**Comment by v4hn** [comment]
> > ... which can only be overridden by github administrators.
> 
> Not really true. Every maintainer can (temporarily) disable the ros-testing by editing .travis.yml.

I don't see how you can propose auxiliary commits to temporarily change travis and at the same time force-push because of merge commits. Either you aim to keep the commit history clean or you don't.

I just filed https://github.com/ros-planning/moveit/pull/2012

**Comment by rhaschke** [comment]
So, you don't like temporarily modifying Travis?

**Comment by v4hn** [comment]
No.

**Pull request merged**
