### PR TITLE
Hide moveit_ikfast for now for more discussion 

### PR DESCRIPTION
**Pull request by 130s**
Following the decision in https://github.com/davetcoleman/moveit_merge/issues/9

### CODE REVIEW

**Comment by 130s** [comment]
NOTE: I'm also committing `CATKIN_IGNORE` despite the fact that it's in the [ignore list](https://github.com/ros-planning/moveit/blob/a2696956d7c95e88234685d74d790cc04ac81876/.gitignore#L49), because of the discussion https://github.com/davetcoleman/moveit_merge/issues/9

**Comment by davetcoleman** [comment]
What is the minimum change we need to make to release the ``moveit`` repo without ikfast? Would just the CATKIN_IGNORE work? Or do we need to do nothing at all?

**Comment by davetcoleman** [comment]
I just noticed that moveit_controller_manager_example package has never been released, which is as intended. However there is no CATKIN_IGNORE in that package's folder. This makes me think you don't need to change anything for skipping releasing moveit_ikfast in this repo.

**Comment by 130s** [comment]
I guess you're right. In order for a package to be "released" in ROS-sense, all it needs is to be listed at ros distro file (e.g. [indigo](https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml)).

That said,
- having CATKIN_IGNORE still helps those who want to build from source.
- moving `moveit_ikfast` under subfolder may not be needed? I have no opinion about this.

**Comment by v4hn** [comment]
> having CATKIN_IGNORE still helps those who want to build from source.

How? There's nothing *wrong* with it.
It has a problematic version number, that's all...

Moving the module into `moveit_ros/planning` would make it part of the `moveit_ros_planning` ros package.
Thus, this would allow us to get rid of the 3.x version number.
Personally, I don't understand why the other kinematics plugins are in there and wouldn't `move_ik_fast` in there either...
In my opinion it would make more sense to create a new top-level-folder/package `moveit_kinematics_plugins` in the repo and make it part of the meta-package.
This should even be possible without breaking anything, because the plugin-descriptions do not reference the package name and the only way the plugins are used is through their plugin descriptions.

**Comment by 130s** [comment]
I'm only commenting about CATKIN_IGNORE.

>>    having CATKIN_IGNORE still helps those who want to build from source.
>
> How? There's nothing wrong with it.
> It has a problematic version number, that's all...

Sorry, I was unclear, and I might be misunderstanding something. 
I thought people who checks out `moveit` repo didn't want to build `moveit_ikfast` package. My comment above is based on this assumption.
If this is wrong then I don't see a reason to add CATKIN_IGNORE at moveit_ikfast; aside from release context, I don't see any harm for having a problematic version number (assuming moveit_ikfast stays OUT of `moveit` metapkg).

**Comment by davetcoleman** [comment]
> In my opinion it would make more sense to create a new top-level-folder/package moveit_kinematics_plugins in the repo and make it part of the meta-package.

I have been thinking about this for a long time. But I don't think we should be debating that sort of thing while we block all of the build farm from syncing

> I thought people who check out moveit repo didn't want to build moveit_ikfast package.

No, I only suggested it if it was needed by bloom. I'm pretty sure its not. I think we can close this PR for now and just release MoveIt!

**Comment by 130s** [comment]
Everything's clear to me now. Closing.

**Pull request closed without merging**
