### PR TITLE
Add pre-commit with GitHub Action

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

This adds the pre-commit GitHub Action for testing formatting of this repo.  One really awesome thing about this is it can use the exact same configuration as the one in the moveit2 repo as it does not depend on any ros infrastructure.  It also runs very quickly in GitHub Actions and will make migrating to CircleCI easier as I will not have to include formatting checks in the CircleCI pipeline.

These formatters can easily be run locally by installing the pre-commit package.  You can do that like this:

```
pip3 install pre-commit
```

Then to run it manually you can do this in the repo directory:
```
pre-commit run -a
```

To have it install in your github hooks to run automatically when you do a `git commit` do this:
```
pre-commit install
```

There are a few new formatters added by this that are really useful in themselves because they will reduce bike shedding and having to comment on formatting issues in PRs.  Specifically this adds these checks to our CI system:

```
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
```

Documentation on what all these do can be found here: https://github.com/pre-commit/pre-commit-hooks

I will just point out that some of the real nice improvements are checking for:
* correct yaml syntax
* end of file new lines
* mixed line endings
* trailing whitespace
* python3 compatibility

Next this will run clang-format automatically and removes the step of clang-formatting your code as it can now be part of a git hook.

Lastly, this adds a new formatter for python files.  `black` is like `clang-format` for python.  It will reformat all the python files to have a unified style.  This is really nice because it makes python files all have the same style.  I am also adding this to moveit2 so it shouldn't impact syncing.  Here is the PR for that: https://github.com/ros-planning/moveit2/pull/392

Thank you @rhaschke for showing me this pre-commit tool.  This is really awesome and makes formatting checking much nicer and easier on both the user and the CI infrastructure.

### CODE REVIEW

**Comment by tylerjw** [comment]
One awesome thing to see is how fast this runs on GitHub Actions.  This whole test takes 37 seconds on the moveit2 repo: https://github.com/ros-planning/moveit2/pull/392/checks?check_run_id=2156925519

It won't run here until after this is part of the repo.

**Review by rhaschke — COMMENTED** [review]
What about removing the clang-format job from Travis?
Lots of formatting changes, of course. I'm trusting `black` on these.

**Comment by tylerjw** [comment]
> What about removing the clang-format job from Travis?

Last night I discovered that GitHub's aggressive backoffs don't seem to be a thing anymore (I queued a bunch of moveit2 CI runs in my fork at once and it just kept starting them regarless of how long they took).  Also, with a fresh ccache, full runs without clang-tidy were taking ~11min.  Without ccache they take about 45min.  That's still considerably faster than travis.

As a result I think there are basically two features I need to figure out to move moveit/moveit2 to github actions with industrial_ci and be at full feature parity.

* *code coverage* (there is a PR to industrial_ci that adds this feature that I've been testing and I'm not sure it is working).  Until it is merged I think I can make a bash script out of what we have already in moveit_ci and put that in a .ci.upload_ccov script.
* *clang-tidy*  The way clang-tidy works in industrial_ci it runs over everything in the target repo.  This, on GitHub Actions takes about 2hrs to complete.  In moveit_ci we have a script to filter the runs based on what files have changed.  I'm going to try to adapt those to a standalone script (similar to my approach to the codecov feature).  If I do these two things we can try using GitHub Actions for all our CI with one basically uniform setup everywhere.

**Comment by tylerjw** [comment]
> Lots of formatting changes, of course. I'm trusting `black` on these.

Yes, black is responsible for most of those.  I really like the idea of having a clang-format for python.  It seems like it could make our python uniform like our c++ code is.

**Comment by rhaschke** [comment]
> Also, with a fresh ccache, full runs without clang-tidy were taking ~11min. Without ccache they take about 45min.

Awesome!

**Comment by tylerjw** [comment]
closing as this change was included in the migration pr

**Pull request closed without merging**
