### PR TITLE
Add error message on failure to load occupancy map monitor

### PR DESCRIPTION
**Pull request by Dale-Koenig**
### Description

Output an error message if the Occupancy map monitor fails to find the `sensors` parameter namespace with a list of sensors.  The current behavior is for the occupancy map monitor to silently not load.

### CODE REVIEW

**Comment by Dale-Koenig** [comment]
> lgtm, except it would be nice if that error was named so it was easier to find what file the error came from. Other errors in this source file aren't named so feel free to ignore that.

I'd be happy to namespace all the messages but it was unclear to me whether there was a reason for not namespacing them.  It seems a lot of the different move group capabilities are only namespaced up to something fairly generic like "manipulation", "ros_moveit_planning", or in this case "ros_moveit_perception"

**Comment by Dale-Koenig** [comment]
@rhaschke Let me know if you would want all the logging namespaced

**Comment by rhaschke** [comment]
Yes, please introduce a logger namespace, following our new policy.
It's common practice to augment missing logger namespaces as soon as somebody touches a source file, where it is still missing. Thanks in advance.

**Comment by rhaschke** [comment]
Great that you took the effort to provide logging scopes for _all_ these files. As this goes far beyond the original scope of this PR, I suggest to file a separate PR for your last commit and we merge the first part as is. Please use `const static` variables for those logging names.

**Comment by Dale-Koenig** [comment]
> Great that you took the effort to provide logging scopes for _all_ these files. As this goes far beyond the original scope of this PR, I suggest to file a separate PR for your last commit and we merge the first part as is. Please use `const static` variables for those logging names.

Figured I already had the search replace setup in my IDE :)

I reverted and force pushed.  I can rebase + make a logging PR then after this is merged.

**Pull request merged**
