### PR TITLE
Prepare 1.1.3 for Noetic

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

@nbbrooks @v4hn here is the patch release of some of the latest features for noetic to make sure they get in with the next release.  Please merge this using the rebase or squash option once it is ready and make sure the commit message is just 1.1.3.

### CODE REVIEW

**Comment by v4hn** [comment]
It doesn't make much sense to handle the release commit like that unless we have a code freeze while it's open.
There have already been two new commits since you created the commit, so this PR shouldn't be merged anymore like that.
I believe traditionally these release commits [were pushed directly](https://moveit.ros.org/documentation/contributing/releases/), but I guess you don't have the permissions to do that and @rhaschke reviewed and merged them quickly?

As we agreed not to spend work on the Changelogs anymore (and not review them critically), I would be happy with adding you to the `MoveIt Admin` team, so you can push such commits directly (and adjust CI settings next time that becomes relevant). However, I believe @davetcoleman is likely the only one in the MoveIt group who can add people to this team.

**Comment by tylerjw** [comment]
> As we agreed not to spend work on the Changelogs anymore (and not review them critically), I would be happy with adding you to the `MoveIt Admin` team, so you can push such commits directly (and adjust CI settings next time that becomes relevant). However, I believe @davetcoleman is likely the only one in the MoveIt group who can add people to this team.

Last time I asked for that I got told that Dave would like to keep that to less people.  I can understand that though.

**Comment by tylerjw** [comment]
I'll remake this PR today and ask for reviews from people at picknik so I can merge it quickly.

**Comment by rhaschke** [comment]
@tylerjw I will handle this PR now.

**Comment by rhaschke** [comment]
Done. @tylerjw, could you continue with blooming, please?

**Comment by tylerjw** [comment]
will do... i'll run the pre-release test first

**Comment by tylerjw** [comment]
https://github.com/ros-planning/moveit/runs/2468712193?check_suite_focus=true

**Comment by rhaschke** [comment]
`GHA: no space left on device`
I think, we shouldn't restore ccache and apply your cleanup. I will prepare a corresponding PR.

**Comment by rhaschke** [comment]
New prerelease test running [here](https://github.com/ubi-agni/moveit/actions/runs/797030672).

**Comment by v4hn** [comment]
> Last time I asked for [admin access] I got told that Dave would like to keep that to less people.

Makes a lot of sense, as long as everyone who needs it has it.
I'm not convinced some of the current members actually make use of it at all and you shouldn't rely on me or Robert being available.

@rhaschke: I love the additional rst linter :-)

**Pull request closed without merging**
