### PR TITLE
Add moveit_tutorials to CI build

### PR DESCRIPTION
**Pull request by davetcoleman**
- Panda must also be added because not released yet

Not sure if this will build yet, depends if Franka has released to melodic their other stuff

### CODE REVIEW

**Comment by davetcoleman** [comment]
Second attempt of https://github.com/ros-planning/moveit/pull/1094

**Comment by rhaschke** [comment]
`franka_description` is missing now

**Comment by davetcoleman** [comment]
Already working on it :-)
https://github.com/frankaemika/franka_ros/issues/34#issuecomment-430903870

**Comment by davetcoleman** [comment]
ping @rhaschke panda_description is now available in melodic

**Comment by rhaschke** [comment]
@davetcoleman Can I prepare a release of `panda_moveit_config`?

**Comment by davetcoleman** [comment]
Let's move that convo here:

**Pull request merged**
