### PR TITLE
PlanExecution: Reset preempt_requested_ when entering executeAndMonitor()

### PR DESCRIPTION
**Pull request by rhaschke**
So far, `executeAndMonitor()` was only called via `planAndExecuteHelper()`, which was resetting the `preempt_requested_` flag:
https://github.com/ros-planning/moveit/blob/f85db808303cb7787320dc48162eabdc07593fdc/moveit_ros/planning/plan_execution/src/plan_execution.cpp#L164

However, this should also work if the function is called directly.
Fixes https://github.com/ros-planning/moveit_task_constructor/issues/217.

### CODE REVIEW

**Comment by rhaschke** [comment]
There is a small drawback of this change: If a `planAndExecute` call (going through the helper function) is preempted just between checking for the flag and calling the `executeAndMonitor()` function, the preemption signal will be essentially lost:
https://github.com/ros-planning/moveit/blob/f85db808303cb7787320dc48162eabdc07593fdc/moveit_ros/planning/plan_execution/src/plan_execution.cpp#L220-L224

**Review by felixvd — COMMENTED** [review]
I don't think it will be dangerous, but it doesn't seem to be best practice to overwrite the flag. Losing a stop signal like this would be a very confusing bug. What about an input parameter like `bool initialize_preempt_flag` for executeAndMonitor, so the helper function can call `executeAndMonitor` as before?

**Comment by rhaschke** [comment]
Yeah, I thought about that solution as well. Thanks for (independently) supporting this idea, which of course breaks ABI.
I committed an appropriate change.

**Review by felixvd — APPROVED** [review]
I would rather break API than introduce a potential time bomb :)

**Comment by rhaschke** [comment]
Closing and reopening to trigger Travis.

**Comment by rhaschke** [comment]
Closing in favor of #2554.

**Pull request closed without merging**
