### PR TITLE
Fix Kinetic clang format

### PR DESCRIPTION
**Pull request by davetcoleman**
This is similar to @v4hn's https://github.com/ros-planning/moveit/pull/344 except it only upgrades us to 3.8 since that is still included in Ubuntu Trusty (ROS Indigo/Jade) but 3.9 is not 

I had to apply some new settings to keep the formatting almost the same, still there are some changes that despite an hour of searching I could not figure out how to disable. Also included are some formatting fixes that were evidently a bug in 3.6:

Added:
```
SortIncludes: false
SpaceAfterCStyleCast: false
BreakBeforeBraces: Custom
BraceWrapping: {
    AfterClass: 'true'
    AfterControlStatement: 'true'
    AfterEnum : 'true'
    AfterFunction : 'true'
    AfterNamespace : 'true'
    AfterStruct : 'true'
    AfterUnion : 'true'
    BeforeCatch : 'true'
    BeforeElse : 'true'
    IndentBraces : 'false'
}
```

In addition, this PR fixes a bug in our current setup as pointed out by @bmagyar [here](https://github.com/ros-planning/moveit/pull/362#issuecomment-261018958) that pointer/reference symbol alignment to the variable type is inconsistent - sometimes it is aligned to the variable name instead of type. Upon investigation I discovered it is because we had the setting ``DerivePointerBinding: true`` - meaning:

> If true, analyze the formatted file for the most common binding and use PointerBindsToType only as fallback.

I've disabled this so that all pointers are aligned to type. This is not explicitly specified in the ROSCpp style guidelines and according to the Google [style guidelines](https://google.github.io/styleguide/cppguide.html#Pointer_and_Reference_Expressions) it does not matter which you use, but looking at ros_comm they use the standard of [type aligned](https://github.com/ros/ros_comm/blob/kinetic-devel/clients/roscpp/include/ros/publisher.h#L63) which I prefer. I think we should be consistent throughout MoveIt!.

@rbbg @v4hn

### CODE REVIEW

**Comment by davetcoleman** [comment]
Note: Travis will fail for clang-format test until I upgrade ``moveit_ci``, which I'll do after we discuss/confirm this PR

- [ ] Update version of clang-format for moveit_ci
- [ ] Update version of clang-format on moveit.ros.org

**Comment by davetcoleman** [comment]
ping - any thoughts on this?

**Comment by davetcoleman** [comment]
I will merge all three PRs once I verify the moveit_ci one is working

**Comment by davetcoleman** [comment]
I have just re-run clang-format 3.8 on the latest repo and am ready to merge this when CI passes

**Comment by v4hn** [comment]
@davetcoleman I assume we should also upgrade the indigo and jade branches?
Are you going to do that?

**Comment by davetcoleman** [comment]
Yes 
https://github.com/ros-planning/moveit/pull/403
https://github.com/ros-planning/moveit/pull/404

**Pull request merged**
