### PR TITLE
Clang tidy

### PR DESCRIPTION
**Pull request by RoboticsYY**
### Description

In [moveit#28](https://github.com/ros-planning/moveit/issues/28) @BryceStevenWilley proposed a clang-tidy road-map which mainly contains two steps: make the clang-tidy fix to the entire MoveIt! codebase and enable the clang-tidy in travis_ci. @rhaschke solved the second step in [moveit_ci#45](https://github.com/ros-planning/moveit_ci/pull/45). This PR targets the first step. Since clang-tidy sometimes may report false positive fixes, each change may need careful check which makes code review time-consuming. So I think maybe it is better to first apply these changes to `Kinetic` which is not changing very fast. If the changes are acceptable to everyone, then a following PR can be submitted to do the same thing for `Melodic`. Please also note in this PR:

- clang-tidy-3.9 is used.
- `clang-analyzer-*` is disabled as the discussion suggests in [moveit_ci#45](https://github.com/ros-planning/moveit_ci/pull/45).
- `readability-identifier-naming` checks are configured as [moveit#1338](https://github.com/ros-planning/moveit/pull/1338) suggestes.
-  All of `auto`s generated by `modernize-loop-convert` checks are manually changed according to the discussions in [moveit#880](https://github.com/ros-planning/moveit/pull/880) and practices in [moveit#990](https://github.com/ros-planning/moveit/pull/990).
- Variable names `more readable` in my own opinion are picked when doing the `readability-inconsistent-declaration-parameter-name` fixes.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

### CODE REVIEW

**Comment by rhaschke** [comment]
> So I think maybe it is better to first apply these changes to Kinetic which is not changing very fast.

Thanks a lot for your effort. I'm not yet convinced that we should apply such a huge code change both to Kinetic and Melodic. From my point of view, we should focus development to Melodic only, particularly because the melodic-branch also compiles on Kinetic. 
Please, @davetcoleman and @v4hn comment on this before anybody starts the tedious review process for this PR.
An advantage of applying those patches to both branches is that we can more easily cherry-pick between them.

> Since clang-tidy sometimes may report false positive fixes, each change may need careful check which makes code review time-consuming. 

How often did you observed false-positives? Which kind of fixes are erroneous?

**Comment by RoboticsYY** [comment]
> How often did you observed false-positives? Which kind of fixes are erroneous?

I don't think I met false positives very often. I met risky changes mostly from:
1. `modernize-use-nullptr` may falsely change `0` to `pullptr`. 
2. `readability-simplify-boolean-expr` may falsely change `if(...){...return...}...return...` to `return ...`, but some code between the `if` and the last `return` cannot be ignored. 
3. `readability-identifier-naming`, `modernize-loop-convert` and `readability-inconsistent-declaration-parameter-name` with or without manual fix may change a variable name to falsely override a variable with the same name.
4. `modernize-loop-convert` may make false fixes to the container like type, that has different return values from iterator and `[]` operator.

**Comment by davetcoleman** [comment]
> From my point of view, we should focus development to Melodic only, particularly because the melodic-branch also compiles on Kinetic.

I strongly agree with this. Effort spent on Kinetic seems wasted.

**Comment by RoboticsYY** [comment]
@davetcoleman @rhaschke I will submit a new clang-tidy PR for Melodic.

**Comment by RoboticsYY** [comment]
@davetcoleman I agree that this PR is so big for review. Each of `readability-identifier-naming`, `modernize-loop-convert` and `readability-inconsistent-declaration-parameter-name` can bring many changes. Some of the changes may be risky and require careful check. Maybe it's better to submit individual PR for each of them, and another PR for the rest clang-tidy checks, this will make review easier and reduce the risk of big changes to the API.

**Pull request closed without merging**
