### PR TITLE
Clean up another typo in perception CMakeLists.txt

### LINKED ISSUE #943: Regression: DepthImageOctomapUpdater was removed from debs
### Description

The depth image octomap updater stopped working in the newest released moveit version. The error message is:

```
[ERROR] [1528466140.174800759]: Exception while loading octomap updater 'occupancy_map_monitor/DepthImageOctomapUpdater': Could not find library corresponding to plugin occupancy_map_monitor/DepthImageOctomapUpdater. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
```

This is a regression in moveit_ros_perception 0.9.12 (released yesterday, 2018-06-07). The files `libmoveit_depth_image_octomap_updater.so` etc. are not contained in the released debs any more.
Here is the diff:

```
#### 0.9.11

/opt/ros/kinetic/lib/libmoveit_depth_image_octomap_updater.so
/opt/ros/kinetic/lib/libmoveit_depth_image_octomap_updater.so.0.9.11
/opt/ros/kinetic/lib/libmoveit_depth_image_octomap_updater_core.so
/opt/ros/kinetic/lib/libmoveit_depth_image_octomap_updater_core.so.0.9.11
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater.so
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater.so.0.9.11
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater_core.so
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater_core.so.0.9.11

#### 0.9.12

/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater.so
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater.so.0.9.12
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater_core.so
/opt/ros/kinetic/lib/libmoveit_pointcloud_octomap_updater_core.so.0.9.12
```

After looking through the commit history, commit 8609bde776a9d86a12f67ea16e750ab2b54339a6 (from PR #698) seems to be the one that broke the build.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04, normal x86_64 laptop
* Source or Binary build? binary
* If binary, which release version? 0.9.12

### PR DESCRIPTION
**Pull request by mintar**
This fixes #943 .

### CODE REVIEW

**Comment by MohmadAyman** [comment]
it does build with me with this fix.

**Comment by davetcoleman** [comment]
It says 24 failures but there are no other details for some reason!?

> build/moveit_ros_perception/test_results/moveit_ros_perception/gtest-mesh_filter_test.xml: 24 tests, 0 errors, 24 failures, 0 skipped

**Comment by mintar** [comment]
You have to expand the log section above. catkin_test_results only gives you the summary, catkin run_tests gives you the details.

**Comment by mintar** [comment]
@davetcoleman @v4hn Let me know if there's anything you need from me to get this merged.

**Comment by v4hn** [comment]
Sorry for not replying earlier @mintar.

Well, you are very welcome to figure out why exactly the tests fail and provide a patch to fix them...
I know your request is seemingly unrelated, but I would like to have CI succeed before merging.

I started looking into this two days ago, but got stuck at https://github.com/ros-planning/moveit/pull/958 which triggered yet another discussion... *sigh*

**Comment by mintar** [comment]
Could we please merge this before the next release? It fixes a clear regression, and the longer it stays open, the more people will be affected.

**Comment by rhaschke** [comment]
Seems like Mesa's OpenGL is broken. Switching to nvidia-OpenGL, the tests pass flawlessly.
However, we can't do this on Travis. I will disable this test for now (in a separate PR).

**Pull request merged**
