### PR TITLE
Added support for PS4 joystick

### PR DESCRIPTION
**Pull request by TrippleBender**
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by TrippleBender** [comment]
I added support for the PS4 Controller. Also added a description in the tutorial

**Comment by simonschmeisser** [comment]
Thanks for your first PR! This is how we move it! ;)

Please note that the text that is there when you open the PR is meant as a template, so please click edit and exchange `Please explain the changes you made, including a reference to the related issue if applicable` by a description of what you want to change and why. You later wrote that in a comment but it's to find and parse this way.

Also, next time, when you write `Also added a description in the tutorial` please add a link to the PR for the tutorial

**Comment by simonschmeisser** [comment]
In an ideal world I would prefer it if this code would not guess the type of input device from the number of buttons but that does not seem to be exposed by this very spartan msg api, so LGTM

**Comment by v4hn** [comment]
> In an ideal world I would prefer it if this code would not guess the type of input device from the number of buttons but that does not seem to be exposed by this very spartan msg api, so LGTM

You could try to convince `joy` upstream to add the device id (Best case also unique between multiple devices) as `frame_id`. That's pretty much what I would expect from the field in this message.

**Comment by v4hn** [comment]
Merging with two approvals.

**Pull request merged**
