### PR TITLE
using LOGNAME variable rather than strings for logging

### PR DESCRIPTION
**Pull request by mlautman**
### Description
Using `name_` variable for logging rather than `"robot_state"`

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Include a screenshot if changing a GUI
- [ ] Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [x] Decide if this should be cherry-picked to other current ROS branches
- [ ] While waiting for someone to review your request, please consider reviewing [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mlautman** [comment]
@rhaschke I'm not sure that declaring the variable outside the class would work. In this case `name_` is used in both `robot_state.h` and `.cpp` so we would have to declare the string in the `.h`. This results in redefinition errors if we have multiple classes that share namespace as is the case with `moveit_core`. Philosophically, I don't see the rational for keeping this data outside of the class in a shared namespace as this variable is being used by the class to relay to the logger it's identity. While  `planning_scene_monitor` uses `LOGNAME`, it is the only one that does so. Since  `trajectory_execution_manager` uses `name_`, I see these as equally valid. `name_` seems better to me because it implies the name of the class whereas `logname_` implies the name of the logger. (Also, since it is a member variable, it would need to be [lower case](http://wiki.ros.org/CppStyleGuide#Static_class_variables))

**Comment by rhaschke** [comment]
The single use case in `.h` I would move into `.cpp` indeed. There is no reason for this function to be inline.
But my key point is that the `name_` member suggests that a RobotState instance can be named. The `LOGNAME` variable will much better emphasize the usage of this variable.

**Comment by davetcoleman** [comment]
I agree with @rhaschke's point that the ``name_`` of a ``RobotState`` would lead me to expect "panda" or "pr2" for example. 

I also agree that there shouldn't be function code in the ``.h`` file and that should be moved. ``inline`` is not necessary with modern compilers.

Perhaps ``CLASSNAME`` would be best, but I don't like the two extra characters so agree with ``LOGNAME``

Please document this new "standard" on the *Contributing* page:
http://moveit.ros.org/documentation/contributing/code/

**Comment by mlautman** [comment]
@rhaschke Requested changes made. I also made the same formatting change to `robot_model.cpp` and `robot_state/conversions.cpp`.

**Pull request merged**
