### PR TITLE
Prepare 1.1.2

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

This is changelogs for 1.1.2 to be released on Noetic.

### CODE REVIEW

**Review by jschleicher — APPROVED** [review]
Great to see the next release finally happen :-)

**Comment by rhaschke** [comment]
I will have a look immediately.

**Review by rhaschke — APPROVED** [review]

**Comment by rhaschke** [comment]
I merged and pushed the tag. @tylerjw, are you going to continue with blooming?

**Comment by tylerjw** [comment]
> I merged and pushed the tag. @tylerjw, are you going to continue with blooming?

I will do it now.

**Comment by tylerjw** [comment]
@rhaschke can you push a fast-forward onto the `noetic-devel` branch?

**Comment by rhaschke** [comment]
Done. I also rebase and force-pushed `docker-master` to build the new `master-source` docker image from latest master.

**Comment by tylerjw** [comment]
https://github.com/ros/rosdistro/pull/29063

**Comment by rhaschke** [comment]
@tylerjw, the ROS buildfarm is failing: https://build.ros.org/job/Ndev_db__moveit__debian_buster_amd64/21/display/redirect
Looks like, `moveit_msgs` is not released yet. Indeed the [status page](http://repositories.ros.org/status_page/ros_noetic_default.html) still lists `0.11.1` as most recent. 
The failure suggests that you didn't do a prerelease test. `industrial_ci` provides the possibility to perform a pre-release test. My suggestion is to trigger this manually on github via [`workflow_dispatch`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events).

**Pull request merged**
