### PR TITLE
Disables copying of attached collision objects when updating start state

### PR DESCRIPTION
**Pull request by TSNoble**
### Description

#3569 describes propagation of error from updating collision objects with each update of the start state during a sequence motion plan.

#3589 attempts to speed up plans by updating only joints positions when updating the start state, though this may cause the RobotState to ignore collision objects entirely if the state being updated has no knowledge of them.

This PR attempts to fix both issues by only updating the joints of a sequence motion, without copying across attached collision objects, in the hope that the start state being updated is already populated with attached collision object information.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/) (No major changes to user-facing functionality)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes (Changes implementation details / fixes error cases)
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html) (See findings below)
- [x] Include a screenshot if changing a GUI (No GUI changes)
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by TSNoble** [comment]
I'm unsure if [this](https://github.com/ros-planning/moveit/blob/e1093080ffee55e7a53f222438c5c0d75d4b4368/moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp#L224-L249) method will be loading the entire scene (objects and all) at the start of the sequence. If not, it might face the same issue as #3589 

If this is the case, perhaps it would make sense to add an `update_attached_objects` flag to `setStartState` which can be called once with `true` at the start of the sequence, then with `false` for each subsequent item?

**Comment by TSNoble** [comment]
If desired, I can try to write some tests which demonstrate the issue described in #3569, which should hopefully pass with this PR

**Review by rhaschke — COMMENTED** [review]
This might be a reasonable change. I need to verify in which contexts `CommandListManager::setStartState` is called.

**Comment by rhaschke** [comment]
> I'm unsure if [this](https://github.com/ros-planning/moveit/blob/e1093080ffee55e7a53f222438c5c0d75d4b4368/moveit_planners/pilz_industrial_motion_planner/src/command_list_manager.cpp#L224-L249) method will be loading the entire robot state (objects and all) at the start of the sequence.

Yes, the initial `start_state` is loaded as is, i.e. clearing existing attached objects if the diff flag is set, otherwise just adding new ones.

**Comment by rr-tom-noble** [comment]
Thanks for taking a look. Submitted this via my personal account, so will try to make those changes & get a test reproducing the issue tonight

**Comment by rr-tom-noble** [comment]
Some findings:

I tried to reproduce the pose error issue on master. Many paths planned fine (no deviation at all), but I was able to reproduce the error consistently with some paths. @rr-mark suspects it may be occurring as a result of performing matrix inversions as part of the msg <-> object conversion process near robot singularities.

I logged the poses of every attached collision object associated with the `start_state` at each point inside the `MotionPlanInfo` constructor:

[unfixed.csv](https://github.com/ros-planning/moveit/files/15131991/unfixed.csv)

Some observations:

- Only "ee5" and "tb_5_1" are attached to the end of the joint group we are planning for.
- We are planning with respect to a subframe defined on "tb_5_1".
- "tb_5_1" shows pose variation, whereas "ee5" does not, despite them both being attached to the end of the robot.
- Only the rotational component of "tb_5_1" appears to accumulate error. The position seems fine.
- The full path attempted contains 425 points. The planner fails to find an IK solution after point 28.

unfixed_position

unfixed_quaternion

I ran the same process over the same path using the changes proposed in this branch, which appear to fix the issue. The pose shows no deviation, and all 425 points plan successfully:

[fixed.csv](https://github.com/ros-planning/moveit/files/15132104/fixed.csv)

fixed_position

fixed_quaternion

I'm not familiar with with the robots available to the pilz unit tests. Given the hard-to-reproduce nature of the issue, which may be somewhat dependent on knowledge of where the singularities lie, I'm not confident I can easily write an automated test for this error case (at least it'd be a big time sink).

I'm pretty confident the issue is fixed, given both that the changes imply the attached collision objects of will never be updated within a sequence motion, and the experimental evidence.

@rhaschke 

Would you be happy to merge this PR without tests, given the above?

**Review by rhaschke — APPROVED** [review]

**Pull request merged**
