### PR TITLE
Rebase master

### PR DESCRIPTION
**Pull request by j-petit**
This is a rebase on master for the bullet feature branch.

### CODE REVIEW

**Comment by j-petit** [comment]
Yes, would be nice to merge. The feature branch isn't merged because we need to deal with the fact that the Bullet version coming through apt on 16.04 is too old. I made a PR to adapt cmake for this, see #1744. When this one is merged, we can merge the feature branch.

**Comment by davetcoleman** [comment]
It won't let me do a 'Rebase and merge'

> This branch cannot be rebased due to conflicts
> Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

I'm not sure, but is a regular 'merge' ok then?

**Comment by nbbrooks** [comment]
If I'm understanding the role of this PR correctly, then I think we should just abandon this PR. Jens, is this PR/your fork's rebase-master branch is just to sync the ros-planning feature branch with master and handle resulting conflicts? If so, then we should forget about the ros-planning feature branch and just merge the feature into master from Jens' fork.

Dave can't rebase and merge because Jens' fork's feature branch is more up to date than the ros-planning feature branch and there is a merge conflict (probably between the feature commits in the ros-planning branch and the newer master commits that Jens' branch has but the ros-planning branch does not). And Jens doesn't have write access to ros-planning so he can't rebase the ros-planning feature branch directly (the reason for this PR). Potential solutions:
1- What I described above (simplest)
2- We use a merge commit to merge this PR into the ros-planning feature branch. So then we have a merge commit in the ros-planning feature branch history, and will potentially have another merge commit if we use a merge commit to merge this feature into master (unless we squash down the entire feature branch and try to rebase and merge)
3- If this PR contains no new features, then a maintainer can just merge it in and manually resolve any conflicts associated with the commit strategy (not an efficient use of maintainer time)

**Comment by rhaschke** [comment]
I just confirmed the rebase on `ros-planning` by force-pushing `feature-bullet-trajopt` to Jens' branch.
@j-petit, I think the only? thing that prevents this feature branch from merging into master is #1744.

**Comment by j-petit** [comment]
Sorry for the confusion, my only intent with the PR was to have `feature-bullet-trajopt` synced again to master and as I can't sync it directly (no write access) I created this PR. I am not sure why conflicts showed up though. Thanks @rhaschke for handling this!

**Comment by j-petit** [comment]
And yes, I think when #1744 is handled we can merge the feature branch!

**Comment by nbbrooks** [comment]
Thanks Robert, forgot about that option.

Jens, I think the rebase conflicts were there because the ros-planning feature branch had feature commits and your fork's branch also had those feature commits. So my guess is rebasing the feature commits individually with the rebase caused conflicts with the existing feature commits (which would explain why the merge commit strategy had no conflict).

**Comment by rhaschke** [comment]
Explanation for conflicts on github is simple: This PR was as rebase of original `feature-bullet-trajopt` branch onto master, but still targeting the (old) `feature-bullet-trajopt` branch. This naturally created conflicts. I manually force-pushed from the commandline.

**Pull request merged**
