### PR TITLE
Melodic devel

### PR DESCRIPTION
**Pull request by ValerioMa**
### Description

Fix clang compilation error in finding OpenMP reported in issue #2518

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
Sorry, but this isn't convincing to me. All these settings should be handled by `find_package(OpenMP)`. If there is a bug in `FindOpenMP.cmake`, it should be fixed there instead of providing a laborious workaround here.

How is this related to #2474? Are you working in a OSX environment?

**Comment by ValerioMa** [comment]
I close this because it is an exact duplicate of #2474 . Sorry if I didn't find it before also the proposed change is taken from the same StackOverflow post [here](https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp)

**Comment by rhaschke** [comment]
So, you are working in a OSX env as well? Does the alternative solution suggested in https://github.com/ros-planning/moveit/pull/2474#issuecomment-760106489 work?

**Comment by ValerioMa** [comment]
No I am using Clang in Ubuntu 18.04 as reported in the linked issue

**Comment by rhaschke** [comment]
In this case, I consider this PR independent. Did you try to install `libomp-dev` as suggested [here](https://askubuntu.com/questions/900702/how-to-compiler-openmp-program-using-clang)?

**Comment by ValerioMa** [comment]
`apt-get --reinstall libomp-dev` fixed my problem thanks for helping me!

**Pull request closed without merging**
