### PR TITLE
WIP: Analyzing Travis failure

### PR DESCRIPTION
**Pull request by rhaschke**
Travis has failing unittests in its last job (clang + ros-shadow-fixed), while the other jobs succeed.
This is an attempt to debug and understand what's happening.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Thanks for looking into this

**Comment by rhaschke** [comment]
This list of commits shows that the culprit is the ros-shadow-fixed repository. Need to analyze further locally, because the test logs are not very helpful.

**Comment by davetcoleman** [comment]
Should we temp disable the shadow-fixed test?

**Comment by rhaschke** [comment]
This issue was introduced by https://github.com/ros/geometry2/pull/367.
See https://github.com/ros/rosdistro/pull/23469 for more references.
As a quick-fix for our Travis, I agree to disable ros-testing for now. I will do this immediately.

**Comment by davetcoleman** [comment]
Thanks again!

**Pull request closed without merging**
