### PR TITLE
Add MoveIt Task Constructor to main rosinstall, for integration testing

### PR DESCRIPTION
**Pull request by davetcoleman**
We would like to start using the MTC in all our clients, and migrate away from the difficult to use planning pipeline. See also https://github.com/ros-planning/moveit_task_constructor/pull/88

### CODE REVIEW

**Comment by rhaschke** [comment]
Dear @davetcoleman,
I appreciate that you want to use MTC in production. However, although I already approved this PR, I don't really like the idea to build MoveIt together will all downstream dependencies. While it has the advantage to notice breaking changes, usually we need to adapt those downstream packages in this case anyway.
So, integrating downstream packages just to notice API breakages, for me, is not worth the extra compilation time at Travis. Instead, we should use the ros build farm for this, which re-compiles all downstream packages after a commit to the MoveIt repo.

**Comment by rhaschke** [comment]
Closing this in favor of another approach, testing downstream packages like MTC, in Travis on their own and using the ros build farm to do cross-package API validation. See open PRs mentioned here https://github.com/ros-planning/moveit/pull/1451#issuecomment-488865664.
Feel free to re-open this PR, if you disagree.

**Comment by davetcoleman** [comment]
I think we're looking at this differently. I'd like to soon merge this into the /moveit repo and remove the never finished, poorly working [moveit_ros_manipulation](https://github.com/ros-planning/moveit/tree/master/moveit_ros/manipulation) package once we show that the same features can be fully done with the MTC

**Comment by rhaschke** [comment]
MTC is not yet ready to be merged into the main `moveit` repo and it's not yet ready to replace `moveit_ros_manipulation`. Michael had some students working on that particular topic, by I didn't get feedback on that for a while now.
Even if we get ready with some pending API changes and the ros-manipulation replacement, there is no strong need to integrate MTC into the main repo. But, I would like to do so as well.
Until then, it's completely fine to Travis-test MTC on its own.

**Comment by v4hn** [comment]
> We would like to start using the MTC in all our clients

Wow. Great to hear that. I hope to talk to @henningkayser about this a bit more in person soon.

> Even if we get ready with some pending API changes and the ros-manipulation replacement, there is no strong need to integrate MTC into the main repo. But, I would like to do so as well.

I sympathize with the first argument here because of the size of mechanisms that still should be implemented (e.g. scheduling which needs a rather big redesign), but I do not strictly oppose it.

Concerning this very pull-request:
I believe it is perfectly fine to merge for users who default to this rosinstall. They will get MTC along with everything else.
As CI uses the same file though, I rather agree with Robert in that downstream dependencies should not be added here.

**Comment by rhaschke** [comment]
Closing, as we cannot find a consensus for adding MTC.

**Pull request closed without merging**
