### PR TITLE
[kinetic] Fix CHOMP planner and CollisionDistanceField (#155)

### PR DESCRIPTION
**Pull request by davetcoleman**
Cherry-pick of https://github.com/ros-planning/moveit/pull/155

* Copy collision_distance_field package
* Resurrect chomp
* remove some old Makefiles and manifests
* Correct various errors
* Code formatting, author, description, version, etc
* Add definitions for c++11. Nested templates problem.
* Add name to planner plugin.
* Change getJointModels to getActiveJointModels.
* Call robot_state::RobotState::update in setRobotStateFromPoint.
* Create README.md
* Improve package.xml, CMake config and other changes suggested by jrgnicho.
* Remove some commented code, add scaling factors to computeTimeStampes
* Add install targets in moveit_experimental and chomp
* Add install target for headers in chomp pkgs.
* Remove unnecessary debugging ROS_INFO.
* Port collision_distance_field test to indigo.
* Remove one assertion that makes collision_distance_field test to fail.

### CODE REVIEW

**Comment by de-vri-es** [comment]
I think #215 needs to be adjusted for this. I'll see what happens locally.

**Comment by davetcoleman** [comment]
Probably.

**Comment by de-vri-es** [comment]
Locally I'm getting the error that `collision_detection::CollisionWorldDistanceField` is an abstract classes because it it not implementing some overloads of `distanceRobot` and `distanceWorld`. That seems unrelated to the `shared_ptr` changes. It looks like an API difference between indigo and kinetic?

**Comment by davetcoleman** [comment]
Fixed

**Comment by davetcoleman** [comment]
Ready to merge.

**Pull request merged**
