### PR TITLE
Add Code of Conduct; see https://www.contributor-covenant.org

### PR DESCRIPTION
**Pull request by mamoll**
I am trying to revive @mcevoyandy's [attempt to add a code of conduct to MoveIt](https://github.com/ros-planning/moveit/pull/647).

In an ideal world this wouldn't be necessary and "be reasonable" would be a sufficient code of conduct. That is not the world we live in, unfortunately. This code of conduct is a strong signal that we want to create a welcoming community for contributors where new ideas will be discussed in a constructive manner. That seems like an idea that everyone should be able to get behind, but I'd be happy to discuss this at the next MoveIt maintainer meeting.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Do we have any examples of situations where we feel a code of conduct would have helped?

I'm not against this per se, but adding it just for the sake of adding it doesn't seem like something I'd support.

**Comment by v4hn** [comment]
I still stand by [my comment on the original request](https://github.com/ros-planning/moveit/pull/647#issuecomment-337343645).

Recently, it has been pointed out to me that the explicit presence of a COC might influence potential sponsors for MoveIt-related projects, which might be enough of a reason to add it to the repository.

But again, I believe this needs the agreement of a maintainer meeting (in contrast to the usual 2x:+1: policy).

**Comment by gavanderhoorn** [comment]
@v4hn wrote:
> Recently, it has been pointed out to me that the explicit presence of a COC might influence potential sponsors for MoveIt-related projects, which might be enough of a reason to add it to the repository.

Really? Is this an actual (documented?) fact, or a hypothetical / hearsay?

Tbh I quite agree with https://github.com/ros-planning/moveit/pull/647#issuecomment-337343645: it saddens me that somehow people feel that we now need to write down what should by all means be reasonable to assume.

@mamoll wrote:
> In an ideal world this wouldn't be necessary and "be reasonable" would be a sufficient code of conduct. That is not the world we live in, unfortunately.

Do we expect the MoveIt community (including the maintainers) unable to maintain this "be reasonable" attitude? Adding a coc could also be viewed as a community admitting that apparently it cannot follow normal, expected ettiquete and behave as normal human beings and that they need to introduce some sort of contract to enforce this.

Personally I have not witnessed any behaviour in the MoveIt community (or the larger ROS community) that would seem to warrant adding a coc, but I'm obviously limited in both my perception of those communities and it may not be a strong argument against it.

**Comment by v4hn** [comment]
> Really? Is this an actual (documented?) fact, or a hypothetical / hearsay?

For me it's hearsay, but the idea seems valid enough to me to mention it here.
After all there are enough organizations out there that pledge to support goals included in standard COCs.

Just to clarify, nobody disagrees with anything essential in the proposed conduct.
The main argument against the request is "Why would we write that down?".

**Comment by mamoll** [comment]
@v4hn wrote:

> The main argument against the request is "Why would we write that down?".

It is not so much a reaction against “bad” behavior within the MoveIt community in the past. Rather, it's a signal to people *outside* of the MoveIt community, welcoming them in. Of course, this can be pushed too far. I'm not suggesting that anyone who creates a PR is now a winner of a participation award.

**Comment by mamoll** [comment]
Per the maintainer meeting, people are generally on board with this (although some have some reservations). LGTM.

**Comment by gavanderhoorn** [comment]
I'd like to have it on record that it goes without saying that I'm not *against* the general idea that is encoded in the document (although I still feel it should go without saying that we behave like normal, responsible and rational adults).

What I do have a problem with is the language in the *Responsibilities* and *Enforcement*, as that language seems to imply that maintainers should now also become policemen next to their other duties.

If we don't believe we'll ever run into situations where such policing would be necessary, as was brought up in the maintainer meeting several times, then that begs the question whether we need this document, or at least whether we need the two sections I mentioned above.

**Comment by mamoll** [comment]
Yes, let me work on rephrasing this code of conduct and tone down the language about enforcement & policing. Thanks for your feedback.

**Comment by mamoll** [comment]
@gavanderhoorn I looked at some other code of conduct statements, and I actually like to the Google one better. It's adapted from the one I had originally. It changes the section about enforcement to conflict resolution. I have made @davetcoleman the project steward (the person that should be contacted if people can't resolve a conflict themselves), but that is open for debate.

Re. responsibilities, is there specific language you'd like to see removed/rephrased?

**Comment by davetcoleman** [comment]
Let's remove the conflict resolution / enforcement stuff that is the greatest cause of concern. But I don't like the idea of going down the path of us writing our own CoC, seems like a waste of time. According to the Open Source Guide "Wherever you can, use prior art."

Github's page on [CoC](https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project) recommended the [Open Source Guide](https://opensource.guide/code-of-conduct/). One of the examples from it is from [Django's](https://www.djangoproject.com/conduct/). I like their CoC, and its based on Fedora's and Python's. So a good lineage.

I like that the first bullet point is simply "Be friendly and patient." Overall the document doesn't read too [angsty](https://www.merriam-webster.com/dictionary/angsty).

**Comment by mamoll** [comment]
Let me push another commit with the Django CoC, updated for MoveIt.

**Pull request closed without merging**
