### PR TITLE
update dependencies for python3 in noetic

### PR DESCRIPTION
**Pull request by mikeferguson**
### Description

This updates some packages to package.xml format 3 and sets up Python3 dependencies for noetic. It requires https://github.com/ros/rosdistro/pull/25263 to be merged before the new python3-pyassimp key will be available.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code) (N/A - all package.xml changes)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/) - also N/A
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by mikeferguson** [comment]
This also handles the fact that orocos_kdl is now a system dependency (rather than a ROS package)

**Comment by rhaschke** [comment]
Merge blocked by https://github.com/ros/rosdistro/pull/25263, which is required for catkin_lint to succeed.

**Comment by mikeferguson** [comment]
pyassimp key has been merged to rosdistro -retriggered the CI

**Comment by v4hn** [comment]
Thanks for taking the time @mikeferguson :+1:

**Pull request merged**
