### PR TITLE
cherry-pick #94 from kinetic-devel: execute action capability

### PR DESCRIPTION
**Pull request by rhaschke**
Cherry picked #94 from Kinetic, but removed deprecation warnings as agreed in https://github.com/ros-planning/moveit_msgs/pull/27#issuecomment-241218455.

### CODE REVIEW

**Comment by v4hn** [comment]
I'll review this, but I'm way to busy this week, so I'm not exactly sure when I will get around to do it..

**Comment by davetcoleman** [comment]
LGTM - this PR has been reviewed so many times!

**Comment by v4hn** [comment]
On Wed, Aug 24, 2016 at 10:01:56AM -0700, Dave Coleman wrote:
> LGTM - this PR has been reviewed so many times!

So did you test it on indigo and check ABI compatibility?

**Comment by davetcoleman** [comment]
> So did you test it on indigo and check ABI compatibility?

I did not, which is why I did not give a +1. You said you'd review it but I gave it a quick read through and was just surprised to see the same old code I've read several times now

**Comment by rhaschke** [comment]
@v4hn: ping.

**Comment by v4hn** [comment]
On Thu, Sep 08, 2016 at 11:43:02PM -0700, Robert Haschke wrote:
> @v4hn: ping.

pong, I'll try to do this next week (though I hate to make such statements in request threads...).

**Comment by davetcoleman** [comment]
ping :-)

**Comment by 130s** [comment]
ping ping :)

**Comment by davetcoleman** [comment]
Note this PR needs to merge in this fix that has already been applied to Jade/Kinetic: https://github.com/ros-planning/moveit/pull/335#issuecomment-258640292

**Comment by rhaschke** [comment]
Rebased to indigo-devel (recent commits there introduced some conflicts). Cherry-picked #335 as suggested by @davetcoleman. I don't have an Indigo system around anymore, so @v4hn can you please finally validate this PR?

**Comment by v4hn** [comment]
Ok, just looked through this once more.
It seems quite likely to me that #335 fixed issue #201 and this leaves no open issues with the patch.
Merging.

Thanks a lot @rhaschke and @davetcoleman !

**Comment by davetcoleman** [comment]
hurray, finally!

**Pull request merged**
