### PR TITLE
get object.pose from new msg field

### PR DESCRIPTION
**Pull request by gautz**
### Description

See https://github.com/ros-planning/moveit/issues/2875

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by gautz** [comment]
@felixvd is there a need to overload to be able to get the `mesh_poses`, `primitive_poses`, `plane_poses` or `subframe_poses`?

**Review by v4hn — APPROVED** [review]
Obvious oversight in @felixvd's pose patch. Thank you for the fixup!

If you want to avoid breakage in this interface in the future, consider contributing a test for it :)

**Comment by simonschmeisser** [comment]
LifeHack: If you write "closes #2875" or "fixes #2875" the corresponding issue will automagically be closed when the PR gets merged

**Comment by v4hn** [comment]
actually I just failed to notice the issue when I merged. thanks for cleaning up 👍

**Pull request merged**
