### PR TITLE
Fix crash if no window_context exists

### PR DESCRIPTION
**Pull request by simonschmeisser**
#491 introduced a regression:

In TrajectoryVisualization::onInitialize the existance of a window_context is checked and the trajectory_slider_panel_ and trajectory_slider_dock_panel_ are only created if it exists.
However later on these two pointers are assumed to be valid (non-NULL) and not checked any further.

### CODE REVIEW

**Comment by v4hn** [comment]
hey @simonschmeisser,

did you encounter this segfault or is this patch preventive?
I believe @Jntzko implemented this similar to other parts of the moveit plugins.
I'm waiting for his response first.

**Comment by simonschmeisser** [comment]
@v4hn we do encounter a crash when it tries to set the title of the non-existent panel. We use several rviz::Display and one rviz::PropertyTreeWithHelp in our application but don't have a central rviz window and thus the window_context == nullptr

**Comment by v4hn** [comment]
@davetcoleman, @130s please review/merge.
@Jntzko also found a similar situation in the motion planning rviz plugin and will probably create a similar pull request for it later today.

**Comment by Jntzko** [comment]
The related pull request is #525.

**Comment by 130s** [comment]
I'm not sure how to reproduce the issue. Assuming from the comment https://github.com/ros-planning/moveit/pull/523#issuecomment-308098540 by @simonschmeisser, it can only be replicated from source code (I don't know on RViz GUI how to set a title on a non-existent panel)? So I leave the decision up to others.

**Comment by v4hn** [comment]
merging. We want to have this regression-fix in the next release.

**Comment by v4hn** [comment]
cherry-picked to i/j

**Pull request merged**
