### PR TITLE
[indigo] cherry-pick #585 (ikfast yields collision-free solutions, if available)

### PR DESCRIPTION
**Pull request by v4hn**
As @130s noticed [in the original thread](https://github.com/ros-planning/moveit/pull/585#issuecomment-350485379) this did not yet get cherry-picked to indigo-devel.

Just as with #575, this has to be tested by someone on indigo before we can merge it.

### CODE REVIEW

**Comment by v4hn** [comment]
Format checking fails for this request, but it asks for something impossible:
In C++03 `X<X<A>>` is not a valid type specification. The additional space `X<X<A> >` is mandatory to properly resolve the context.

@davetcoleman Can we change our format description in `indigo-devel` to account for this?

**Comment by davetcoleman** [comment]
Done: https://github.com/ros-planning/moveit/pull/813

**Comment by davetcoleman** [comment]
Just attempted to fix https://github.com/ros-planning/moveit/pull/813

**Comment by rhaschke** [comment]
Merged #813.

**Comment by v4hn** [comment]
I rebased this, but the mesh filter test (totally unrelated) fails.

We recently did our "last planned" indigo release, so I will close this unmerged.
If anyone still needs this, please comment below.

**Pull request closed without merging**
