### PR TITLE
Memory leak hot fix for mesh filter

### PR DESCRIPTION
**Pull request by berkealgul**
### Description

According [this issue](https://github.com/ros-planning/moveit/issues/3364) there is memory leak from mesh filter. I hotfixed the problem according to the issue

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
Thanks for your initiative. While your solution fixes the memory leak, it defeats the original idea of the code:  `data` was declared `static` here to avoid frequent memory allocation and deallocation, which is rather costly.

**Comment by rhaschke** [comment]
I just noticed that `data_size` was never adjusted, thus rendering this optimization idea pointless. Another issue with static storage is missing thread safety. Thus one should drop the static storage...

**Comment by rhaschke** [comment]
Instead of optimizing memory usage, one might try to optimize the scaling operation using `Eigen`...

**Comment by rhaschke** [comment]
Ideally, one would not need data copying and scaling at all and just pass the original float data...

**Comment by rhaschke** [comment]
I don't have a depth camera available to test. Please @berkealgul and @luorui93 test and review, particularly https://github.com/ros-planning/moveit/pull/3371/commits/f64ceb51cd2eee5319176f4cba7a269f9604121f and https://github.com/ros-planning/moveit/pull/3371/commits/b7b062a58e29903718f64a02f868c93e3eb9a807.

**Comment by luorui93** [comment]
> I don't have a depth camera available to test. Please @berkealgul and @luorui93 test and review, particularly [f64ceb5](https://github.com/ros-planning/moveit/commit/f64ceb51cd2eee5319176f4cba7a269f9604121f) and [b7b062a](https://github.com/ros-planning/moveit/commit/b7b062a58e29903718f64a02f868c93e3eb9a807).

Thanks! I'll test these changes and get back you asap.

**Review by luorui93 — APPROVED** [review]
Tested on my machine and no memory leak was found.

**Comment by rhaschke** [comment]
@luorui93, thanks for testing. Did you test both listed commits? Is there any difference? I'm not sure, why/whether the scaling by factor 1000 was needed...

**Comment by rhaschke** [comment]
I'm confused now: b7b062a doesn't comprise the scaling by factor 1000, but you report it works as expected.
On the other hand, you state omitting the scaling makes the filter fail... I guess that's only happening if you _also_ use the conversion from `float` to `uint`?

**Comment by rhaschke** [comment]
@luorui93, please file a new issue regarding the failing depth filter for a real RealSense camera. Particularly, please provide a rosbag file and your MoveIt sensor config to reproduce the issue. Thanks.

**Comment by luorui93** [comment]
> @luorui93, please file a new issue regarding the failing depth filter for a real RealSense camera. Particularly, please provide a rosbag file and your MoveIt sensor config to reproduce the issue. Thanks.

Sure, I actually managed to fix the issue so I'll also send a pull request too probably. However I didn't use any moveit sensor config file (actaully I only used the mesh filter as a separate tool without any other moveit components), would you mind telling me what's the config file you are referring to? It's possible that this "moveit sensor config" could solve the issue already.

**Comment by rhaschke** [comment]
If you already identified and fixed the bug, that's even better. I was referring to this [yaml config](https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html#yaml-configuration-file-point-cloud).

**Comment by luorui93** [comment]
I see, then the config file should not affect whether the issue occurs or not. I'll post an issue along with a pull request.
.

**Pull request merged**
