### PR TITLE
GHA: Add pre-release job

### PR DESCRIPTION
**Pull request by rhaschke**
Fixes #2595.

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
looks like this should work, this will be really convenient for testing the pre-release tests.

**Comment by tylerjw** [comment]
Maybe it would make sense to put this in a separate yaml file?  I don't care either way though.

**Comment by rhaschke** [comment]
> Maybe it would make sense to put this in a separate yaml file?

I agree. Obviously, it's not possible to trigger a single job from a workflow.

**Comment by rhaschke** [comment]
Weird, I was struggling with the correct naming of the pre-release job: It wasn't using the `matrix.distro` name.
Looks like this is only considered if the job isn't skipped. I enabled the job temporarily now to test the pre-release test.

**Comment by rhaschke** [comment]
The pre-release test can now be triggered manually:
image

Here is an example run: https://github.com/ros-planning/moveit/actions/runs/735321782

**Comment by v4hn** [comment]
Thank you so much @rhaschke !
This simplifies life a lot.
The only issue I see is that the logs for the test are so long that it's basically impossible to scroll to the actual error in the dynamically-loading web view. Downloading the raw logs works perfectly though.

**Pull request merged**
