### PR TITLE
[jog_arm] Move and rename to moveit_ros/moveit_servo

### PR DESCRIPTION
**Pull request by AdamPettinger**
### Description

This moves the `moveit_experimental/jog_arm` package and renames it `moveit_ros/moveit_servo` @AndyZe. There is already an open PR for ROS2 ([https://github.com/ros-planning/moveit2/pull/223](https://github.com/ros-planning/moveit2/pull/223)) with some discussion.

@tylerjw will help with migration notes through the name change as well as his big recent PR #2103. 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by AndyZe** [comment]
I tested it and did a quick verification that "jog" and "Jog" don't appear anywhere (except message types, which we can't change here). Looks good! Approved if you remove that last commit, like Henning pointed out.

**Comment by AdamPettinger** [comment]
>  b48460b shouldn't be included here, though

Just to clarify @henningkayser, you want me to leave the COLCON_IGNORE file here in the ROS1 package?

**Comment by henningkayser** [comment]
> > [b48460b](https://github.com/ros-planning/moveit/commit/b48460b1418d8a7c73257d0afd445b1a014720a4) shouldn't be included here, though
> 
> Just to clarify @henningkayser, you want me to leave the COLCON_IGNORE file here in the ROS1 package?

No, the commits shouldn't include COLCON_IGNORE at all. This repo doesn't include this file so there should be no need to remove it.

**Comment by AndyZe** [comment]
I think once these commits all get squashed it won't matter, then...

**Comment by AdamPettinger** [comment]
> > > [b48460b](https://github.com/ros-planning/moveit/commit/b48460b1418d8a7c73257d0afd445b1a014720a4) shouldn't be included here, though
> > 
> > 
> > Just to clarify @henningkayser, you want me to leave the COLCON_IGNORE file here in the ROS1 package?
> 
> No, the commits shouldn't include COLCON_IGNORE at all. This repo doesn't include this file so there should be no need to remove it.

One of my earlier commits added it (first done in moveit2), and I removed it at the end. I think Andy is right and squashing these commits together would result in it never being here. If we are going to squash before merging anyway, I think leaving it is ok. Otherwise I can fix the commit that added it, and remove the final commit

**Comment by AdamPettinger** [comment]
I removed the COLCON_IGNORE from these commits

**Comment by henningkayser** [comment]
> > > > [b48460b](https://github.com/ros-planning/moveit/commit/b48460b1418d8a7c73257d0afd445b1a014720a4) shouldn't be included here, though
> > > 
> > > 
> > > Just to clarify @henningkayser, you want me to leave the COLCON_IGNORE file here in the ROS1 package?
> > 
> > 
> > No, the commits shouldn't include COLCON_IGNORE at all. This repo doesn't include this file so there should be no need to remove it.
> 
> One of my earlier commits added it (first done in moveit2), and I removed it at the end. I think Andy is right and squashing these commits together would result in it never being here. If we are going to squash before merging anyway, I think leaving it is ok. Otherwise I can fix the commit that added it, and remove the final commit

The commit history is a good documentation here, I would also keep it probably.

**Comment by rhaschke** [comment]
IMHO we should try to avoid merging PRs like this as a merge-commit and instead squash-merge them. For example, this one has many closely-related commits and some cleanup commits:
￼
* Move moveit_experimental/moveit_jog_arm -> moveit_ros/moveit_jog_arm
* Rename filepath moveit_ros/moveit_jog_arm -> moveit_ros/moveit_servo

...
* Rename internal namespaces and package/project name to moveit_servo
* Internal rename interface class JogArm to Servo
* Internal rename JOG_ARM_STATUS_CODE_MAP to SERVO_STATUS_CODE_MAP
* Internal rename jog_server to servo_server
* Rename a bunch of internals
* Internal rename JogCalcs -> ServoCalcs
* Rename servo_calcs internals

...
* Clang formatting

@tylerjw: As I have seen several such commits from your side recently (e.g. also #2103), please carefully balance a clean vs. detailed history in future. Sometimes, of course, it is important and useful to keep individual commits of a PR and perform a proper merge. In these cases, (request to) cleanup the PR commit history before merging. Examples are unrelated commits (e.g. backports) in a single PR. However, as a rule of thumb, our guidelines state that a single PR should only tackle a single "problem" and thus all related commits should be squash-merged by default (see [GitHub Merge Policies](https://moveit.ros.org//documentation/contributing/pullrequests/)).

**Comment by felixvd** [comment]
Thanks for mentioning it, I was close to bringing it up, too. #2162 in particular is very long (54 commits, 15 for renaming, two identical commits one after the other). I would actually support force-pushing a clean version to melodic-devel in this case because it's so large.

**Pull request merged**
