### PR TITLE
Shift catkin_lint to pre-commit checks

### LINKED ISSUE #2566: Run catkin_lint in pre-commit
I started trying to do this and I'm not sure it is possible because of how pre-commit works.  My understanding is that pre-commit runs per-file and that because catkin_lint runs over directories it won't work.

It would however be really nice if this worked this way because then you could get an error from pre-commit much quicker than from the full CI system.

### PR DESCRIPTION
**Pull request by rhaschke**
Fixes #2566 (hopefully). Works locally. The key was, I think, `pass_filenames: false`.

### CODE REVIEW

**Review by tylerjw — COMMENTED** [review]
This creates a ton of errors for me locally, also it runs very slow compared to the other checks when ran with `pre-commit run -a`:

```
- hook id: catkin_lint
- exit code: 1

catkin_lint: downloading noetic package index from https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
catkin_lint: downloading package manifest for 'moveit_resources_pr2_description'
catkin_lint: downloading package manifest for 'moveit_resources_panda_moveit_config'
catkin_lint: downloading package manifest for 'moveit_resources_fanuc_moveit_config'
catkin_lint: downloading package manifest for 'moveit_resources_panda_description'
catkin_lint: downloading package manifest for 'moveit_resources_fanuc_description'
moveit_commander: warning: file 'demos/plan_with_constraints.py' is executable but not installed
moveit_commander: warning: file 'demos/pick.py' is executable but not installed
moveit_commander: warning: file 'demos/plan.py' is executable but not installed
moveit_core: CMakeLists.txt: warning: target 'robot_state_benchmark' is not installed
moveit_kinematics: CMakeLists.txt(32): warning: exported package include path but no exported library
moveit_ros_planning: CMakeLists.txt: warning: target 'demo_scene' is not installed
moveit_ros_planning: CMakeLists.txt: warning: target 'moveit_compare_collision_checking_speed_fcl_bullet' is not installed
moveit_ros_planning: launch/collision_checker_compare.launch(5): warning: launch configuration needs exec_depend on 'moveit_resources_panda_description'
moveit_ros_planning: launch/collision_checker_compare.launch(7): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_ros_planning: launch/collision_checker_compare.launch(10): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_ros_planning: launch/collision_checker_compare.launch(14): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_ros_planning_interface: CMakeLists.txt: warning: target 'demo' is not installed
moveit_ros_visualization: warning: file 'rviz_plugin_render_tools/src/octomap_render.cpp' is executable but not installed
moveit_ros_warehouse: warning: file 'warehouse/src/import_from_text.cpp' is executable but not installed
moveit_ros_warehouse: warning: file 'warehouse/src/db_path_config.py' is executable but not installed
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/default_warehouse_db.launch(13): warning: launch configuration needs exec_depend on 'moveit_ros_warehouse'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo.launch(32): warning: launch configuration needs exec_depend on 'joint_state_publisher'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo.launch(35): warning: launch configuration needs exec_depend on 'joint_state_publisher_gui'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo.launch(40): warning: launch configuration needs exec_depend on 'robot_state_publisher'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo_gazebo.launch(41): warning: launch configuration needs exec_depend on 'joint_state_publisher'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo_gazebo.launch(45): warning: launch configuration needs exec_depend on 'joint_state_publisher_gui'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/demo_gazebo.launch(51): warning: launch configuration needs exec_depend on 'robot_state_publisher'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/gazebo.launch(8): warning: launch configuration needs exec_depend on 'gazebo_ros'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/gazebo.launch(19): warning: launch configuration needs exec_depend on 'gazebo_ros'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/joystick_control.launch(7): warning: launch configuration needs exec_depend on 'joy'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/move_group.launch(86): warning: launch configuration needs exec_depend on 'moveit_ros_move_group'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/planning_context.launch: warning: parse error: error parsing attribute name, line 9, column 77 (<string>, line 9)
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/ros_controllers.launch(9): warning: launch configuration needs exec_depend on 'controller_manager'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_ompl.launch(17): warning: launch configuration needs exec_depend on 'moveit_ros_benchmarks'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch(7): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch(12): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch(17): warning: launch configuration needs exec_depend on 'moveit_ros_benchmarks'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch(18): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/run_benchmark_trajopt.launch(19): warning: launch configuration needs exec_depend on 'moveit_resources_panda_moveit_config'
moveit_setup_assistant: templates/moveit_config_pkg_template/launch/warehouse.launch(10): warning: launch configuration needs exec_depend on 'warehouse_ros_mongo'
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_pg70_support'
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_support'
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_moveit_config'
catkin_lint: checked 29 packages and found 38 problems
catkin_lint: option -W2 will show 324 additional notices
catkin_lint: 3 messages have been ignored. Use --show-ignored to see them
```

**Comment by tylerjw** [comment]
I don't know what to do about source dependencies like these:

```
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_pg70_support'
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_support'
pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_moveit_config'
```

**Comment by tylerjw** [comment]
It looks like it is passing in the Action.  Did I do something wrong when I tried it locally?  I'm on noetic on 20.04.

**Comment by tylerjw** [comment]
> I don't know what to do about source dependencies like these:
> 
> ```
> pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_pg70_support'
> pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_support'
> pilz_industrial_motion_planner: package.xml: error: unknown package 'moveit_resources_prbt_moveit_config'
> ```
> 
> The rest of them can probably be fixed.

**Comment by tylerjw** [comment]
Sorry, didn't mean to close this :facepalm:

**Comment by rhaschke** [comment]
I had the same issue: locally it fails, while it succeeds on CI. Explanation is as follows: `catkin_lint` knows to operation modes: with and without `ROS_DISTRO` defined. If not defined, it cannot check for package dependencies...
As we don't run it remotely in a ROS environment, we don't see issues. Locally we do. I will try to configure rosdep as well.
It's strange that `industrial_ci` doesn't complain when running `catkin_lint`...

**Comment by tylerjw** [comment]
> It's strange that `industrial_ci` doesn't complain when running `catkin_lint`...

I bet that's because it runs this after sourcing the upstream workspace which does define these dependencies.

**Comment by rhaschke** [comment]
I think we should hold this back until the Pilz stuff is released.

**Comment by tylerjw** [comment]
Even after we release the pills stuff if we add anything to our source dependencies that isn't released it will make this fail unless users also source an underlay workspace with our source repos when running pre-commit.  We don't do that very often so maybe it'll be fine.

**Comment by rhaschke** [comment]
Just learned about another interesting GH feature: disabling a workflow for non-relevant changes (something Dave asked for in the past): https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

**Comment by tylerjw** [comment]
So if we have a directory with docs for example, changes to that directory could rebuild the docs but not the code and vice/versa.

**Comment by rhaschke** [comment]
@tylerjw, this should be ready for review now: `catkin_lint` as part of pre-commit works.

**Comment by tylerjw** [comment]
> @tylerjw, this should be ready for review now: `catkin_lint` as part of pre-commit works.

My only worry about merging this is that this will fail if we ever add a package like the pilz robot descriptions that we haven't released yet.  I tested locally though and it does work which is nice.

**Review by tylerjw — APPROVED** [review]

**Pull request merged**
