### PR TITLE
jog_arm: add missing license

### PR DESCRIPTION
**Pull request by AndyZe**
Add the missing license, as pointed out in #1716

### CODE REVIEW

**Comment by AndyZe** [comment]
I accidentally deleted the source repo because I forgot this PR was still open.  :(

**Comment by jonbinney** [comment]
@AndyZe might be easiest to re-fork and just copy over the text from the one file.

**Comment by davetcoleman** [comment]
Agreed it'd be best to keep the license format standard, using /* */

**Comment by AndyZe** [comment]
Closing in favor of #1764

**Pull request closed without merging**
