### PR TITLE
python move_group interface: allow setting of targets from any iterable

### PR DESCRIPTION
**Pull request by rhaschke**
The python MoveGroup interface only allowed to set joint targets from lists, dicts, and some special data structures. This PR

* allows to pass any iterable to `move_group.set_joint_value_target()`, particularly `numpy` arrays.
* adds a corresponding unittest
* adds a unittest for https://github.com/ros-planning/moveit_commander/issues/15.
  This fails due to an upstream bug: https://github.com/ros/ros_comm/pull/871

### CODE REVIEW

**Comment by davetcoleman** [comment]
Travis says the branch is missing?

I skimmed the changes and it looks alright, but I'm not a python person

**Comment by rhaschke** [comment]
> Travis says the branch is missing?

I accidentally pushed my branch to ros-planning first instead of by own fork, which caused Travis to start building. The PR build succeeded.

**Comment by v4hn** [comment]
The changes look nice and good to me, but I can't run the test cases over here.
@rhaschke Could you rebase this request against upstream to retrigger CI please?
If they pass, please also file these requests against jade and indigo.
Once CI passed for all of them, I'll merge the requests.

**Comment by rhaschke** [comment]
Rebase succeeded, PRs opened for indigo (#199) and jade (#198)

**Pull request merged**
