### PR TITLE
use correct install destination of headers

### PR DESCRIPTION
**Pull request by v4hn**
This installed to `include/moveit_ros_planning/moveit/...` before.

Needs to be picked to j/k

### CODE REVIEW

**Comment by rhaschke** [comment]
+1

**Comment by rhaschke** [comment]
Cherry-picked into J/K

**Comment by 130s** [comment]
Could any of you teach me why we need this change? My guess is as follows:

[From Catkin's doc](http://docs.ros.org/kinetic/api/catkin/html/user_guide/variables.html):

> **CATKIN_GLOBAL_INCLUDE_DESTINATION**
> This is set to include. This destination should only be used when installing headers which are not in a subfolder which matches the project name. Else you should use the destination CATKIN_PACKAGE_INCLUDE_DESTINATION instead.

Now it seems to me the subfolder name in question [`moveit_ros/planning/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin`](https://github.com/ros-planning/moveit/tree/09c014d200a6d9b43fc378148738b5f0fc30b2a5/moveit_ros/planning/lma_kinematics_plugin/include/moveit/lma_kinematics_plugin) does NOT match the package name `moveit_ros_planning` (defined in `planning` folder). Is this the reason?

If I missed a previous discussion, I'm sorry...

**Comment by v4hn** [comment]
MoveIt uses *one* folder for all headers from all of its modules: "include/moveit".
This is rather non-standard for catkin and catkin would prefer to have headers of each
ROS package in a separate folder, e.g. `include/moveit_core/...`, `include/moveit_ros_planning/...`, ...
The `lma_kinematics_plugin/include` folder currently contains (just as all other modules)
a "moveit" folder that is installed.

Now if we use `CATKIN_PACKAGE_INCLUDE_DESTINATION`, the installed headers would reside in `include/moveit_ros_planning/moveit/lma_kinematics_plugin/`.
So to install all moveit headers from our packages to `include/moveit/` instead, we have to install to `${CATKIN_GLOBAL_INCLUDE_DESTINATION}/moveit`.
Because the moveit folder is already present in the respective `include` folders of each package, we have to install *the content* of `<moveit_package>/include/` to `${CATKIN_GLOBAL_INCLUDE_DESTINATION}`.

**Pull request merged**
