### PR TITLE
Missing RViz dependency in MSA template

### PR DESCRIPTION
**Pull request by DLu**
### Description

Adds a missing dependency on RViz to the MSA template. If not, the package will fail roslaunch checks if they are added. 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by DLu** [comment]
I also think `moveit_simple_controller_manager` should have a dependency here. Can add it if this is approved.

**Comment by rhaschke** [comment]
> I also think `moveit_simple_controller_manager` should have a dependency here. Can add it if this is approved.

Yes, this as well as `moveit_fake_controller_manager` is needed.

**Comment by DLu** [comment]
[`moveit_fake_controller_manager` is already there](https://github.com/ros-planning/moveit/blob/00aca0c90e6cea9fd7fd723e411753be9e4c31e2/moveit_setup_assistant/templates/moveit_config_pkg_template/package.xml.template#L20)

**Review by rhaschke — APPROVED** [review]

**Comment by DLu** [comment]
Good to merge then?

**Review by JafarAbdi — APPROVED** [review]

**Pull request merged**
