### PR TITLE
Updated First Timers Only Issue Template #2413

### PR DESCRIPTION
**Pull request by harshgupta246**
### Description

Fixed the first_timers_only.md as instructed in Issue #2413 

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
Thank you for doing this.  It looks good.  Do you have any feedback on the process?  Was there anything you found confusing?  I'll merge this after travis passes.

**Comment by tylerjw** [comment]
For some reason travis didn't get triggered on this.  I'm going to close and re-open this PR to get travis to run.

**Comment by harshgupta246** [comment]
> 
> 
> Thank you for doing this. It looks good. Do you have any feedback on the process? Was there anything you found confusing? I'll merge this after travis passes.

The most confusing part was to find out how to ping someone. I still don't know if making a comment on a Github issue is the correct way to simply open up a conversation or whether it is reserved for a technical discussion regarding the issue.

The process was easy and simple as it had everything given to me and being new to open source, it is a big thing to even get an issue that I could work on.

Thanks for doing this, I learnt alot.

**Comment by tylerjw** [comment]
> The most confusing part was to find out how to ping someone. I still don't know if making a comment on a Github issue is the correct way to simply open up a conversation or whether it is reserved for a technical discussion regarding the issue.

Using an @ mention in a response to an issue or the PR works well (they get an email).  Would you mind making a new `first-timer-only` issue using the template (click new issue and it'll be one of the options) with a change to the template (the same file you edited) to make it clear to the next person who does one of these how they can ping someone?

I'm glad this worked well for you.  I hope it is now clearer how you'd make a PR here or anywhere on github.  Welcome :tada:

**Comment by harshgupta246** [comment]
> 
> 
> > The most confusing part was to find out how to ping someone. I still don't know if making a comment on a Github issue is the correct way to simply open up a conversation or whether it is reserved for a technical discussion regarding the issue.
> 
> Using an @ mention in a response to an issue or the PR works well (they get an email). Would you mind making a new `first-timer-only` issue using the template (click new issue and it'll be one of the options) with a change to the template (the same file you edited) to make it clear to the next person who does one of these how they can ping someone?
> 
> I'm glad this worked well for you. I hope it is now clearer how you'd make a PR here or anywhere on github. Welcome 🎉

I am giving it a try right now. Have some questions - 

- There are a few instructions in the template that are used to build a local workspace with this project. However, to edit the file a simple fork and clone would work. Should I edit out the template (not the actual template, just the text in the issue)

- How do I generate the supposed difference, as was generated in #2413

**Comment by tylerjw** [comment]
>     * There are a few instructions in the template that are used to build a local workspace with this project. However, to edit the file a simple fork and clone would work. Should I edit out the template (not the actual template, just the text in the issue)

I would say to leave those in for now.  Part of the `first-timer-only` issues is walking people through getting setup to make further contributions (most often code changes) and these steps help with that.

I looked over the issue and added the tag, it looks correct, thank you!

**Pull request merged**
