### PR TITLE
[indigo] Add colours to trajectory_visualisation display (backport of #362)

### PR DESCRIPTION
**Pull request by bmagyar**
### Description

Coloured trajectory visualisation (backport of #362)

### Checklist
- [x] **Required**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extended the tutorials / documentation, if necessary [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Include a screenshot if changing a GUI
- [ ] Optional: Created tests, which fail without this PR [reference](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html)
- [ ] Optional: Decide if this should be cherry-picked to other current ROS branches (Indigo, Jade, Kinetic)

Thank you!

### CODE REVIEW

**Comment by bmagyar** [comment]
screenshot from 2016-11-23 11 56 11

A quick test with PAL's TIAGo

**Comment by davetcoleman** [comment]
I don't understand why Travis didn't run its checks on this PR. This occasionally happens on Github and I haven't found a solution. Maybe because it says "@bmagyar changed the base branch to ros-planning:indigo-devel from ros-planning:kinetic-devel"?

Did you test this on an Indigo machine? If not, do you mind force pushing some kind of fake change to this PR to maybe re-trigger Travis?

**Comment by bmagyar** [comment]
Did a `git commit --amend` to update the date, seems to have done the trick! 

Of course I wouldn't push anything to Indigo that's not tested ;) 
The screenshot is from there.

**Comment by davetcoleman** [comment]
fyi for cherry-picks from other branches, I typically do not compile locally but rely on the original branch testing (kinetic for me) and the Travis CI. That might save you time :)

also looks like there was a connection error with Docker, i've restarted the build

**Comment by bmagyar** [comment]
All green now 👍

**Pull request merged**
