### PR TITLE
fix signal for planning_attempts

### PR DESCRIPTION
**Pull request by v4hn**
fixup for dfb00da5917f357f56b54db5b0e3038a3180e10a

### CODE REVIEW

**Comment by simonschmeisser** [comment]
Did we drop Qt4 already? Then this could be checked at compile time by using modern style connects

**Comment by rhaschke** [comment]
Is there a nice tool available to upgrade all connects?

**Comment by simonschmeisser** [comment]
https://github.com/KDE/clazy can do that

**Comment by v4hn** [comment]
> Did we drop Qt4 already? Then this could be checked at compile time by using modern style connects

Yes we can upgrade the slot connects, I just wanted to keep the old style consistent and did not want to spend even more time on refactoring for now.

Pull-requests that ran automatic tools and upgrade the format are clearly appreciated :sunglasses:

**Pull request merged**
