### PR TITLE
Helper function that accepts JointModelGroup*

### PR DESCRIPTION
**Pull request by davetcoleman**

### CODE REVIEW

**Comment by rhaschke** [comment]
Do we really need this function? Why can't you call ->getName() from where you are calling?
I think this is cluttering the API.

**Comment by davetcoleman** [comment]
Its questionable. I know @isucan was converting all the API to used JointModelGroup pointers to improve performance, but in this case there is no performance gain because there is a message be populated on the other side of this function with strings. But in my mind all of the moveit API should be consistent and accept the same type of input (JointModelGroup pointers) as found [everywhere else](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_core/robot_state/include/moveit/robot_state/robot_state.h#L571) in the code base

**Comment by davetcoleman** [comment]
ping

**Comment by v4hn** [comment]
Oh, I thought I responded to this? Weird...

:-1: from my side.
I agree that consistant API is a good thing.
But with this patch you would just introduce an interface that takes a pointer, assumes validity and dereferences it and calls a different interface. That does not make any sense at all.
This would just further hide the underlying mechanism that *does* require the name.

**Comment by davetcoleman** [comment]
I concede defeat, but just to point out:

> assumes validity

Assuming the validity of a JointModelGroup pointer is everywhere in the MoveIt code.

> calls a different interface

This is also common throughout MoveIt - all moveit's ROS messages convert classes and ptrs to strings

**Comment by v4hn** [comment]
> This is also common throughout MoveIt - all moveit's ROS messages convert classes and ptrs to strings

Yes, but usually it's (or should be) the other way around. :)

**Pull request closed without merging**
