### PR TITLE
Updated the First Timers Only Issue Template 

### PR DESCRIPTION
**Pull request by rjtsingh**
updated   .github/ISSUE_TEMPLATE/first_timer_only.md 

Added -

💬️ - You can even ping us by using an `@ mention` in the comments.

### CODE REVIEW

**Comment by rjtsingh** [comment]
Done

**Comment by simonschmeisser** [comment]
Please explain **what** is *done* in the commit message and the PR title

**Comment by simonschmeisser** [comment]
Also this seems to be based on a first timers issue, so please add "fixes #NUMBER OF ISSUE " in the PR description

**Review by simonschmeisser — CHANGES_REQUESTED** [review]
needs info about **what** has been done

**Comment by rjtsingh** [comment]
> needs info about **what** has been done

Updated the First Timers Only Issue Template #2424

**Comment by simonschmeisser** [comment]
Please reread carefully what I wrote, you actually need to use the word "fixes" before the issue to have github close the issue after this has been merged. Also you should find the edit button to edit the title and description of this PR.

**Comment by simonschmeisser** [comment]
ok, 1/3 done, now you also need to replace the text below "Description" where it currently says: Please explain the changes you made, including a reference to the related issue if applicable

and finally the title of your commit should also be more descriptive than "done", you can read up on "git interactive rebase" or "git ament" to find out how to change the commit description. The commit is the actually important part here as it will stay in the code forever

**Review by tylerjw — APPROVED** [review]
lgtm

**Review by felixvd — CHANGES_REQUESTED** [review]
- Git commit messages and issue titles should be in present tense
- The issue needs to say "Fixes #xxx" so Github automatically fixes the issue, as @simonschmeisser said
- The issue description is not very helpful. Could you be more detailed?

**Comment by v4hn** [comment]
@felixvd I don't see what needs to be addressed from your "chage requested" review.
There is a difference between "holding a firsttimer's hand" and "bikeshedding until they leave". :smile_cat: 

I think this should just be merged.

**Comment by simonschmeisser** [comment]
@v4hn the commit titel is "done" ...

**Review by JafarAbdi — APPROVED** [review]

**Comment by JafarAbdi** [comment]
> @v4hn the commit titel is "done" ...

It can be changed in the `squash & merge` option

**Comment by simonschmeisser** [comment]
I just wonder what's the point of these "first timer issues" if we provide the diff and do not require candidates to provide a valid PR ... but wasting time bike sheding this is probably the worst possible outcome

**Comment by felixvd** [comment]
> @felixvd I don't see what needs to be addressed from your "change requested" review.

Normally I wouldn't bother, but I figured that these first-timer issues are about form and how to submit a good PR rather than the content (since it's provided), so skipping over good form/submission style makes the exercise seem pointless. We should discuss what we expect these issues to achieve, maybe in #2421.

Also, I changed my mind about this PR, it should just be closed. The original issue #2424 was assigned to @Prakhar030 who already submitted #2427, so his should be the one to be merged.

**Comment by v4hn** [comment]
@tylerjw @felixvd you said in the maintainer meeting you want to give up on the first timer project.
Could you decide what to do with this patch?

**Comment by felixvd** [comment]
Yes, I have decided to close this and merge #2427.

**Pull request closed without merging**
