### PR TITLE
registrer exit command

### PR DESCRIPTION
**Pull request by k-okada**
workaround for https://github.com/ros-planning/moveit_commander/issues/15, registrer exit command
see https://github.com/ros-planning/moveit_commander/pull/46#issuecomment-241496778 for discussion

### CODE REVIEW

**Comment by rhaschke** [comment]
This issue originates from `ros_comm`: ros/ros_comm#871.
Doing os._exit(0) avoids any cleanup and always returns with success code 0. I think in case of true exceptions, that's not what we want. According to my investigation, it might be useful to trigger ros.shutdown() on exit.
-1

**Comment by k-okada** [comment]
that's interesting, 
https://github.com/ros-planning/moveit_commander/pull/46#issuecomment-236128030
reports that the problem occurs in indgo, but not in jade. and  https://github.com/ros/ros_comm/pull/871 is targeting to the kinect.

**Comment by v4hn** [comment]
@rhaschke Yes this is a bug in ros_comm, but it also is a drastic usability problem in the MoveIt python interfaces.
I do not believe your fix in ros_comm - if accepted at all - will make it into indigo, because it changes quite a bit.
Do you see a way to fix this in our scripts instead?

I do believe even the current patch would improve the current state of the python wrappers quite a lot. (always 0 is much better than always segfault)

**Comment by rhaschke** [comment]
The fix is merged in Kinetic. I agree, that they might not merge into Indigo soon. However, I asked (https://github.com/ros/ros_comm/pull/871#issuecomment-245833915).
If there is the strong wish to hotfix this in MoveIt Commander, we should do it. However, simultaneously, we should open a new issue, to remove the hack again as soon as ros_comm is fixed.

**Comment by v4hn** [comment]
Wow, I didn't expect them to merge it that fast. Thanks a lot @rhaschke !
Closing this now - either this will be fixed in kinetic onward or they even get around to backport this to indigo. We'll see.

**Pull request closed without merging**
