### PR TITLE
[jade] Making the moveit release-ready

### PR DESCRIPTION
**Pull request by 130s**
@v4hn https://github.com/ros-planning/moveit/issues/22#issuecomment-241199671 Ok, I agree we should have released DEBs ready on WMD (even from shadow-fixed repo), and time is running out, so I have to go radical.
- Remove moveit_ikfast for now (see https://github.com/ros-planning/moveit/issues/22#issuecomment-241199671).
- More Manual adjustment of package.xml versions to 0.8.3 for the packages that aren't going to be released, but I still do this since I'm afraid `bloom` might complain if there's mismatching versions.

### CODE REVIEW

**Comment by rhaschke** [comment]
Removing and re-adding a whole sub-tree isn't ideal. Could we instead of merging this into the jade-devel branch, have simply a release tag pushed to the repo with this commit?

```
| \ current jade-devel
|  \  - release tag with this commit
| ...
| jade-devel will continue here, without the need to re-add the sub-tree
```

**Comment by 130s** [comment]
> Removing and re-adding a whole sub-tree isn't ideal. 

I almost understand what you're saying, but in actuality, how bad is it?

> Could we instead of merging this into the jade-devel branch, have simply a release tag pushed to the repo with this commit?

I experimented it in my personal repo, and seems to be possible (i.e. the `tag`ged tarball on the remote did contain the change I made locally, without being pushed to the remote).

I still don't know how `bloom` reacts to this, but I'll try. Closing this PR.

**Comment by 130s** [comment]
Re-opening this PR.
Tried but still `bloom` is looking into `moveit_ikfast` package, which indicates that bloom fetches source code from repository, not from `tag`ged tarball where moveit_ikfast is not included in.

```
$ bloom-release --rosdistro jade --track jade moveit
:
==> git-bloom-release jade
Processing release track settings for 'jade'
Checking upstream devel branch for package.xml(s)
Cloning into '/tmp/tmpiYGoFJ/upstream'...
remote: Counting objects: 57709, done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 57709 (delta 36), reused 0 (delta 0), pack-reused 57615
Receiving objects: 100% (57709/57709), 49.54 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (30248/30248), done.
Checking connectivity... done.
Looking for packages in 'jade-devel' branch... found 23 packages.
Traceback (most recent call last):
  File "/usr/bin/git-bloom-release", line 9, in <module>
    load_entry_point('bloom==0.5.21', 'console_scripts', 'git-bloom-release')()
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/release.py", line 353, in main
    args.unsafe)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/release.py", line 247, in execute_track
    settings = process_track_settings(track_dict, release_inc)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/release.py", line 192, in process_track_settings
    track_dict['ros_distro'])
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/release.py", line 145, in find_version_from_upstream
    meta = get_upstream_meta(upstream_repo.get_path(), ros_distro)
  File "/usr/lib/python2.7/dist-packages/bloom/commands/git/release.py", line 120, in get_upstream_meta
    name, version, packages = get_package_data(current_branch, quiet=False, release_directory=directory)
  File "/usr/lib/python2.7/dist-packages/bloom/packages.py", line 91, in get_package_data
    version = verify_equal_package_versions(packages.values())
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 127, in verify_equal_package_versions
    raise RuntimeError('Two packages have different version numbers (%s != %s):\n- %s\n- %s' % (package.version, version, package.filename, packages[0].filename))
RuntimeError: Two packages have different version numbers (3.2.0 != 0.8.2):
- /tmp/tmpiYGoFJ/upstream/moveit_ikfast/package.xml
- /tmp/tmpiYGoFJ/upstream/moveit_plugins/moveit_ros_control_interface/package.xml

Release failed, exiting.
```

**Comment by v4hn** [comment]
Too bad the workaround did not work.
Removing the `moveit_ikfast` package from this repository again is no problem because we still have the module around in a separate repository and we plan to merge it into a `moveit_kinematics_plugin` package in this repository.

Merging. @130s if you have to remove the package in `indigo-devel` too, feel free to merge yourself after the pull-request got tested, you got my +1.

**Comment by v4hn** [comment]
one more note: @rhaschke there's no need to re-add the package until https://github.com/ros-planning/moveit/issues/67 has been addressed. And afterwards the `moveit_ikfast` package will not exist anymore, but be part of `moveit_kinematics_plugins`.

Question is: should we do this in `indigo-devel` too, to keep the sources for the package all in one place? Or should we keep the https://github.com/ros-planning/moveit_ikfast.git repository for around for indigo? I'll leave this question to @jrgnicho and @gavanderhoorn (they are listed with "speciality IKFast Plugin on our )

**Comment by davetcoleman** [comment]
I'm glad we got jade out, but for future reference - could you have not just renamed moveit_ikfast's ``package.xml`` to something else so bloom did not find it?

**Comment by gavanderhoorn** [comment]
@v4hn wrote:
> one more note: @rhaschke there's no need to re-add the package until https://github.com/ros-planning/moveit/issues/67 has been addressed. And afterwards the `moveit_ikfast` package will not exist anymore, but be part of `moveit_kinematics_plugins`.

I've commented on this in #67.

**Comment by 130s** [comment]
> for future reference - could you have not just renamed moveit_ikfast's package.xml to something else so bloom did not find it?

That could work too.
This time I thought I wanted to push debs before WMD (I know it's Jade but still) so didn't want to risk (I knew time was already ticking).

**Pull request merged**
