### PR TITLE
Changes to the first_timers_only file by prakhar030

### PR DESCRIPTION
**Pull request by Prakhar030**
### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [x] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [x] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [x] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [x] Include a screenshot if changing a GUI
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
lgtm.

**Comment by tylerjw** [comment]
Travis is really slow right now.  We'll need to wait for that to finish before merging this change.

**Comment by tylerjw** [comment]
I closed and re-opened this to trigger travis to run again.

**Comment by tylerjw** [comment]
Fixes https://github.com/ros-planning/moveit/issues/2424

**Comment by tylerjw** [comment]
It seems the pick-place test is still flaky :cry: I'm going to close and re-trigger travis to see if I can get this to pass.

**Review by felixvd — APPROVED** [review]
LGTM. Next time, please describe what you did in the initial post, and link the issue that the PR fixes with a keyword like @tylerjw did, e.g. "Fixes #2424", so Github closes the connected issue when the PR is merged. 

Also, don't add your username into the commit message or PR title. You are the author of the commit and PR, so it adds no information.

**Comment by felixvd** [comment]
@Prakhar030 Please rebase this branch on master and force-push it to resolve the conflict.

**Comment by v4hn** [comment]
closed in favor of #2555

**Pull request closed without merging**
