### PR TITLE
Add badge for moveit metapackage

### PR DESCRIPTION
**Pull request by davetcoleman**
only changes README.md

### CODE REVIEW

**Comment by IanTheEngineer** [comment]
Looks good to me. 

Though, any reason the tag is failing to render? https://github.com/davetcoleman/moveit/blob/babcc4639b5e260cefed03003999a730df74ac3f/README.md
Has the metapkg been released into `indigo`?

**Comment by 130s** [comment]
+1. Merging.

>  Has the metapkg been released into indigo?

Not yet. Waiting for #100

**Comment by IanTheEngineer** [comment]
> Not yet. Waiting for #100
Gotcha. :shipit:

**Comment by v4hn** [comment]
On Tue, Aug 23, 2016 at 11:54:19AM -0700, Ian McMahon wrote:
> > Not yet. Waiting for #100
> Gotcha. :shipit: 

Naw, this will take some more time to address problems and wait for all this dust to settle...

**Comment by davetcoleman** [comment]
C-P to I/J

**Pull request merged**
