### PR TITLE
[FIX][moveit_ros_planning_interface] Install test directory so that tutorial for testing can be run

### PR DESCRIPTION
**Pull request by 130s**
At [Running Tests In MoveIt!](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/tests.html#integration-test) tutorial, the test command fails as follows. This PR fixes it.

```
$ rostest moveit_ros_planning_interface python_move_group.test
[python_move_group.test] is neither a launch file in package [moveit_ros_planning_interface] nor is [moveit_ros_planning_interface] a launch file name
$ rospack find moveit_ros_planning_interface
/opt/ros/kinetic/share/moveit_ros_planning_interface
$ ll `find /opt/ros/kinetic -iname moveit_ros_planning_interface`
/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_ros_planning_interface:
total 676K
drwxr-xr-x 189 root root  20K Jan  5 23:47 ../
drwxr-xr-x   2 root root 4.0K Jan  5 23:47 ./
lrwxrwxrwx   1 root root   37 Jan  4 21:41 _moveit_move_group_interface.so -> _moveit_move_group_interface.so.0.9.3
-rw-r--r--   1 root root 414K Jan  4 21:41 _moveit_move_group_interface.so.0.9.3
lrwxrwxrwx   1 root root   41 Jan  4 21:41 _moveit_planning_scene_interface.so -> _moveit_planning_scene_interface.so.0.9.3
-rw-r--r--   1 root root  88K Jan  4 21:41 _moveit_planning_scene_interface.so.0.9.3
lrwxrwxrwx   1 root root   32 Jan  4 21:41 _moveit_robot_interface.so -> _moveit_robot_interface.so.0.9.3
-rw-r--r--   1 root root 124K Jan  4 21:41 _moveit_robot_interface.so.0.9.3
lrwxrwxrwx   1 root root   35 Jan  4 21:41 _moveit_roscpp_initializer.so -> _moveit_roscpp_initializer.so.0.9.3
-rw-r--r--   1 root root  19K Jan  4 21:41 _moveit_roscpp_initializer.so.0.9.3
-rw-r--r--   1 root root  173 Jan  4 21:41 __init__.pyc
-rw-r--r--   1 root root    0 Nov 16 13:57 __init__.py

/opt/ros/kinetic/share/moveit_ros_planning_interface:
total 32K
drwxr-xr-x   3 root root 4.0K Jan  5 23:47 ./
drwxr-xr-x   2 root root 4.0K Jan  5 23:47 cmake/
drwxr-xr-x 379 root root  20K Nov 17 19:32 ../
-rw-r--r--   1 root root 1.8K Nov 16 13:57 package.xml
$ rosversion moveit_ros_planning_interface
0.9.3
$ lsb_release -a|grep Rele
No LSB modules are available.
Release:        16.04
```

### CODE REVIEW

**Comment by 130s** [comment]
I targeted `indigo-devel` since I wrote this on Indigo (although the test result above was done on Kinetic). Should be portable to JK too.

**Comment by v4hn** [comment]
This proposes to install a cpp source file of one of the tests (that is currently disabled) and the CMakeLists.txt of the test folder.
Could you please change it to only install `python_move_group.test` and `python_move_group.py` into a test-folder instead?
That should be enough.

**Comment by 130s** [comment]
You're right. Commit updated.
I moved the change into `test/CMakeLists.txt` because the folder is `add_subdirectory`ed so info about the resource in that folder should be handled in their CMakeLists.txt. Please correct me if this is wrong.

**Comment by v4hn** [comment]
Testing failed. I just proposed a new version of this in #415 .

**Pull request closed without merging**
