### PR TITLE
Remove ConstraintSampler::project()

### LINKED ISSUE #3159: Different planning results between c++ and python interface
### Description

Overview of your issue here.

### Your environment
* ROS Distro: [Noetic]
* OS Version: e.g. Ubuntu 20.04
* Source build from master branch

### Steps to reproduce
In rivz, using motion planning plugin to plan robot move in `z+0.05` get correct results. (**Have tried for 10 times**)
```
[ INFO] [1654768863.379805972]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1654768863.379852136]: Using planning pipeline 'ompl'
[ INFO] [1654768863.381383438]: Planner configuration 'manipulator[RRTConnect]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1654768863.381999212]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.382085290]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.382173744]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.382265368]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.393834397]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654768863.394000046]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.394359550]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.395009513]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.395179181]: ParallelPlan::solve(): Solution found by one or more threads in 0.013464 seconds
[ INFO] [1654768863.395600964]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.395681381]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.395912000]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.396021091]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.396571780]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.397003931]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.397546423]: manipulator/manipulator[RRTConnect]: Created 5 states (3 start + 2 goal)
[ INFO] [1654768863.397604034]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654768863.397793616]: ParallelPlan::solve(): Solution found by one or more threads in 0.002359 seconds
[ INFO] [1654768863.398122700]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.398200117]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654768863.399551581]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654768863.399995843]: manipulator/manipulator[RRTConnect]: Created 5 states (3 start + 2 goal)
[ INFO] [1654768863.400192984]: ParallelPlan::solve(): Solution found by one or more threads in 0.002201 seconds
[ INFO] [1654768863.403346263]: SimpleSetup: Path simplification took 0.003037 seconds and changed from 3 to 2 states

```
CleanShot 2022-06-09 at 18 01 08@2x

However, when using python interface, the results are all weird. (**Have tried for many times.**)
```python
move_group.set_planning_pipeline_id('ompl')
move_group.set_planner_id('manipulator[RRTConnect]')
move_group.set_planning_time(1.0)
move_group.set_num_planning_attempts(10)
move_group.set_max_velocity_scaling_factor(0.1)
move_group.set_max_acceleration_scaling_factor(0.1)

pose_goal = move_group.get_current_pose().pose
pose_goal.position.x = pose_goal.position.x
pose_goal.position.y = pose_goal.position.y 
pose_goal.position.z = pose_goal.position.z + 0.05
move_group.clear_pose_targets()
move_group.set_pose_target(pose_goal)
result, plan, fraction, others = move_group.plan()
```

```
[ INFO] [1654769004.327905298]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1654769004.327931945]: Using planning pipeline 'ompl'
[ INFO] [1654769004.329302351]: Planner configuration 'manipulator[RRTConnect]' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1654769004.329758681]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.329808425]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.329859890]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.329941552]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.351190517]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654769004.351274890]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654769004.351531769]: manipulator/manipulator[RRTConnect]: Created 5 states (3 start + 2 goal)
[ INFO] [1654769004.352135813]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654769004.352277536]: ParallelPlan::solve(): Solution found by one or more threads in 0.022740 seconds
[ INFO] [1654769004.352579709]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.352647052]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.352729478]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.352785743]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.354010976]: manipulator/manipulator[RRTConnect]: Created 5 states (3 start + 2 goal)
[ INFO] [1654769004.354815474]: manipulator/manipulator[RRTConnect]: Created 5 states (3 start + 2 goal)
[ INFO] [1654769004.355670929]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654769004.356622430]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654769004.356788503]: ParallelPlan::solve(): Solution found by one or more threads in 0.004378 seconds
[ INFO] [1654769004.357012408]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.357073448]: manipulator/manipulator[RRTConnect]: Starting planning with 1 states already in datastructure
[ INFO] [1654769004.358520461]: manipulator/manipulator[RRTConnect]: Created 4 states (2 start + 2 goal)
[ INFO] [1654769004.358965464]: manipulator/manipulator[RRTConnect]: Created 5 states (2 start + 3 goal)
[ INFO] [1654769004.359146759]: ParallelPlan::solve(): Solution found by one or more threads in 0.002230 seconds
[ INFO] [1654769004.376688942]: SimpleSetup: Path simplification took 0.004986 seconds and changed from 3 to 2 states
```
CleanShot 2022-06-09 at 18 03 37@2x

### PR DESCRIPTION
**Pull request by rhaschke**
As pointed out in https://github.com/ros-planning/moveit/pull/3119#issuecomment-1160397187, the difference between `project()` and `sample()` is highly subtle and non-intuitive to users. Thus, it was suggested to drop `project()` and just use `sample()`, which is implemented with this PR.
Fixes #3159. Builds on #3119.

### CODE REVIEW

**Comment by v4hn** [comment]
Given the amount of headaches this method caused by now I believe removing it is the sensible thing to do. :+1: 
Assuming CI will succeed with the fixed ikfast generator test I do approve. Please add a `MIGRATION.md` entry for the API change though.

**Comment by mamoll** [comment]
Projection takes a given state and projects it onto a subset of the config. space (e.g., the set of configurations that satisfies some constraints). Often this is done by following a gradient of a constraint function. Sometimes this is also called a retraction. Sampling a state means computing a random state. If sampling is done over an implicitly-defined constraint manifold, then sampling can use projection to turn an invalid state into a valid one. They seem like very different operations to me.

If you replace `project()` with `sample()`, you change the semantics: you no longer find state near the input argument that satisfies the constraint, but you're just sampling a completely random state.

**Comment by rhaschke** [comment]
@mamoll, the key problem is that MoveIt didn't obey this common semantics of sample and project. Looking into the code, I just found what I described in https://github.com/ros-planning/moveit/pull/3119#issuecomment-1160397187.

**Comment by mamoll** [comment]
I am confused by [this comment in PR 3119](https://github.com/ros-planning/moveit/pull/3119#issuecomment-1179556748). Doesn't this essentially show there _is_ a difference between `sample()` and `project()` (esp. in terms of path length and number of waypoints)?

**Comment by rhaschke** [comment]
As I wrote in https://github.com/ros-planning/moveit/pull/3119#issuecomment-1159696060, the difference between `project()` and `sample()` _in MoveIt_ was very subtle:
- for joint-space sampling, both methods are identical:
- for Cartesian space sampling, the only difference is that `sample()` - additionally to Cartesian space sampling, which is performed by `project()` as well, - also first samples a joint-space pose, thus triggering an IK solution that is far away from the current pose (which is usually not desired).

**Review by v4hn — APPROVED** [review]
This is a critical issue for MoveIt performance that has been pushed to users :(.
The source has been identified for over a month now.
I will merge this fix to get the expected default planner performance back.

I'm happy to discuss this further during the Maintainer Meeting if necessary.

**Pull request merged**
