### PR TITLE
checks that the joint_state field of the robot state message isn't empty

### PR DESCRIPTION
**Pull request by jrgnicho**
### Description

Addresses #496

### CODE REVIEW

**Comment by v4hn** [comment]
format checking failed.

Returning `false` here breaks the logic in `_robotStateMsgToRobotStateHelper` though, doesn't it?

**Comment by jrgnicho** [comment]
@v4hn The ```_jointStateToRobotState``` function already checked for another condition that can return false so I assume that it wouldn't break the logic in the calling function ```_robotStateMsgToRobotStateHelpe```

**Comment by v4hn** [comment]
At the moment ```_robotStateMsgToRobotStateHelper``` accepts and successfully transforms a ```RobotState`` message if ```joint_state``` is empty, but ```multi_dof_joint_state``` specifies joints.
With your patch this case would return false, right?

How about we change ```_robotStateMsgToRobotStateHelper``` to call both conversion functions only if the size of their corresponding list of joint names is nonzero?

**Comment by jrgnicho** [comment]
@v4hn I don't have a full understanding on the role of the ```multi_dof_joint_state``` field, however I thought that it was used only as a supplement to the ```joint_states``` field .  If a full robot state can be properly initialized from the ```multi_dof_joint_state``` only then I'm OK with implementing your suggested solution.

**Comment by v4hn** [comment]
I'm not sure whether some other place limits the use-case I give above, but I see no reason to limit it in this part of the code..

You know we don't have many invariants or guarantees in the upper layers of MoveIt, so it's always hard to say how something *should* be interpreted...

It would be great if you could retain the current behavior for this case :thumbsup:

**Comment by jrgnicho** [comment]
@v4hn I made the requested changes.

**Comment by v4hn** [comment]
lgtm. Format checking failed though.

**Comment by jrgnicho** [comment]
@v4hn the formatting checks out now.

**Comment by v4hn** [comment]
Thanks a lot and sorry for all the nitpicking!

Keep the good patches coming :)

**Comment by jrgnicho** [comment]
@v4hn thanks for reviewing.

**Comment by Vonstafenberg** [comment]
@v4hn Hi,
I am not sure If I applied the fix in the commit 492e881 properly, since I am still getting the Found joint states empty message. I have Moveit installed in the opt. but for this fix I downloaded the moveit core package and compiled it in my workspace. I am working with pr2 moveit_tutorials planning_scene_ros_api_tutorial

Am I suppose to compile Moveit from source in my _ws and then it would be effective ..or how ?

please elaborate

**Comment by v4hn** [comment]
The error message should *not* affect functionality of MoveIt! and should be ignored until someone had time to fix it.

**Comment by Vonstafenberg** [comment]
@v4hn yes the error message is indeed not affecting the functionality of moveit. I actually have setup a moveit configuration for an arm with the Kinetic Moveit pkg. And the move plans are executed normally. But still these errors messages are displayed. I am actually more concerned about the issue mentioned here #552. the object gets attached to the arm gripper but then does not get detached. Same case for the pr2 tutorial mentioned in #552.

I will report this bug in Moveit tutorial asap.

**Pull request merged**
