### PR TITLE
pilz: Add type for overloaded function specification

### PR DESCRIPTION
**Pull request by jspricke**
### Checklist
- [X] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)

### CODE REVIEW

**Comment by simonschmeisser** [comment]
Could you please motivate a bit why this verbosity is required?

**Comment by jspricke** [comment]
>Could you please motivate a bit why this verbosity is required?

`setJointGroupPositions` has two definitions:

```
void setJointGroupPositions(const JointModelGroup* group, const std::vector<double>& gstate)
void setJointGroupPositions(const JointModelGroup* group, const Eigen::VectorXd& values);
```

With recent versions of Eigen and gcc (Debian unstable) the compiler 
can't decide which one to use and fails.

**Review by rhaschke — APPROVED** [review]
Probably, Eigen provides initialization from brace-initializer list as well now...

**Comment by simonschmeisser** [comment]
Thanks for clarifying!

**Review by simonschmeisser — APPROVED** [review]

**Pull request merged**
