### PR TITLE
[prerelease test] Fix shell syntax

### PR DESCRIPTION
**Pull request by jspricke**
Don't use shell expansion for package names and to remove a directory tree

### CODE REVIEW

**Comment by jspricke** [comment]
Just stumbled over this while chatting with @v4hn about #2633..

**Comment by rhaschke** [comment]
I agree that we want to avoid shell expansion for debian package names. However, I think that both, `ghc*` vs `"ghc*"` trigger shell expansion, don't they? Shouldn't we use `'ghc*'`?
Regarding `/usr/local`: We want to keep `/usr/local`, but only want to remove its contents.

**Comment by jspricke** [comment]
> I agree that we want to avoid shell expansion for debian package names. However, I think that both, `ghc*` vs `"ghc*"` trigger shell expansion, don't they? Shouldn't we use `'ghc*'`?

Doesn't make a difference, both work.

> Regarding `/usr/local`: We want to keep `/usr/local`, but only want to remove its contents.

"a package must not rely on the presence or absence of files or directories in /usr/local for normal operation."
https://www.debian.org/doc/debian-policy/ch-opersys.html#site-specific-programs

Why would you need it?

**Comment by v4hn** [comment]
```
❯ mkdir a
❯ cd a
❯ touch bc
❯ ls "b*"
ls: cannot access 'b*': No such file or directory
❯ ls b*
bc
```

> Regarding /usr/local: We want to keep /usr/local, but only want to remove its contents.

We were just discussing that. If you're that fastidious, we should actually only delete `/usr/local/*/*` because the subfolders are also [part of the FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html). But in the end it shouldn't matter either way and I'd also prefer to remove `/usr/local` altogether if it's empty.

**Review by rhaschke — APPROVED** [review]
Ok, convinced. Thanks for the fixup.

**Pull request merged**
