### PR TITLE
Fix flaky test

### LINKED ISSUE #1259: Flaky unittests
Since recently, we have some flaky unittests at Travis: 

```
build/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rosunit-cleanup_tests.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="2" time="3.417"><testcase classname="__main__.CleanupTest" name="test_cpp" time="1.6308"><failure type="AssertionError">False is not true
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/root/ws_moveit/src/moveit/moveit_ros/planning_interface/test/cleanup.py", line 30, in test_cpp
    self.assertTrue(subprocess.call(cmd) == 0)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
</failure></testcase>
```

I wasn't able to reproduce this locally though. Any feedback is welcome!
Maybe it's related to #1104, using `createUniqueInstance()` for plugins.

### PR DESCRIPTION
**Pull request by rhaschke**
Fixes #1259.
The culprit was the [change in memory management of shared objects](https://github.com/ros-planning/moveit/pull/1104/commits/d0daf644d3d08ca8783d3dc588ced7479ddd9e30), deleting `tf2::Buffer` and it's associated `tf2::TransformListener` together - but unfortunately in the wrong order.

This also cleans up the corresponding unittests.

### CODE REVIEW

**Comment by v4hn** [comment]
...
Thanks for the fast fixup.

**Comment by v4hn** [comment]
As we were talking [about hot-fix releases the other day](https://github.com/ros-planning/moveit/pull/1104#issuecomment-445873038), I guess, we should do one for this?
This can trigger segfaults in existing code.

**Comment by v4hn** [comment]
> There is another severe regression, which I want to address: #1255. Any help is welcome!

As I just argued there, I think this might require additional API / a novel concept introduced to MoveIt.

I don't think we should wait for this with the fixup release.

**Comment by rhaschke** [comment]
> As I just argued there, I think this might require additional API / a novel concept introduced to MoveIt.

I don't agree.

> I don't think we should wait for this with the fixup release.

I agree. I can trigger a new release this evening.

**Pull request merged**
