### PR TITLE
Update Docker builds for Melodic/Ubuntu Bionic

### PR DESCRIPTION
**Pull request by davetcoleman**
Setup Dockerhub to build MoveIt-based Docker images for Ubuntu Bionic

https://github.com/ros-planning/moveit/issues/806

Note these will not fully build yet because there are many missing MoveIt! dependencies

Also removes all lunar builds as they are not applicable in the melodic branch - does not remove the lunar images in the kinetic branch, however.

### CODE REVIEW

**Comment by rhaschke** [comment]
Looks reasonable. How/where are the corresponding docker images built?

**Comment by davetcoleman** [comment]
I documented Docker usage a while back here: http://moveit.ros.org/install/docker/

It answers your question with the second link

**Comment by v4hn** [comment]
@davetcoleman merged this two days ago splitting `kinetic-devel` and `melodic-devel`.
Before Robert and I (possibly others) only ever fast-forwarded.

So from now on we need to take care of cherry-picks between these branches!

**Comment by davetcoleman** [comment]
@v4hn I'm not sure what you mean - this PR is not intended for ``kinetic-devel``, how does it have anything  to do with fast-forwarding?

**Comment by rhaschke** [comment]
@v4hn pointed out an important point. Actually I didn't yet merged this PR after approval for this reason.
So far kinetic-devel and melodic-devel were exactly identical and we were able to fast forward melodic-devel when kinetic-devel received commits. Now, we need to cherry-pick those changes...

**Pull request merged**
