### PR TITLE
Workaround for #1785

### PR DESCRIPTION
**Pull request by gleichdick**
### Description

Reordered tf2 header includes, workaround for #1785. Needs ros/geometry2#431 applied to geometry2 package

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the MIGRATION.md notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by v4hn** [comment]
Does this patch *require* the geometry2 pull-request or is it a workaround for it?

I'd support only the latter one.

**Comment by gleichdick** [comment]
To compile moveit with latest geometry2 melodic-devel branch, both packages need to reorder their headers (as I did in both PRs). The reason is a templated declaration (not definition) of `fromMsg()` / `toMsg()`, so `tf2::convert` picks the templated declaration instead of the correct overload (see ros/geometry2#340 for details). By reordering the overload is defined before the template declaration.
This PR should not affect compiling with the latest **packaged** geometry2 version, where ros/geometry2#367 is not applied.
This is oviously not bullet-proof, but the tf2 api has to be changed for a proper solution.

**Comment by kejxu** [comment]
> We should not rely on a specific ordering of include headers.
> If there is a bug in tf2, it should be fixed there. Hopefully @kejxu, the original author of [ros/geometry2#367](https://github.com/ros/geometry2/pull/367), can help.

thanks much for the redirection; however, would appreciate really appreciate it if there could be more info. What exactly is the bug? https://github.com/ros/geometry2/pull/367 itself did not cause any build break in tf2 right?

**Comment by kejxu** [comment]
read through https://github.com/ros/geometry2/issues/430, https://github.com/ros/geometry2/pull/431, and https://github.com/ros-planning/moveit/issues/1785. @gleichdick, thanks a lot for the amount of time and effort invested in this issue!

Agree on the conclusion that the root cause is around the use of C++ templates (https://github.com/ros-planning/moveit/issues/1785#issuecomment-559271015), and a proper fix (instead of workarounds) will be to correct those usages altogether. The objective of https://github.com/ros/geometry2/pull/367 was to fix a MSVC build error in a small yet precise change, apologies for introducing build breaks in its downstream project (moveit).

**Comment by gleichdick** [comment]
So, I proposed a solution in ros/geometry2#433, any comments are welcome :smile:

**Comment by rhaschke** [comment]
Closing here. Should be fixed via https://github.com/ros/geometry2/issues/430 or https://github.com/ros/geometry2/pull/433.

**Pull request closed without merging**
