### PR TITLE
msa collision widget: highlight collision pairs in red/green, allow keyboard selection

### PR DESCRIPTION
**Pull request by rhaschke**
replacement for #203 using a better fix for the "highlighting on selection" issue

### CODE REVIEW

**Comment by rhaschke** [comment]
Motivated by @v4hn PR, I have a student now to turn the collision widget into a proper collision matrix display. Hopefully this will facilitate input even more.

**Comment by v4hn** [comment]
Wow, I blamed it on Qt for sending the signals in less-intuitive order,
because I didn't think someone would write slot-code that ignores the arguments...
Thanks for looking into this and +1 to the patch!  :)

On Thu, Sep 15, 2016 at 12:45:42PM -0700, Robert Haschke wrote:
> I have a student now to turn the collision widget into a proper collision matrix display.
> Hopefully this will facilitate input even more.

Neat! Bonus points for allowing to toggle a whole row/column. :-)
I believe this could be a pretty big mess though for realistic robots.
E.g. a PR2 has at least 38 links without modifications.
This is quite a lot to visualize as a matrix.

**Comment by rhaschke** [comment]
> I believe this could be a pretty big mess though for realistic robots.

Well, I think the current list is a mess. Using a scrollable table and having the ability to hide rows/columns will make this feasible, I hope.

We do have a bimanual Shadow Hand system with 54 joints for testing ;-)

**Comment by v4hn** [comment]
On Fri, Sep 16, 2016 at 03:34:53AM -0700, Robert Haschke wrote:
> Well, I think the current list is a mess.
> Using a scrollable table and having the ability to hide rows/columns will make this feasible, I hope.

Agreed, this *could* improve things.

> We do have a bimanual Shadow Hand system with 54 joints for testing ;-)

PR2+Shadow Hand+custom changes => 73 :-P

**Comment by v4hn** [comment]
I just tested the patch and it works. +1

Thanks @rhaschke I didn't know that slot functions can take less arguments than their signals until now.
This simplifies things quite a bit.

**Comment by davetcoleman** [comment]
cherry-picked to I/J

**Pull request merged**
