### PR TITLE
Melodic Backports

### PR DESCRIPTION
**Pull request by tylerjw**
### Description

Here are the backports for Melodic with trivial fixups to api and namespacing.

+ d5dcc9d6618bd14eed7bebf48a619a37a5f3a6fb Fix pose tracking race condition (#2395)
+ 382aa5a8cdd39eace07536d39c497a4b21f0f653 Fix QObject::connect: Cannot queue arguments of type 'QVector<int>' (#2392)
+ c616ef9aa86b34c4b237ca7b1cdd66c19dfc6f20 Fix empty sequence in moveit_setup_assistant (#2406)
+ e8f1a4c8156fd1655f9fa6d8e0c57806b4c2ec8b Move timer initialization down to fix potential race condition
+ 7f647b0594ef50674d711d97ac8f73b06bf06298 Changed processing_thread_ spin to use std::make_unique instead of new (#2412)
+ a15af07ee83b909ca5ef0a14e764dc87d62a93f1 [feature] Low latency mode (#2401)
+ bd53490301b4c0076483e713af082e44dfcd4074 Fix OrientationConstraint::decide (#2414)
+ 712a73a485226e7f7b9344136058347a4e2019ff Prevent moveit_servo transforms between fixed frames from causing timeout (#2418)
+ ad8ce6621bd676ef93f02d96753400d32ee6b58b docker-source: support running clang-tidy (#2430)
+ 10d6380438b2a5a5798ef9e02daf173e7a67b82c Upgrade cmake_minimum_required to 3.1 (#2453)
+ 253a2177f23c2d5e2e3fa415c75f720c9d6a98a5 Fix validation of orientation constraints (#2434)
+ 97c0b28f5580eadaade3f752f66f8eb12b0f7063 Fix doxygen documentation for setToIKSolverFrame (#2461)
+ 798b32f6769d3bd5635cf50a4aa3ef2a269558d3 Add an important sleep in Servo pose tracking (#2463)
+ da926ac95154ea2699247fedf6e3690b15d8eef3 Missing RViz and moveit_simple_controller_manager dependencies in MSA template (#2455)
+ abb83f178075b4d5bb655df2dc9dd3e400e258ca Fix some typos in comments (#2466)
+ be0cbaff7546348b9c19bd46a98ee253341f2c97 Catch exceptions during RobotModel loading in rviz (#2468)
+ ac55f9e252fb24321c4066d71bca4f447b55d961 Python3 compatibility for ikfast's round_collada_numbers.py (#2473)
+ 475e5810911961ae51cdb5cab0961471f5d4aa1a [Servo] Fix initial angle error is always 0 (#2464)
+ cc5d5a4e21c513e1527e306c2adaa8386a4bcef8 Fix RobotState::dropAccelerations/dropEffort to not drop velocities (#2478)
+ 50e19608d8d27a86f1e69fd2cd8c8b7abc330fb0 pilz planner: add string includes (#2483)
+ 680db65c14b3f0ac84beccd55bfc548719b8af84 Clean up collision-related log statements (#2480)
+ 0983cf9ab0a289af975971cc7374bd9182938b88 Fix scaling factor parameter names (#2452)
+ e573a36c6009c200c70d805d546865d0d1974bc9 Improve robustness of move group interface test (#2484)
+ 960745c8d7aaf8cec9703b810576d22cd321c54d Use kinematics solver timeout if not specified otherwise (#2489)
+ e32288400e80a1999474be4f076febb6c289046e Do not break out of loop -- need to update low pass filters (#2496)
+ 0e5911316ed51a765fc6b08a35f48c35f275e026 Protect paused_ flag, for thread safety (#2494)
+ 74b3e30db2e8683ac17b339cc124675ae52a5114 Add missing dependency on joint_limits_interface (#2487)
+ 8878682c2a71faf822db638a8ce21cedc512e4d5 Refactor Servo velocity bounds enforcement (#2471)
+ e986f6d709356920068610e22a424948baf95452 Servo: add missing include (#2519)
+ 47551054600f3445a4a243716bc1be6e18b5ff40 It's not an error not to define a plugin (#2521)
+ 41771d072341f488e075b747c2b2cb38267d579d Update README.md (#2525)
+ 7461264c20d2a5e9ddb4d322b16934640f7b7c30 Update doxygen comments for distance() and interpolate() (#2528)
+ 34b235692c41dac80a28186dff5021f46356ba65 Add debugging log statement for a common error (#2509)
+ f6fd34bbab6da4a1c72b7a532444c0075eee7001 add get_active_joint_names (#2533)
+ d18173b598846260d4e067ff604c3f3b29366f57 Add utility functions to Python PSI (#2532)
+ 30a170f224c37fc1f28de1640b8da0b3afef6614 thread safety in clear octomap & only update geometry (#2500)
+ ae7d1ad1c5eb2bdd65511fe9a4e8574b0f77241d Sanitize CHOMP initialization method parameter (#2540)
+ dd421646a6457e6ad90ee82c70ad0f45c5fffdbd Enable mesh filter (#2448)
+ 55b5878c0ece7b908d2209e85a4d64f966c2804b stop_requested_ flag clearing fix (#2537)
+ f4ebdd4a28e54ee6b3de61324446ea6bdda4b374 Fixed flood of errors on startup for `mesh_filter` (#2550)
+ 06b52899fb3526b6001ecf87324d77bc82d84dbe [Servo] Halt Servo command on Pose Tracking stop (#2501)
+ cd91cd10e01cd547f929ac93a8754ac174c1df6b Fix segfault in MSA (#2564)
+ d9b93ce646a5ff5aaa8cf9a4ceec926f0f1f1b85 Make setToIKSolverFrame accessible again (#2580)
+ 888c1ed5d90c1cbb23480c1df008440799b0c073 Keep MotionPlanningFrame hidden on Display::reset()
+ 393cee729a29c589fd6f78de1fe96025faaf9b53 Call renderPlanningScene() only if planning_scene_render_ is valid
+ 991335e01fd24a01d2bb1c8b15ae3cd1abadc6a0 Fix deadlock in PlanningSceneDisplay
+ 9de3111c65718db16efc5b5dcd72a9b20e256bda GHA: Add pre-release job
+ 550d386440d18465d759a34f983c7e7677c8729e Avoid joint jump when SuddenHalt() is called in velocity mode (#2594)
+ 3a61f184b82d01c75333292ca3e12ecd2765ecde Let users override fake execution type from demo.launch (#2602)
+ 58e1302648f69c70ecb4e729887152001bfc1121 Add clear() to Python PSI, allow empty call to remove_attached_object (#2609)
+ 224129a34c3ff8f7c584cb468999673822d3e383 Velocity limit error (#2610)
+ 824706ba8b6ad7e27c3acc3d1d9882d612973617 Call setStatus from main GUI thread only
+ d1fbbccf0ff77584920e48db2e63076359a397c7 Remove unused model_is_loading_
+ b598820b637658071ae370ff6f24ba2a7aadcbc9 Remove redundant planning_scene_render_.reset(); 
+ b13270be50ae7b43673cc5370bfe52a165c467e8 fix docstring in MGI API (#2626)

These patches are backported after resolving minor conflicts:

+ 59a372484f8f928152eec71bad636c58087d0f15 Provide a function to set the position of active joints in a JointModelGroup (#2456)
+ 8faed13a4dd27fd9181d0e606fe7ff64b27dae65 Fix missing isEmpty check in compute_ik service (#2544)
+ a3a4d8f97e3c0d2110dcd55883490cc58fcb92b1 Set rotation value of cartesian MaxEEFStep by default (#2614)
+ 9f9e69c54529e1aa156851abb6aae7047b20780d FixStartStateBounds: Copy attached bodies when adapting the start state (#2398)

These changes will not be backported for one reason or another or are already backported.

+ 225cb77cbd9d50e93c42d9e3ad6aa4490c6b30ed Add test to ompl interface for StateValidityChecker (#2247)
+ a461efe7dbef01328e3d72c1c83e66dce050eb2c Fix broken documentation link in README (#2393)
+ f85db808303cb7787320dc48162eabdc07593fdc [meta] first-timers-only issue template (#2385)
+ 0247ed0027ca9d7f1a7f066e62c80c9ce5dbbb5e [maint] Changelogs in pilz planner (#2408)
+ f56e17508c5f24f96c840a07243101f38f26096f Add Stargazer chart to README (#2417)
+ eca2deb1b80cbeb3eceaf00090ad853cc12851f2 Updated First Timers Only Issue Template (#2419)
+ bdd4bde4938c7bdac3a57a791cf738146c8834e0 Delete CollisionRequest min_cost_density
+ a9c8f939382193bc250788c62dd57c6627b25a2b Suppress warnings "mesh_use_embedded_materials is ignored"
+ 664ae01803abf5e0b4649063102357262de9e05c Improve robustness of subframes test (#2488)
+ 6512d987b8379519146193267906ee957586c4e8 resolved typo in first-timers-only.md (#2443)
+ ea5080167be92f1ed4441b560f9d94d542b06f4c Fix logic, improve function comment for clearDiffs() (#2497)
+ b7711c134a8a1e173c9bf956f68ad8bbe27796c4 Replaced eigen+kdl conversions with tf2_eigen + tf2_kdl (#2472)
+ a3023013b8df3d17b711e09124eb82e5e3982d58 increase time limit (#2545)
+ eb3bf6fdb6ece5324e3d1a81fd5d2b2197804710 Move moveit_cpp to moveit_ros_planning
+ 5f486dd74adb867443393ee3afd36fa476b6c57c Allow selecting planning pipeline in RViz MotionPlanningDisplay
+ 8df40df56ad58a6358834129b09b3a8b2c35a02c Run multiple planning pipelines with MoveGroup using MoveItCpp
+ db9cecc8955a0c8b6867517835820d87219d1e21 Update MSA launch templates for multi-pipeline support
+ 50614c640b96f550abd235f72bb6b84f88d4eca3 PlanExecution: Correctly handle preempt-requested flag (#2554)
+ 3b9977d18e4e838d103d71fd9b84534874981477 Migrate from Travis to GitHub Actions
+ b618bac5c84055f2354267ea2a0317cc9b1a547e Fix formatting errors
+ a8326da6cc420000b399e78f4048bf5df2abefca Update README for GitHub Actions
+ 3361b2d1b6b2feabc2d3e93c75653f5a00e87fa4 Python bindings for moveit_core (#2547)
+ f0e850af900b0ec438c00f8f6afabf17b6379107 Shift catkin_lint to pre-commit checks (#2569)
+ b1a17dcb7245ae1fd2312f5239a724d297d43b9a Add Readme line on how to ping someone (#2555)
+ 412a6f2c83c83446bb04232e1c0e8accf467c9c8 1.1.2
+ 90e70a59aa05ba8fe7413ed8b8dddba7bea06c71 Improve job naming
+ ae770f7446ab7406f813a47cfe70ee032c1d9f38  Lock the Bullet collision environment, for thread safety (#2598)
+ cf218879dbc23aadf88dd56b8abe7970b7d61030 Add Pilz industrial motion planner (#1893)
+ 460c152ab9f713f2606e345fd0f6abc07cd2c13e Order PlaceLocations by quality during planning (#2378)
- 09afa50b40ac8cb8644ba1a627bb7643137959d3 Update collision-related comments (#2382) (#2388)
- 7e1ccecde9b956c358d9d40630b13635171ec70d RobotModelBuilder: Allow adding end effectors (#2454)
- 5d2549fe5018bca5fa5cf22f90ecdc7b8b3f7762 RobotModelBuilder: Add parameter to specify the joint rotation axis

After this the `review-for-backports` tag can be moved to b13270be50ae7b43673cc5370bfe52a165c467e8

This also adds the pre-release test for melodic so we can run it here.

### CODE REVIEW

**Comment by v4hn** [comment]
Thank you so much for doing this. Your selection looks reasonable to me.
I agree that we don't have to backport collision-related patches through the CollisionRobot/World -> Env refactoring.

I went through the trouble and backported five more commits with minor conflicts that address usability issues or fix critical issues.
- https://github.com/ros-planning/moveit/commit/8faed13a4dd27fd9181d0e606fe7ff64b27dae65
  - removes an unnecessary error message
- https://github.com/ros-planning/moveit/commit/a3a4d8f97e3c0d2110dcd55883490cc58fcb92b1
  - makes sure users who specify a step size actually get one for orientations as well
- https://github.com/ros-planning/moveit/commit/460c152ab9f713f2606e345fd0f6abc07cd2c13e
  - prefer correct place locations during Place action
- https://github.com/ros-planning/moveit/commit/9f9e69c54529e1aa156851abb6aae7047b20780d
  - safety-critical edge-case for planning with attached objects
- https://github.com/ros-planning/moveit/commit/59a372484f8f928152eec71bad636c58087d0f15
  - assert on API-misuse instead of overwriting wrong value

I pushed directly to the PR branch.

**Comment by tylerjw** [comment]
I rebased this and changed the pre-release test to always run for pull requests to melodic-devel.  This seems to make sense to me as the melodic-devel branch is for releasing backports to melodic not for active development.

**Comment by rhaschke** [comment]
I don't agree. I think we still get PRs against Melodic from external contributors.  They shouldn't automatically trigger a full pre-release test.

**Review by rhaschke — APPROVED** [review]
@tylerjw, could you please squash my last three commits into one before merging?

**Comment by rhaschke** [comment]
prerelease test succeeded: https://github.com/ubi-agni/moveit/runs/2473376931

**Comment by rhaschke** [comment]
I got this failure:
```
Full test results for 'build/moveit_ros_planning_interface/test_results/moveit_ros_planning_interface/rosunit-move_group_interface_cpp_test.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="3" failures="1" disabled="0" errors="0" timestamp="2021-04-30T08:33:00" time="15.552" name="AllTests">
  <testsuite name="MoveGroupTestFixture" tests="3" failures="1" disabled="0" errors="0" time="15.551">
    <testcase name="PathConstraintCollisionTest" status="run" time="6.15" classname="MoveGroupTestFixture">
      <failure message="/home/runner/work/moveit/moveit/.work/target_ws/src/moveit/moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp:255&#x0A;      Expected: planning_scene_interface_.getObjects().size()&#x0A;      Which is: 1&#x0A;To be equal to: std::size_t(0)&#x0A;      Which is: 0&#x0A;Google Test trace:&#x0A;/home/runner/work/moveit/moveit/.work/target_ws/src/moveit/moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp:155: PathConstraintCollisionTest" type=""><![CDATA[/home/runner/work/moveit/moveit/.work/target_ws/src/moveit/moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp:255
      Expected: planning_scene_interface_.getObjects().size()
      Which is: 1
To be equal to: std::size_t(0)
      Which is: 0
Google Test trace:
/home/runner/work/moveit/moveit/.work/target_ws/src/moveit/moveit_ros/planning_interface/test/move_group_interface_cpp_test.cpp:155: PathConstraintCollisionTest]]></failure>
    </testcase>
    <testcase name="CartPathTest" status="run" time="5.4" classname="MoveGroupTestFixture" />
    <testcase name="JointSpaceGoalTest" status="run" time="4.001" classname="MoveGroupTestFixture" />
  </testsuite>
</testsuites>
```
Is this a new flaky test?

**Comment by v4hn** [comment]
> Is this a new flaky test?

Looks like it, [we saw the same error before and rerunning resolved it](https://github.com/ros-planning/moveit/pull/2622#issuecomment-828403503).

**Comment by tylerjw** [comment]
@rhaschke rebased on melodic-devel (squashing your last three into one) and pushed.

**Comment by tylerjw** [comment]
Running the pre-release test here: https://github.com/tylerjw/moveit/runs/2494130551?check_suite_focus=true

**Comment by tylerjw** [comment]
> Summary: 1474 tests, 0 errors, 0 failures, 1 skipped

This passes pre-release.  I say we merge it and near the end of this week we cut a Melodic release.  Thoughts? @v4hn @rhaschke

**Comment by tylerjw** [comment]
I talked with @v4hn and we think we should let these soak on melodic-devel for a while (to hopefully get more backports) and wait to cut the melodic release until right after the next sync to get the most possible time in testing as there are a ton of changes here.

**Pull request merged**
