### PR TITLE
Update doxygen comments for distance() and interpolate()

### LINKED ISSUE #2527: JointModel interpolate() -- time argument is a misnomer
The [interpolate()](http://docs.ros.org/en/noetic/api/moveit_core/html/revolute__joint__model_8cpp_source.html#l00191) function takes an argument called `t`:

`  void RevoluteJointModel::interpolate(const double* from, const double* to, const double t, double* state) const`

The [description](http://docs.ros.org/en/noetic/api/moveit_core/html/classmoveit_1_1core_1_1RevoluteJointModel.html#a8ced1a14641a067315971c6bfa284384) says:

`Computes the state that lies at time t in [0, 1] on the segment that connects from state to to state. The memory location of state is not required to be different from the memory of either from or to. `

So it seems `t` is really a fraction. I think this is confusing.

### PR DESCRIPTION
**Pull request by AndyZe**
Update documentation of `interpolate()` and `distance()` to clarify a few things:

- The `t` parameter of interpolate isn't a time, it's a fraction
- `distance()` just sums the joint difference, for all joints. It's not an L2 norm or SSE or anything like that. Verify [here](http://docs.ros.org/en/noetic/api/moveit_core/html/robot__model_8cpp_source.html#l01236).

Fixes #2527

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
Thank you for doing this!  I read through these and they look good.  I'll merge this once it passes CI if no one else requests changes.

**Review by simonschmeisser — APPROVED** [review]
thanks especially for the corner-case info about active joints!

**Comment by v4hn** [comment]
> `distance()` just sums the joint difference, for all joints. It&#39;s not an L2 norm or SSE or anything like that.

Just because of the way you formulate this: summing up element-wise differences is the standard [L1 norm](https://en.wikipedia.org/wiki/Taxicab_geometry) and I'm missing that term a bit in your patch. There was even a proposal to add weighting to the components, but it was not merged as far as I know.

**Comment by AndyZe** [comment]
> `distance()` just sums the joint difference, for all joints. It&#39;s not an L2 norm or SSE or anything like that.
> Just because of the way you formulate this: summing up element-wise differences is the standard [L1 norm](https://en.wikipedia.org/wiki/Taxicab_geometry) and I'm missing that term a bit in your patch. There was even a proposal to add weighting to the components, but it was not merged as far as I know.

I'm porting this to MoveIt2 now and will mention L1 norm  :+1:

**Pull request merged**
