### PR TITLE
Cherry Picking #596  into indigo-devel

### PR DESCRIPTION
**Pull request by jrgnicho**
### Description

Cherry Picking #596  into indigo

### CODE REVIEW

**Comment by v4hn** [comment]
CI failed

**Comment by jrgnicho** [comment]
Looks like the `load_robot_model_` does not exists as a member of the class. I'll add it and push again.

**Comment by v4hn** [comment]
ping @jrgnicho

**Comment by jrgnicho** [comment]
@v4hn finally got around to it, please review.

**Pull request merged**
