### PR TITLE
Fix typo in first-timer-only issue template

### PR DESCRIPTION
**Pull request by pawanw17**
### Description

Fixed few typos in first-timers-only.md file

### Checklist
- [x] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by tylerjw — APPROVED** [review]
This looks good to me.

**Comment by tylerjw** [comment]
> ### Checklist
> * [ x ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
> * [ x ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
> * [ x ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
> * [ x ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
> * [ x ] Include a screenshot if changing a GUI
> * [ x ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

Small note on the checklist, one thing I like to do is just remove lines that don't matter for this PR.  For example, this doesn't change any code checked by clang-format so you can just remove that line.  Next this doesn't affect any tutorials, so you can remove that one.  There are no API changes that need documenting, remove that one.  This isn't something that makes sense to test, remove that one.  This doesn't change any gui elements, remove that one.  The only one that applies is the PR review.  Did you review another PR?

Also, a style thing is that if you don't put a space between the bracket and the x, like this: `[x]` it will result in a check mark like this: [x].

This is just a style thing and doesn't really matter.  Lastly about this PR getting merged, we need travis (CI) to pass before we'll merge it.  However CI has been really slow and flaky recently so it might be a few days before we can get this merged.  I'm working on fixing the CI issues.

**Comment by pawanw17** [comment]
Thanks alot @tylerjw for the insights! I'll keep those in mind for next time.

**Review by simonschmeisser — CHANGES_REQUESTED** [review]
The website seems to https://www.firsttimersonly.com/ Is it actually a typo here or usage of plural?

Also this should really be only one commit, can you please read up on interactive rebase using git and change it to be only one commit (also there's a typo in your commit message)

**Comment by pawanw17** [comment]
@simonschmeisser Actually in the issue it was mentioned to change first-timers-only to first-timer-only... I'll look it up to make a single commit ... should I make another pull request or I can make changes in this one, I'd really appreciate any help.

**Comment by simonschmeisser** [comment]
If you push again to your branch this will be updated, you might need to use `git push --force` or better `git push --force-with-lease`

**Comment by pawanw17** [comment]
@simonschmeisser but it is already updated in my branch templateissue#2425 then how to add a commit again? :/

**Comment by pawanw17** [comment]
Hey @simonschmeisser I was able to change the commits from 2 to 1 by git push force-with-lease, Thanks for your help! :)

**Comment by simonschmeisser** [comment]
Nice, now please also use the edit function to clean up the checklist and provide a summary of your PR like Tyler suggested.

**Review by simonschmeisser — APPROVED** [review]
Thanks for following up on all the small details :)

**Comment by pawanw17** [comment]
Thanks for all the help!

**Comment by tylerjw** [comment]
I restarted the CI run of this.  It seems that it is failing for issues with a couple of tests.  We are aware of these issues and are working to resolve them.  In the meantime re-running the CI job might be enough to get this to pass.

**Comment by tylerjw** [comment]
Travis is regularly passing now on master.  Would you mind rebasing this change on the latest commit in the master branch.  Here are some instructions for how to do that.

First, you need two remotes, one for your fork and one for upstream.  

1. To make this easy install the github command-line interface: https://cli.github.com/
2. Run this command:

```
 gh repo fork --remote 
```

After this if you list your remotes (`git remote -v`) it should look something like this:

```
origin  git@github.com:tylerjw/moveit.git (fetch)
origin  git@github.com:tylerjw/moveit.git (push)
upstream        git@github.com:ros-planning/moveit.git (fetch)
upstream        git@github.com:ros-planning/moveit.git (push)
```

The `origin` remote should point to your fork.  Another way you can manipulate the remotes is with the `git remote add` and `get remote rm` commands.  Here is the documentation on how to use those commands: https://git-scm.com/docs/git-remote

3. Now we need to fetch the latest from the `master` branch on the `upstream` remote.

```
git fetch upstream
```

4. With `upstream` updated we can now rebase.  This will rewrite the history of your branch by applying your commits over the top of the latest commits on master.  Before we do this we want to make sure we are on the branch of your PR.

```bash
gh pr checkout 2443              # this will make sure you are on your PR branch
git rebase upstream/master   # this will rewrite the history of your branch
```

5. Lastly, you need to push the change you just made to your branch to your fork.  Here we have to use a special push command because we have overwritten the history of the branch.

```
git push --force-with-lease origin templateissue#2425
```

**Comment by pawanw17** [comment]
Hey @tylerjw I tried out the steps, but Travis is still failing :/

**Pull request merged**
